### PR TITLE
Fix uploading creds

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3172.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- start a new model
- add an app
- open the deployment flow
- choose gce
- open the add creds form
- click 'upload ... json auth-file'
- choose a file
- the box should change to read "File stored"

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8025/

**Comment by frankban** [comment]
QA is ok: I was able to deploy a model after adding GCE credentials via the file.

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
