### PR TITLE
Ecs bits

### PR DESCRIPTION
**Pull request by makyo**
This fixes some errors that were showing up in the console with the interaction between the ECS and the bundle importer.

Addresses https://bugs.launchpad.net/juju-gui/+bug/1457213 and https://bugs.launchpad.net/juju-gui/+bug/1454765

### CODE REVIEW

**Comment by makyo** [comment]
# QA

* Deploy the trunk version of the gui charm
* `juju set juju-gui juju-gui-source="https://github.com/makyo/juju-gui.git ecs-bits"`
* `juju set juju-gui sandbox=true`
* `juju set juju-gui juju-gui-console-enabled=true`
* Deploy a bundle - there should be no errors in the console
* Commit the changes leaving the units unplaced - no errors
* Refresh
* Deploy a bundle - no errors
* Commit the changes autoplacing or manually placing units - no errors

## NB

Local QA uncovered a bug in the ECS not covered by this branch - deleting the services one by one while they're uncommitted leaves the pending relations in the database.  This will be fixed in a follow up branch.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2558/
Test PASSed.

**Comment by hatched** [comment]
:+1:

**Comment by hatched** [comment]
QA Issue:

After dragging the django bundle to the canvas I switched to the machine view and the units had the service temp id instead of the name.

screenshot from 2015-05-22 15 30 05

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2561/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2562/
Test PASSed.

**Comment by hatched** [comment]
QA OK! I would like to see a test for the unit display names though.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2563/
Test PASSed.

**Comment by hatched** [comment]
Thanks for the updates! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
