### PR TITLE
Fix deploy placement

### PR DESCRIPTION
**Pull request by huwshimi**
Can't return undefined from a stateless component.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add a service
- open the machine view and place the unit
- click deploy
- the summary should appear and there should be no error in your browser console

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3598/
Test PASSed.

**Comment by hatched** [comment]
:+1: QA :ok: Thanks!

QA Notes:
I deployed multiple services, related them, removed relations, commited the changes, then removed and re-created the relations again. All worked as expected.

**Comment by kadams54** [comment]
:+1: from me as well.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
