### PR TITLE
Prepare app for the inspector component

### PR DESCRIPTION
**Pull request by hatched**
To support the new component rendering cycle and the new inspector/added services views we need `state.dispatch()` to be idempotent so that we can call it whenever there is a database change to update the UI using the existing app state.

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2879/
Test PASSed.

**Comment by makyo** [comment]
Sweet, :+1: QA OK

Looking forward to the inspector work.

**Comment by kadams54** [comment]
:+1: Code looks good. Thanks!

**Comment by hatched** [comment]
Thanks for the reviews! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
