### PR TITLE
[#2214] Center the empty profile CTA.

### LINKED ISSUE #2214: Empty state for the profile had an off centered button
screen shot 2016-11-21 at 11 12 40

### PR DESCRIPTION
**Pull request by kadams54**
Fixes #2214.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6230/
Test PASSed.

**Comment by kadams54** [comment]
## QA

1. Modify line 95 in `section-load-watcher.js` to be: `if (true):` - this will force the empty user profile page to load.
2. `make run`
3. Head to `http://0.0.0.0:6543/profile/`.
4. Verify that the button is centered as spaced appropriately from the text above it.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
