### PR TITLE
Add a tooltip to the model list permissions icons

### LINKED ISSUE #3445: New Profile: Add tooltips to permissions icons

### PR DESCRIPTION
**Pull request by hatched**
Fixes #3445

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Load the GUI with the profile flag and then hover over the permissions icon the model list. 
Also click to expand the model info and the hovers should still work.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8478/

**Comment by hatched** [comment]
Thanks @huwshimi :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
