### PR TITLE
Add support for Service.Get API call. Update and fix sandbox mode API.

### PR DESCRIPTION
**Pull request by frankban**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4451/
Test PASSed.

**Comment by hatched** [comment]
:+1: :ok: on Sandbox

**Comment by frankban** [comment]
QA ok on embedded GUI as well, no more "Client.ServiceGet not implenented" errors.

**Comment by frankban** [comment]
Thank you Jeff for the review and QA!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
