### PR TITLE
Created a template for the karma-mocha-phantom.conf.js file

### PR DESCRIPTION
**Pull request by hatched**
Create a template instead of modifying the conf file directly so that we don't have to deal with accidentally checking it in later.

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

If CI passes it's good

**Comment by frankban** [comment]
:+1:

**Comment by kadams54** [comment]
:+1: on the code

**Comment by bac** [comment]
:+1:

**Comment by hatched** [comment]
:) thanks all :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4085/
Test FAILed.

**Comment by hatched** [comment]
Spurious failure

**Pull request merged**
