### PR TITLE
Support namespaced bundle id's with deploy-target

### PR DESCRIPTION
**Pull request by hatched**
Bundles can have two different formats for their id's `bundle/django` and namespaced `~jorge/bundle/django`

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA
Try and deploy the two bundles above by visiting the following paths with this GUI instance.

`<host>?deploy-target=bundle/django`
`<host>?deploy-target=~jorge/bundle/django`

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2375/
Test PASSed.

**Comment by makyo** [comment]
:+1: Works well!  Thanks for the quick turn-around.

**Comment by huwshimi** [comment]
Code looks good, thanks @hatched! :+1:

**Comment by hatched** [comment]
Thanks for the reviews and qa! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
