### PR TITLE
Disable plan info and display machines

### PR DESCRIPTION
**Pull request by huwshimi**
Update the deployment flow to hide the plan info for now. Display the real machine info.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add a service
- add a machine with some constraints
- click deploy
- you should see machines with constraints
- you should not see anything about plans or budgets

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5775/
Test PASSed.

**Comment by jaycee** [comment]
Thanks @huwshimi

**Comment by hatched** [comment]
Thanks @huwshimi !

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
