### PR TITLE
Fix feature store items in GiJ

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3584.

### CODE REVIEW

**Comment by huwshimi** [comment]
[Fix feature store items in GiJ](https://trello.com/c/BvPy5aN3/415-fix-feature-store-items-in-gij)

**Comment by huwshimi** [comment]
QA:
- load the GUI for GiJ
- open the store
- you should only see three feature blocks at the top (not four like the attached bug)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8579/

**Comment by huwshimi** [comment]
Thanks @frankban that should hopefully be fixed now.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8586/

**Comment by frankban** [comment]
It's now looking good on gijoe.
On gisf (firefox) I see the elephant taking off...

screen shot 2018-03-20 at 17 09 39

**Comment by huwshimi** [comment]
@frankban OK, hopefully THIS time!

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8589/

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
