### PR TITLE
Implement isLegacyJuju on the app.

### PR DESCRIPTION
**Pull request by frankban**
So that the logic is more clearly reusable.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5285/
Test PASSed.

**Comment by makyo** [comment]
👍

**Comment by hatched** [comment]
Thanks @frankban :+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5286/
Test PASSed.

**Comment by frankban** [comment]
Thanks for the reviews!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
