### PR TITLE
Temporarily add logout button to header

### LINKED ISSUE #1190: Add the ability to log out of the GUI
We appear to have lost this functionality in the new UI

### PR DESCRIPTION
**Pull request by hatched**
The logout button will eventually be hidden under a profile link, but for now we just have a logout button. Fixes #1190

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Test that you can log out and log back in in:
- sandbox
- non-JES
- JES

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4124/
Test FAILed.

**Comment by hatched** [comment]
ci passed when run manually http://ci.jujugui.org:8080/job/juju-gui/4126/

**Comment by bac** [comment]
QA was fine for deployed with JES and not JES.
With sandbox (i.e. 'make qa-server') there was not login and there is not logout button.

**Comment by bac** [comment]
:+1:

**Comment by makyo** [comment]
:+1:

**Comment by hatched** [comment]
Thanks! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
