### PR TITLE
Focus on the search box when the mid-point is opened

### LINKED ISSUE #1454: When opening the midpoint, the user should be able to start typing a search straight away without having to click on 'Search the store'

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #1454.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4634/
Test PASSed.

**Comment by anthonydillon** [comment]
Code :ok: QA :+1:

**Comment by hatched** [comment]
:+1: :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
