### PR TITLE
Replace d3 asset with the npm module

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3253.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- do a bunch of canvas stuff e.g. adding app, relations, zooming, panning etc.
- everything should work, there should be no console errors

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8174/

**Comment by hatched** [comment]
How does the dist size compare with the one we had vendored? It was generated using this project https://github.com/juju/juju-gui-d3/blob/master/Makefile

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8179/

**Comment by hatched** [comment]
Thanks @huwshimi :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
