### PR TITLE
Remove onboarding.

### PR DESCRIPTION
**Pull request by huwshimi**
Remove the onboarding as it is out of date.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- in a new or private browser load the gui
- you should not see the onboarding

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3515/
Test PASSed.

**Comment by hatched** [comment]
:+1: QA :ok:

**Comment by fabricematrat** [comment]
:+1:  code :ok:  thanks for removing all this code !

**Comment by jaycee** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/1203

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
