### PR TITLE
Add new invoice component

### PR DESCRIPTION
**Pull request by barrymcgee**

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8497/

**Comment by spencerbygraves** [comment]
@barrymcgee thanks, looking good. I have some feedback below.

Looking at it now, I think we could just have the invoice on a white page and scroll normally if needed, as on small screen. I'm not keen on the scroll within the card. Would it be ok/easier for you to remove it?

- [ ] Update the logo to the current/newer version as on jujucharms.com

**Large screen**

- [ ] The invoice title to be 45px
- [ ] Invoice number and total amount to be 32px
- [ ] Details table title to be 23px
- [ ] Can we have the space under each of the 1px lines be 16px please, except for the first one, which I made 8px as the invoice title is bigger
- [ ] Can we change the margin under 'Services during the period' and 'Questions?' to be the same as that in between 'VAT number' and 'VAT @ 20%' etc
- [ ] Canonical logo 16px high if possible


**Small screen**

- [ ] The space above each 1px to be 32px, and 16px below
- [ ] Invoice number and total amount is be 23px
- [ ] Details table title should be 20px
- [ ] All text in the table cards 16px
- [ ] Can we reduce the space between the model name and number of hours please, so they are grouped better. I had it as 4px in the design
- [ ] Canonical logo 16px high if possible

Thanks

**Large screen without card**
image

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8505/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8506/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8507/

**Comment by spencerbygraves** [comment]
@barrymcgee Thanks. Can we set the invoice font-weight to 400 please, and the old logo is still at the top, can we update it please.

Is it essential that the invoice scrolls within a div? I think a normal page scroll would be better.

Thanks

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8542/

**Pull request closed without merging**
