### PR TITLE
Add a workaround for the contenteditable bug in Firefox.

### PR DESCRIPTION
**Pull request by frankban**
Fixes https://github.com/juju/juju-gui/issues/3401

### CODE REVIEW

**Comment by frankban** [comment]
QA:
Use both firefox and chrome.
- deploy nagios;
- use the inspector to change the charm configuration; 
- scroll down and find an empty option;
- check that you are able to edit the option.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8385/

**Comment by hatched** [comment]
QA is ok, thanks @frankban. I also found another FF bug https://github.com/juju/juju-gui/issues/3402

**Comment by frankban** [comment]
Thanks for the QA @hatched , and good catch for the new bug.

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
