### PR TITLE
Fix the font size of the expanded profile entity details

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3515.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- open your profile charm list
- expand a charm
- the charm title should go bold, but not get massive

**Comment by huwshimi** [comment]
[Fix the font size of the expanded profile entity details](https://trello.com/c/VonlwGCz/333-fix-the-font-size-of-the-expanded-profile-entity-details)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8523/

**Comment by mitechie** [comment]
QA ok, ty. 

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Comment by cassiocassio** [comment]
### On titles in various profile lists, both open and closed

Having seen this I'm almost afraid to mention these two issues to @huwshimi that were the result of comments from @barrymcgee about the link styling in the open state.

Original query - includes videos
## https://github.com/juju/juju-gui/issues/3438

Proposed solutions
## https://github.com/juju/juju-gui/issues/3460

(This PR undoes 3460)

### Models too...

@mitechie has been thinking  about the **analagous** issue for **model lists** here: https://github.com/CanonicalLtd/juju-design/issues/438 - which @spencerbygraves and I were planning to harmonise with charms and bundles in a future enhancement. @hatched has pointed out to me how we're not likely to do those model enhancements (e.g. thumbnails of models) soon, although I had hoped to add .ssh buttons to open the model with a shell. 

### to summarise:

In the **closed state:**
- **Blue links titles** are reserved for the title of a thing the user can navigate to, e.g. the model in the canvas, or the entity page.

- other fragments might also be links, e.g. tags in charms, in a variety of greys or black, depending on the information design.

In the **open state:**

- Titles have to serve as the **title of the whole card**, which can now be quite big, so they need to be visually stronger

- Titles still are links, since they offer than navigation, so some (@barrymcgee and @mitechie) thought it was odd if they turned black and bold - it looked like opening the card had made the links dead (even though there are still links). So the argument is that they should remain blue

- Open cards have a **mixture** of

1. extra content, e.g. the charm description - _body text_
2. info that are also links, e.g. charm authors, credential names, - _blue links_ 
3. labels, e.g. "Writable:",  which were previously regular (bold looking - this had the unfortunate effect of making these relatively unimportant labels look stronger than the title of the whole card. 

This is  why we made these labels light, and added the : (colon) which we don't usually use in the UI.

so: 

- what might have made sense as two separate designs in the spec, didn't make sense when you toggled open and closed

- the big might indeed be too big.

Let's try and resolve across all the profile items open and closed, and come to a final conclusion. Apologies for open-card-title-style-gate.

**Pull request merged**
