### PR TITLE
Added the more menu component.

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3754/
Test PASSed.

**Comment by huwshimi** [comment]
QA:
- use the flag `/:flags:/mv/`
- open the machine view
- notice that there is a more menu in the machine column header
- clicking the more menu should open it
- clicking outside should close it

**Comment by hatched** [comment]
:+1: QA :ok:

**Comment by huwshimi** [comment]
Thanks @hatched! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
