### PR TITLE
Set the base asset path in the GUI to match Juju 2

### LINKED ISSUE #1538: favicon not in proper place for it to be served statically
The path being requested for the favicon asset is: 

`https://54.185.245.225:17070/gui/750d1963-e03f-40f7-8b58-755bd10421ca/4aadf3998dea043dea186a32f7d01da1c0078c036280db00caedfa460c1b9f25/juju-ui/favicon.ico`

when it should be in the asset path.

### LINKED ISSUE #1546: Update css asset locations to use Juju 2 asset location

### PR DESCRIPTION
**Pull request by hatched**
To simplify the codebase set the default asset path to match Juju 2. Fixes #1546 Fixes #1538

### CODE REVIEW

**Comment by jaycee** [comment]
:+1:

**Comment by bac** [comment]
:+1:
will qa now

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4823/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4824/
Test PASSed.

**Comment by hatched** [comment]
#### To QA

In addition to the QA instructions found here: https://github.com/juju/juju-gui/pull/1540#issuecomment-208620222

Click on the relation line joining two of the services and it should have a green arrow and trash can in the menu that pops up.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4825/
Test PASSed.

**Comment by bac** [comment]
QA-suspicious

From GIJoe testing. FF on wily:

screen shot 2016-04-12 at 16 24 40

**Comment by bac** [comment]
Also I see no favicon,

**Comment by bac** [comment]
USER ERROR!

QA-OK

green arrow, trashcan, and favicon all seen.

**Comment by hatched** [comment]
Awesome thanks for the reviews and qa! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
