### PR TITLE
Update selenium version: attempt to unblock CI.

### PR DESCRIPTION
**Pull request by frankban**

### CODE REVIEW

**Comment by bac** [comment]
Download cache has been updated?

:+1:

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2715/
Test PASSed.

**Pull request merged**
