### PR TITLE
Improve handling of unknown charm series and add bionic

### PR DESCRIPTION
**Pull request by frankban**
This also fix an issue currently on production: if you search openstack the result page does not show up and errors are present in the console.

Fixes https://github.com/juju/juju-gui/issues/3601

### CODE REVIEW

**Comment by frankban** [comment]
To QA:
- on gijoe, open the store and click to see openstack results;
- on gisf, search for openstack.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8592/

**Comment by mitechie** [comment]
QA ok ty!

**Comment by frankban** [comment]
Thank you both!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
