### PR TITLE
[#2230] Fix CSS path for white buttons in DF.

### LINKED ISSUE #2230: 'Change cloud' button should have a white background

### PR DESCRIPTION
**Pull request by kadams54**
Fixes #2230.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6241/
Test PASSed.

**Comment by kadams54** [comment]
## QA

Prerequisite: you'll need to hook up to JIMM. You can do this while running the GUI locally by following the instructions in `development.ini` then doing a `make run`.

1. Deploy something so that you get into the deployment flow.
2. Select a cloud provider; you may also need to setup credentials.
3. Once you're at the summary at the end of the workflow, verify that the "Change cloud" button has a white background.

**Comment by anthonydillon** [comment]
untitled model juju gui

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
