### PR TITLE
Update generated name for multiple same services.

### LINKED ISSUE #1287: Adding a charm to the canvas twice sets an invalid service name
If you add the "ubuntu" charm to the canvas, then add it again, you'll have one with the service name "ubuntu", and one with "ubuntu-2". The latter is not a valid service name, according to Juju.

screenshot from 2016-01-27 13 55 15

Also, when I deleted the second service from the canvas after that failure came up, references to "21018070$" started showing up in the UI.

screenshot from 2016-01-27 13 55 09

### PR DESCRIPTION
**Pull request by hatched**
When adding multiple services to the canvas with the same charm update the name properly to create a valid charm name for Juju.
Fixes #1287

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Deploy into a real environment and deploy the ubuntu charm twice. The second should have the name 'ubuntu-s2' and it should deploy without error.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4281/
Test FAILed.

**Comment by hatched** [comment]
CI ran out of disk space, after making more space it passed: http://ci.jujugui.org:8080/job/juju-gui/4283/

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4286/
Test PASSed.

**Comment by bac** [comment]
:+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4289/
Test PASSed.

**Comment by huwshimi** [comment]
QA OK :+1:

**Comment by hatched** [comment]
Thanks for the reviews and qa! Sending in the squirrel :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
