### PR TITLE
Provide defaults when model information is missing.

### PR DESCRIPTION
**Pull request by kadams54**
Fixes https://github.com/juju/juju-gui/issues/1545.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4820/
Test PASSed.

**Comment by hatched** [comment]
:+1: But this has a lot of extraneous commits, can you remove those please.

**Comment by kadams54** [comment]
Extraneous commits removed. :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4821/
Test PASSed.

**Comment by bac** [comment]
Thanks @kadams54

**Pull request merged**
