### PR TITLE
Fixes automatic charmstore login from the canvas usso login link

### PR DESCRIPTION
**Pull request by jaycee**

### CODE REVIEW

**Comment by jaycee** [comment]
QA:

In a private window with cache disabled spin up the gui with guiproxy, using `-config 'gisf:true, jujuEnvUUID:""'`. Go to /new/. Click the "Login" link in the upper right hand window, and allow popups to go through the full login process. You should then see your username in the breadcrumb in the left.

Click it to go to your profile. There should be no "Log in to charm store" button and you should see your charms/bundles if you have any.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6838/

**Comment by hatched** [comment]
QA Notes:

After following the instructions sometimes I would close the popup window and I would already be on the profile, sometimes I'd be on the canvas. Both times a new popup would be trying to load to discharge to identity.

**Comment by hatched** [comment]
After discussion with @jaycee - it is working when configured properly :)

However there does appear to be a race condition in state but that's separate from this branch.

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
