### PR TITLE
Display the user details on the account page

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7162/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7163/

**Comment by huwshimi** [comment]
QA:
- if you have a user, open your account page
- you should see your name, email addresses etc.

**Comment by jaycee** [comment]
QA OK. Thanks!

**Comment by huwshimi** [comment]
Thanks @hatched, @jaycee. :shipit:.

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
