### PR TITLE
Do not show the @external domain in the profile page.

### PR DESCRIPTION
**Pull request by frankban**

### CODE REVIEW

**Comment by frankban** [comment]
**QA** must be done in both gijoe and gisf scenarios.
For gisf, at this stage you can use `guiproxy -config 'gisf: true, jujuEnvUUID: ""'`.

- log in and go to the profile page as a local user: you should see the `@local` domain in the profile header;
- log in and go to the profile page as an USSO user: you should see no domain in the profile header;
- navigate and switch between models, from the profile page and from the model switcher, everything should work as usual.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6805/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6806/

**Comment by Lukewh** [comment]
QA OK

**Comment by hatched** [comment]
QA OK :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
