### PR TITLE
Add eslint rules

### PR DESCRIPTION
**Pull request by huwshimi**
Add rules to eslint for `debugger;` and unused variables.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3446/
Test PASSed.

**Comment by hatched** [comment]
:+1: Wow that was a lot of unused code :)

**Comment by jaycee** [comment]
:+1:

**Comment by hatched** [comment]
:shipit:

**Comment by jaycee** [comment]
QA notes:

In sandbox I did the usual routine of setting up wordpress with mysql. I manipulated machines, deployed, configured, and destroyed the whole thing. I encountered no issues.

QA :ok:

**Comment by jaycee** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
