### PR TITLE
Fix QA errors found while testing the new ES6 class based components.

### PR DESCRIPTION
**Pull request by frankban**
Also update the inspect-components script so that it handles class based components.

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7833/

**Comment by jaycee** [comment]
QA notes:

Using a dist uploaded into LXD with `juju upgrade-gui`:

* Loaded my active model (previously created with the CLI) correctly
* Switched between default and the new model
* Created a new model, and deploy cs:ubuntu from search results using the left hand button
* Switched to the profile
* Created another new model, deploying kibana from its details page
* Went back to the canvas from DF on the kibana model
* Actually deployed kibana
* Switched between all models
* Destroyed the ubuntu application
* Destroyed the ubuntu model
* Destroyed the kibana model with still active kibana application

I saw no errors.

QA OK for GIJoe.

**Comment by frankban** [comment]
Thank you both for the reviews!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
