### PR TITLE
Hide the drop notification if there is an error with the file

### LINKED ISSUE #2295: Dragging a non-charm zip to the canvas blocks future canvas interactions
Drag a non-charm zip file to the canvas. It throws a notification error but the 'drop' mask never disappears. 
https://github.com/juju/juju-gui/pull/2287#issuecomment-266754019

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #2295.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- drop a zip file that is no a charm on the canvas
- the drop overlay should disappear and an error should appear
- create a text file and give it a `.zip` extension
- drop it on the canvas
- the drop overlay should disappear and an error should appear

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6588/

**Comment by bac** [comment]
# QA notes

## Safari

* The drop overlay ("Drop file to add to canvas") never appears on Safari.
* Zip file that is not a charm displays error properly.
* Text file with .zip extension does not display an error.

## Chrome

* Zip file that is not a charm displays drop overlay and error properly.
* Text file with .zip extension displays drop overlay bug does not display an error. After the file is dropped, the drop overlay incorrectly stays on the canvas.

**Comment by huwshimi** [comment]
@bac I tried this and it worked with Chrome (Version 55.0.2883.87 (64-bit) on Ubuntu 16.10). Not sure what's up but we seem to be getting different results with our Chromes.

Safari does not appear to show the drop overlays so I've filed an issue: #2323.

**Comment by kadams54** [comment]
I tested in the latest Chrome for Mac (55.0.2883.95) and got the behavior @bac reported, in terms of the overlay being displayed + no error, when I dropped a non-charm zip file. Here's the stack trace:

~~~~
Uncaught RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint32 (<anonymous>)
    at combo?app/store/env/api.js&app/assets/javascripts/yui/timers/timers.js&app/assets/javascripts/yui/p…:7565
    at FileReader.reader.onload (combo?app/store/env/api.js&app/assets/javascripts/yui/timers/timers.js&app/assets/javascripts/yui/p…:7160)
~~~~

I'm going to continue testing in a variety of browsers across platforms to see if I can reproduce consistently. That said, I suspect this is an intermittent error, given that @bac saw it, I saw it under different conditions, and @huwshimi didn't see it at all.

**Comment by kadams54** [comment]
Amendment & correction on my previous note. Just realized I was indeed dropping the .txt file, not a real zip. My observed behavior matches with @bac's report.

**Comment by kadams54** [comment]
Reported in Firefox for Mac 50.1.0, when dropping a txt file:

~~~~
RangeError: argument 1 accesses an index that is out of range  combo:7565:10
	createZipReader/seekEOCDR/< http://192.168.33.10:6543/dev/combo:7565:10
	BlobReader/readUint8Array/reader.onload http://192.168.33.10:6543/dev/combo:7160:6
~~~~

**Comment by kadams54** [comment]
Saw the same errors in Firefox 50.1.0 and Chrome 55.0.2883.87 on Xenial, when dropping a txt file with a `.zip` extension.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6598/

**Comment by kadams54** [comment]
I've verified that there is no console error in Yakkity, but there is in Xenial and OS X. It must be something about how the underlying OS is sending the file to the browser. @huwshimi: would it be possible to catch the RangeError and then display the expected "invalid file" error notification?

**Comment by huwshimi** [comment]
@kadams54 It looks like these issues can be resolved by updating our zip.js asset, unfortunately however it is not just a drop-in replacement, so we'll have to take some time to the upgrade at some stage.

**Comment by kadams54** [comment]
@huwshimi: yeah, but until that happens… why not catch the RangeError and fail gracefully?

**Comment by huwshimi** [comment]
@kadams54 That could work, except that try/catch only works on synchronous code and the file upload happens async.

**Comment by kadams54** [comment]
Ah, I see. Well, the situation is at least better than it was, so I'm OK with this PR landing.

**Comment by hatched** [comment]
Until we can upgrade the zip.js asset this is a good incremental improvement. Landing

Thanks @huwshimi  et al
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
