### PR TITLE
New icons

### PR DESCRIPTION
**Pull request by huwshimi**
Updated icon set. Removed unused icons.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- look around the UI, make sure nothing is obviously broken

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2644/
Test PASSed.

**Comment by makyo** [comment]
:+1: QA okay, looks great!

**Comment by jaycee** [comment]
Code looks :+1: thanks.

**Comment by huwshimi** [comment]
Thanks @makyo and @jaycee :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
