### PR TITLE
Do not require a model name to be specified when deploying

### PR DESCRIPTION
**Pull request by hatched**
It was impossible to deploy anything without this modification to the new DF.

### CODE REVIEW

**Comment by urosj** [comment]
👍

**Comment by hatched** [comment]
:shipit: Thanks!

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5829/
Test PASSed.

**Pull request merged**
