### PR TITLE
Cancel config

### PR DESCRIPTION
**Pull request by huwshimi**
Handle cancelling the config changes.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add a service
- navigate to the config
- make some changes
- click cancel
- you should be taken back to the service overview
- navigate to the config
- your previous changes should have been reset

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3443/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3444/
Test PASSed.

**Comment by hatched** [comment]
:+1: QA :ok:

**Comment by kadams54** [comment]
LGTM as well. :+1: and :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
