### PR TITLE
Make the kubernetes display name clearer.

### PR DESCRIPTION
**Pull request by frankban**
Fixes https://github.com/juju/juju-gui/issues/2751

### CODE REVIEW

**Comment by frankban** [comment]
QA: search for kubernetes, check that "The Canonical Distribution Of Kubernetes" is the first result. Then click it and check that you land to "/canonical-kubernetes/bundle/21" and that that bundle detail page has the right title.
Check that the above has not side effects related to the ability to actually deploy that bundle, see bundle info etc.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7122/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
