### PR TITLE
Different profile header link list for non-gisf

### LINKED ISSUE #3479: New Profile: Right header links reference JAAS even in bootstrapped controller

### PR DESCRIPTION
**Pull request by hatched**
Fixes #3479

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Run the GUI and guiproxy.
View your profile in a gisf environment and in a non-gisf environment, the links should be different.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8493/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
