### PR TITLE
Service count map

### PR DESCRIPTION
**Pull request by huwshimi**
Use a map for getting the highest service name count.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add the same charm multiple times
- the first time it should be 'mysql' then 'mysql-2' then 'mysql-3' etc.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3445/
Test PASSed.

**Comment by hatched** [comment]
QA Issue:

I think this issue was pre-existing...
- Add wordpress to the canvas
- Add wordpress to the canvas
Open the inspector to wordpress-2 and you'll see that its unit list has just wordpress/0 for its units.
The same is visible in the machine view as well.

**Comment by kadams54** [comment]
:+1: on the code.

**Comment by huwshimi** [comment]
I've added a card for the existing issue. Thankyou for the reviews! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
