### PR TITLE
Do not show started units as uncommitted

### PR DESCRIPTION
**Pull request by hatched**
After a service was deployed it was showing it's started units as uncommitted.

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA
- Deploy a service: 
```
app.get('charmstore').getEntity('precise/python-django', function(entity) { app.deployService(entity[0]); });
```
- The inspector should have an 'uncommitted units' line item (this is not clickable yet).
- Close the inspector (bug fixed in #849)
- Open commit and deploy the deployer bar.
- Open the inspector for the new service
- The uncommitted units line should no longer be shown but the units list is, and shows 1 unit.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2999/
Test PASSed.

**Comment by makyo** [comment]
Code :+1: - unable to QA atm, may get to later, or ask for someone else.

**Comment by makyo** [comment]
QA okay!

**Comment by anthonydillon** [comment]
Guess started is started :+1:

**Comment by hatched** [comment]
Thanks for the reviews! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
