### PR TITLE
Display a message if there is nothing to deploy

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- visit `http://0.0.0.0:6543/deploy/:flags:/blues/`
- you should see a message about having no changes
- close the deployment flow
- add a service or machine
- open the deployment flow
- you should open the normal deployment flow

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5591/
Test PASSed.

**Comment by hatched** [comment]
I'm not really sure how it's possible to ever see this message? The 'Commit' button should be disabled if there are no changes to commit.

**Comment by anthonydillon** [comment]
Code looks good :+1:. Does the deployment panel return there after clearing or deploying?

**Comment by huwshimi** [comment]
@hatched This is for if you navigate via the urls, either by visiting an old url, clicking back in the browser etc.

**Comment by huwshimi** [comment]
@anthonydillon I think the deployment panel will close in those cases.

**Comment by anthonydillon** [comment]
Thanks, was sure there was a reason.

**Comment by hatched** [comment]
@huwshimi so in that case I would prefer that we simply redirect to the canvas. Saves us from having to implement and maintain this code (sorry). Thoughts?

**Comment by huwshimi** [comment]
@hatched OK, so do a `changeState` if there are no changes?

**Comment by hatched** [comment]
That's my thought, I'm open to objections :)

**Comment by huwshimi** [comment]
@hatched I agree, I'll do a new branch.

**Comment by huwshimi** [comment]
This has been superseded by #1922.

**Pull request closed without merging**
