### PR TITLE
Update hadoop entity in featured search section.

### PR DESCRIPTION
**Pull request by kadams54**
Fixes https://github.com/juju/juju-gui/issues/1796

### CODE REVIEW

**Comment by kadams54** [comment]
## QA

1. Update `development.ini` to use production URLs.
2. Fire everything up.
3. Click in the search input.
4. In the midpoint that appears, click on "Hadoop". Verify that you're taken to the hadoop-processing bundle.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5411/
Test PASSed.

**Comment by hatched** [comment]
Thanks @kadams54 :+1:

**Comment by jaycee** [comment]
:+1: QA OK. Thanks @kadams54 

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
