### PR TITLE
Stick with the plan.

### PR DESCRIPTION
**Pull request by frankban**
Keep the selection when activating a plan from the inspector.
This has no tests as the components has no tests, being considered a demo component for now.

### CODE REVIEW

**Comment by anthonydillon** [comment]
LGTM :+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5485/
Test PASSed.

**Comment by anthonydillon** [comment]
QA ok

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
