### PR TITLE
Do not add the same unit id when scaling up without pre-existing units.

### PR DESCRIPTION
**Pull request by frankban**
Fixes https://github.com/juju/juju-gui/issues/2425

### CODE REVIEW

**Comment by frankban** [comment]
QA: follow the instructions on the linked bug. Try to scale up with and without pre-existing units already deployed or added as ghosts. Also exercise the same scale up code as used in the inspector -> units.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6746/

**Comment by frankban** [comment]
Thanks for the reviews!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
