### PR TITLE
Only show macaroon missing message in JEM environments

### LINKED ISSUE #1206: Remove repeated macaroon warning.
When loading the gui there is a long stream of console messages "No macaroon found to get username from." This message can probably be suppressed.

### PR DESCRIPTION
**Pull request by hatched**
Fixes #1206

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Deploy into a JES enabled environment and navigate around, the console should not be full of messages warning about a macaroon.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4144/
Test PASSed.

**Comment by jaycee** [comment]
This looks fine :+1: How hard would it be to change the check so we don't even go into the `_getUsernameFromCookie` method of we aren't using a JEM?

**Comment by hatched** [comment]
@jaycee Updated to not even call `_getUsernameFromCookie` if we aren't in JEM.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4145/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4146/
Test PASSed.

**Comment by huwshimi** [comment]
Nice work @hatched :+1: (NO QA).

**Comment by jaycee** [comment]
Doing QA now.

**Comment by jaycee** [comment]
QA OK, thanks @hatched

**Comment by hatched** [comment]
Thanks for the reviews! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
