### PR TITLE
Link exposed service addresses

### LINKED ISSUE #1187: IP address in the inspector for exposed services should be link
You used to be able to click the IP addresses in the service details of an exposed service to take you to their IP:Port

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #1187

### CODE REVIEW

**Comment by huwshimi** [comment]
## QA
- Test in a real environment
- Add the Ghost service to the canvas then expose it and commit it
- Open the Expose details for the service and check that the unit ip addresses are links
- Go into the unit details in the inspector and see a list of private and public IP addresses
- Check the links open the ip:port in a different tab
- Unexpose the service and check there are no IP's available in the inspector

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4196/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4197/
Test PASSed.

**Comment by hatched** [comment]
:+1: 
QA incoming

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4198/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4199/
Test PASSed.

**Comment by hatched** [comment]
Thanks for fixing these qa issues as I bring them up :)

The newly created https/443 links do not navigate as the other ports. It just closes the inspector instead of opening a new window.

**Comment by anthonydillon** [comment]
Code and QA is good. Thanks for picking this one up @huwshimi :+1:

**Comment by hatched** [comment]
Because of ant's successful QA I spun up another env to check again and had the same issue. After a chat with @jaycee it was determined that it is working as expected because the host is the same so the YUI router is grabbing the link and routing it in the app. This was confirmed by modifying the link in the devtools and clicking on it. When the host differed from the GUI it opened up in a new tab as expected. This issue should resolve itself once we get away from the YUI router.

**Comment by hatched** [comment]
@anthonydillon @huwshimi thanks for the teamwork here!

:+1: :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
