### PR TITLE
Eslint indents

### PR DESCRIPTION
**Pull request by huwshimi**
Added eslint indentation rule. Fixed indentation.

### CODE REVIEW

**Comment by huwshimi** [comment]
No QA (lint should pass).

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3462/
Test FAILed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3463/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3464/
Test PASSed.

**Comment by hatched** [comment]
Tests passed, lint passed so Yay +1

**Comment by huwshimi** [comment]
Thanks @hatched! As discussed :shipit: to avoid conflicts.

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
