### PR TITLE
Prevent the login component to attempt logging in twice.

### LINKED ISSUE #2002: Login form always submits twice
When logging into Juju using the username and password the controller connection is called to login twice. While there is some code to prevent this from becoming a race condition there are instances where a race is possible.

https://github.com/juju/juju-gui/blob/develop/jujugui/static/gui/src/app/components/login/login.js#L114

The login form has both the `_handleLoginSubmit` method called for form submit and for the button click.

You can tell if you've resolved this issue because there won't be two console logs when logging in with the output of "logging into controller-api with user and password"

### PR DESCRIPTION
**Pull request by frankban**
This fixes #2002

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5808/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5812/
Test PASSed.

**Comment by hatched** [comment]
Thanks @frankban 

:+1: :ok: :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
