### PR TITLE
Replaced Google cloud platform svg with embeded base64 to pure svg

### PR DESCRIPTION
**Pull request by Lukewh**

### CODE REVIEW

**Comment by Lukewh** [comment]
QA: Use GCP. The Google Cloud Platform logo should not have changed in appearance.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6599/

**Comment by mitechie** [comment]
By "Use GCP" do you mean in the deployment flow? Can you be a bit more specific?

**Comment by Lukewh** [comment]
> By "Use GCP" do you mean in the deployment flow? Can you be a bit more specific?
I've updated my original comment mitechie, hope it's clearer. Let me know if more clarification is needed.

**Comment by mitechie** [comment]
QA ok but I can't tell if the image is now optimizable or still base65.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6600/

**Comment by Lukewh** [comment]
:shipit:

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
