### PR TITLE
Fix background color on expanded row bug

### PR DESCRIPTION
**Pull request by barrymcgee**

### CODE REVIEW

**Comment by barrymcgee** [comment]
## QA

- Load profile with 'profile' flag
- Roll over row item, verify background of row changes to white
- Click on row to expand it
- there should now be clear gutter between the expanded card and the edges of the row

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8431/

**Comment by hatched** [comment]
Thanks @barrymcgee :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
