### PR TITLE
Move the deploy button when the cookie notice is visible

### LINKED ISSUE #2467: deploy button should not be hidden by cookie warning
The deploy button hidden by cookie warning. I think we can/should try to at least move the x to the end by the deploy button so that you can remove it but best if we could move the deploy button above it when it's active. Anchor to XX px above the bottom of the page or above the cookie warning so it looks like the botton of the box was pushed up entirely. e.g. the canvas is stacked on the cookie warning vs under it.

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #2467.

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6836/

**Comment by huwshimi** [comment]
QA:
- clear your `_cookies_accepted` cookie
- load the gui with `GTM_enabled = true` e.g. `guiproxy -controller jimm.jujucharms.com:443 -config 'gisf: true, jujuEnvUUID:"", GTM_enabled: true'`
- check that the cookie notice is visible and that the deploy button appears above the notice
- close the notice
- the deploy button should move down

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
