### PR TITLE
Properly export ambiguous relations

### LINKED ISSUE #2791: Bundle export is broken due to wrong relations export
Add cs:~uros-jovanovic/bundle/big-bundle to canvas. Export. Result is:

relations: 
  - - "resourcemanager:undefined"
    - "namenode:undefined"
  - - "namenode:undefined"
    - "slave:undefined"
  - - "resourcemanager:undefined"
    - "slave:undefined"
  - - "plugin:undefined"
    - "namenode:undefined"
  - - "plugin:undefined"
    - "resourcemanager:undefined"
  - - "client:undefined"
    - "plugin:undefined"
...

Do not append ":undefined" to relations. 

This bug breaks bundle and can't be used or published to the store.

### PR DESCRIPTION
**Pull request by hatched**
Fixes #2791

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA
Follow the repro instructions in the bug and also try a few of your own export/imports to make sure it works as expected. Please note the issue https://github.com/juju/juju-gui/issues/2801 which was exposed by this fix.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7192/

**Comment by Lukewh** [comment]
## QA OK
and it's true, #2801 is exposed by this fix.

**Comment by hatched** [comment]
Thanks :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
