### PR TITLE
Restyle the invalid form input

### PR DESCRIPTION
**Pull request by anthonydillon**

### CODE REVIEW

**Comment by anthonydillon** [comment]
## QA
- Switch over to using JIMM
- Deploy a application
- Enter `-name-` into the model_name field
- Click off the field
- See that the error style matches the design [1]
- Enter `name` and click off and see the error has gone

[1] https://cloud.githubusercontent.com/assets/2169216/20483852/32d242c0-afec-11e6-8553-f06defac6eae.png

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6256/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6257/
Test PASSed.

**Comment by hatched** [comment]
Thanks @anthonydillon :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
