### PR TITLE
Show the cloud tag not provider name in model list in new profile.

### LINKED ISSUE #3447: New Profile: Update Cloud Type names to match CLI
eg) should show 'aws' instead of 'ec2'

### PR DESCRIPTION
**Pull request by hatched**
Fixes #3447

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

View the GUI with the new profile flag.
The model list should show 'aws', 'google' etc, instead of 'ec2, gce'...

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8477/

**Comment by hatched** [comment]
Thanks @huwshimi :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
