### PR TITLE
Make sure options.update doesn't clobber options that are set to false.

### PR DESCRIPTION
**Pull request by jaycee**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4227/
Test PASSed.

**Comment by jaycee** [comment]
There is no necessary QA--the tests demonstrate the fix is in place. However, you can monkey with the values in development.ini and make sure they still work.

**Comment by hatched** [comment]
:+1:

**Comment by bac** [comment]
:+1:

**Comment by jaycee** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
