### PR TITLE
Last user-facing clean up on text for svc2app

### PR DESCRIPTION
**Pull request by makyo**

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5239/
Test FAILed.

**Comment by makyo** [comment]
# QA

* Deploy an application and commit changes, ensure that the notification doesn't say service
* Click machine view, then back to applications and ensure that the url doesn't say service
* Delete the service and ensure that the confirmation box doesn't say service

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5241/
Test PASSed.

**Comment by hatched** [comment]
👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍

**Comment by jaycee** [comment]
:+1: :cake: :candy: :fireworks: :+1:

**Comment by huwshimi** [comment]
QA OK (says Jeff).

**Comment by hatched** [comment]
:shipit:

**Comment by makyo** [comment]
:ship: :shipit: 🍧 💯

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
