### PR TITLE
Navigate to entities

### PR DESCRIPTION
**Pull request by huwshimi**
Set full ids so that entities can be correctly navigated to.

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3254/
Test FAILed.

**Comment by huwshimi** [comment]
QA:
- view `/:flags:/react/`
- search for wordpress
- click the first result "wordpress"
- you should be taken to the wordpress charm
- go back to the search results
- scroll down to the Recommended section
- click on the first "wordpress" bundle
- you should be taken to the wordpress bundle

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3255/
Test PASSed.

**Comment by hatched** [comment]
:+1: QA :ok: 

QA Notes:
This fixes the issue where all links from the store would only use the charm id and not it's store path. All of the tested links generated the proper url and shows the correct entity.

**Comment by makyo** [comment]
:+1: :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
