### PR TITLE
Add NPM system dependency.

### PR DESCRIPTION
**Pull request by kadams54**

### CODE REVIEW

**Comment by makyo** [comment]
:+1: no qa

**Comment by bac** [comment]
:+1:

**Comment by hatched** [comment]
:-1: npm should be installed with the nodejs in the yellow ppa, can you check first that you have that ppa installed

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2771/
Test PASSed.

**Comment by kadams54** [comment]
Turns out sysdeps does need updated, just not with NPM. @hatched is going to handle that in a separate PR.

**Pull request closed without merging**
