### PR TITLE
Only display one dropdown at once

### PR DESCRIPTION
**Pull request by huwshimi**
When opening a dropdown then close all other open dropdowns.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- click on "Admin" and the user menu should open
- click on "More" and the more menu should open and the user menu should close

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2340/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2341/
Test PASSed.

**Comment by makyo** [comment]
:+1: QA okay - I clicked back and forth between the menus and noted that only one would stay open at a time.  Didn't notice any other changes.  Thanks!

**Comment by jaycee** [comment]
:+1: looks good, thanks.

**Comment by huwshimi** [comment]
Thanks for the reviews! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2343/
Test PASSed.

**Pull request merged**
