### PR TITLE
Increase hitbox on select dropdowns and align the right hand arrow

### PR DESCRIPTION
**Pull request by anthonydillon**

### CODE REVIEW

**Comment by anthonydillon** [comment]
## QA
- Run locally
- Add application
- Enter the deployment flow
- You should be able to click anywhere on the `Credential` select input to trigger the download
- The arrow should also to vertical centred
- I have also added extra (`30px`) padding on the right so the text doesnt go behind the chevron

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6279/
Test PASSed.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
