### PR TITLE
Simplify series used for filtering.

### PR DESCRIPTION
**Pull request by kadams54**
Only show LTS series for filtering. Fixes https://github.com/juju/juju-gui/issues/1245.

### CODE REVIEW

**Comment by kadams54** [comment]
## QA

1. Search for something.
2. In the search results, check the Series dropdown. It should now more closely match the similar dropdown that shows when you search at https://jujucharms.com/

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5399/
Test PASSed.

**Comment by hatched** [comment]
Thanks @kadams54 :+1: :ok: :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
