### PR TITLE
Don't update the search text while typing

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #2020.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add an app
- click deploy and then deploy
- immediately start typing in the search box
- your text shouldn't be cleared
- hit enter
- it should search correctly
- refresh the page
- the store should be open with your search query
- close the store
- the query should be cleared

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5844/
Test PASSed.

**Comment by anthonydillon** [comment]
Code looks good :+1:

**Comment by hatched** [comment]
Thanks @huwshimi This works great!

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
