### PR TITLE
Add new direct deploy layout

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3013.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load the direct deploy flow for a charm and a bundle
- check that it looks roughly like: https://user-images.githubusercontent.com/9105999/27917449-e7e0563c-6263-11e7-8de9-0d2043a73ebf.png

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7860/

**Comment by hatched** [comment]
Couple QA notes:

- When viewing a bundle the left text side is collapsed by default so the svg bounces back and forth while it's loading - It should have a defined width.
- The text area is missing the number of machines count.
- The model name is still shown in the header.
- Wen viewing a single charm it does not display the canvas icon.

**Comment by hatched** [comment]
Good step in the right direction, thanks @huwshimi

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
