### PR TITLE
Handle no results when listing clouds.

### LINKED ISSUE #2041: Gracefully handle list clouds response failures
In JIMM the cloud response could be invalid, while unlikely, it causes an exception in the GUI.

https://github.com/juju/juju-gui/blob/develop/jujugui/static/gui/src/app/store/env/controller-api.js#L748

It's possible that results is undefined 
```JavaScript
...
    const results = data.response.clouds;
    const clouds = Object.keys(results).reduce((prev, tag) => {
...
```

### PR DESCRIPTION
**Pull request by frankban**
Also fix a react error while rendering the deployment bar.

Fixes #2041

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5882/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5883/
Test PASSed.

**Comment by hatched** [comment]
Thanks for this fix @frankban 

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
