### PR TITLE
Update styling for the deployment bar so that it doesn't block the canvas

### LINKED ISSUE #3341: Can't click along the bottom of the gui
If you try and interact with the GUI near the bottom of the screen then your clicks do nothing (looks like #deployment-bar-container is covering the canvas)

### PR DESCRIPTION
**Pull request by hatched**
Fixes #3341

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

This has no visible UI changes, but when clicking to the left of the 'deploy' button, it should now drag the canvas around.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8484/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8485/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
