### PR TITLE
Check for the existence of the apiv4 charmstore instead of apiv3 store

### PR DESCRIPTION
**Pull request by hatched**

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Make sure the search widget works properly

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2384/
Test FAILed.

**Comment by hatched** [comment]
NPM spurious error

**Comment by makyo** [comment]
:+1: QA okay - everything worked as expected in search land.

**Comment by mitechie** [comment]
:+1: :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
