### PR TITLE
Correctly fetch application names in deployment flow changelog.

### LINKED ISSUE #3109: Unable to remove units on GIJoe
- Deploy a charm
- When still deploying and fully deployed:
 - Try to remove a unit

### PR DESCRIPTION
**Pull request by hatched**
Fixes #3109

Different api methods have different call signatures so if the application name isn't in the correct spot the displaying of the changelog could fail.

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Be sure you're able to add/remove a relation, unit, application as well as add/remove machines.

This can simply be done by adding the kabana elastic search bundle and then performing one action, opening the df, checking the changelog, refresh, and continue through the steps.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7939/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7942/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7943/

**Pull request merged**
