### PR TITLE
Inspector relations: do not fail when the app has peer relations.

### PR DESCRIPTION
**Pull request by frankban**
QA: on gijoe, deploy postgresql, and open its relations in the inspector.
Everything should work without JavaScript errors.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5382/
Test PASSed.

**Comment by hatched** [comment]
QA Issue:
After deploying postgresql and viewing the relations in the inspector it showed me the "Select all relations" checkbox even though there are none. 

screenshot from 2016-07-05 08 40 42

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5384/
Test PASSed.

**Comment by hatched** [comment]
Thanks for this fix @frankban 

:+1: :ok:

**Comment by frankban** [comment]
Thanks for the review and QA Jeff.
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
