### PR TITLE
In Firefox, text box for entering SSH key is misaligned

### PR DESCRIPTION
**Pull request by Lukewh**
Fixes https://github.com/juju/juju-gui/issues/2443

### CODE REVIEW

**Comment by Lukewh** [comment]
**QA**
Try to deploy to a cloud provider, the SSH Key input box should be the right height :)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6783/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
