### PR TITLE
Update model name when switching models

### LINKED ISSUE #1070: When creating new model, the name of the model is not updated
When new model is created, and switched to it, the name in the env switcher does not update.

Switching between models doesn't update the name properly as well.

### PR DESCRIPTION
**Pull request by hatched**
When switching models we now mask the canvas and show the "connecting to environment" message while we wait for the appropriate deltas. Fixes #1070

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Deploy to a real environment with JES enabled, create an env and switch between them. You should see the mask and when you get back to the new model it should have the appropriate env name.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3933/
Test PASSed.

**Comment by urosj** [comment]
QA: env switching works ok, but creating new model fails. When model is created, we switch to it, but the name is not updated.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3936/
Test PASSed.

**Comment by huwshimi** [comment]
Code :+1: no QA

**Comment by urosj** [comment]
:+1: and QA :ok:

**Comment by hatched** [comment]
Thanks for the reviews! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
