### PR TITLE
Minor fixes to release process.

### PR DESCRIPTION
**Pull request by jaycee**

### CODE REVIEW

**Comment by jaycee** [comment]
QA:

Make through the steps seem sensible--feel free to run part of them, but do not push back to the main repo.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3930/
Test FAILed.

**Comment by kadams54** [comment]
:+1: No QA. Not sure this ticket really needs QA, given the brevity of changes and that they're to docs rather than code.

**Comment by bac** [comment]
:+1:

**Comment by jaycee** [comment]
Tests are spurious. Let's hope CI let's this land.

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
