### PR TITLE
Fix the popup background

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3519.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- open your profile
- check that the canvas is not visible behind the bottom of the profile 
- click the delete icon on a model
- the popup should appear, but you should be able to see the profile underneath the profile

**Comment by huwshimi** [comment]
[Fix the popup background](https://trello.com/c/uYs7zlN6/332-fix-the-popup-background)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8522/

**Comment by mitechie** [comment]
I qa'd this and it looks ok except I don't see my profile when the delete popup comes up. I see this:

This is chrome on osx

popup

**Comment by mitechie** [comment]
QA ok, ignore me. It helps if I merge the PR in to test correctly.

**Comment by mitechie** [comment]
Except, deleting a model doesn't work now?

**Comment by mitechie** [comment]
Ok, except that the deletion is due to #3541 so this is ok and landing it. :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
