### PR TITLE
Add Xenial to list of supported series.

### PR DESCRIPTION
**Pull request by kadams54**
Fixes https://github.com/juju/juju-gui/issues/1588.

### CODE REVIEW

**Comment by kadams54** [comment]
## QA

Pull up search. Make sure Xenial is in the series dropdown.

**Comment by bac** [comment]
:+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4907/
Test PASSed.

**Comment by kadams54** [comment]
:shipit: Landing as trivial.

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
