### PR TITLE
Remove apps' relations store

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3548.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add a bundle with a few apps/relations
- click Destroy on one of the apps
- click on the inspector for one of the apps that used to relate to the app you destroyed
- open the relation list
- you should not get errors in your console
- click export in the header
- the exported relation list should not include any of the relations to the destroyed app

**Comment by huwshimi** [comment]
[Fix removed relations when exporting models](https://trello.com/c/dAd365F1/368-fix-removed-relations-when-exporting-models)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8563/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
