### PR TITLE
Import the makeEntityModel util

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- search for a bundle and view the details
- they should appear with no errors
- add the bundle to the canvas
- the bundle should be added with no errors

**Comment by huwshimi** [comment]
[Import the makeEntityModel util](https://trello.com/c/GhrYRHcI/650-import-the-makeentitymodel-util)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8689/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8690/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Comment by huwshimi** [comment]
[Add agree to terms to the expert flow](https://trello.com/c/GlvnkHfp/653-add-agree-to-terms-to-the-expert-flow)

**Pull request merged**
