### PR TITLE
API layer: rename go.js to api.js and duplicate it as legacy-api.js

### PR DESCRIPTION
**Pull request by frankban**
In preparation for future work.
This is a mechanical branch.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5269/
Test PASSed.

**Comment by jrwren** [comment]
👍

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
