### PR TITLE
Use relative paths for hero images in store

### LINKED ISSUE #2947: Store assets not found on /store
When deployed via dist with the latest Juju the hero assets are not found:
```
https://35.185.108.91:17070/static/gui/build/app/assets/images/store/openstack-promo.png
https://35.185.108.91:17070/static/gui/build/app/assets/images/store/hadoop-elephant.png 
https://35.185.108.91:17070/static/gui/build/app/assets/images/store/k8-image.png
```
It looks like the path isn't setup properly.
screen shot 2017-05-25 at 1 33 50 pm

### PR DESCRIPTION
**Pull request by hatched**
Fixes #2947

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

build dist, upgrade gui on fresh controller and view store, the hero images should appear.

Also check GUIPROXY but this issue only appears without.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7728/

**Comment by jaycee** [comment]
QA OK.

**Comment by hatched** [comment]
Thanks @jaycee :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Comment by hatched** [comment]
@huwshimi plz be aware of this change

**Pull request merged**
