### PR TITLE
Close inspector when switching model

### LINKED ISSUE #3241: local inspector not cleared when switching models
To reproduce, drag a local charm to the canvas, do not deploy, switch models.

The inspector will still be rendered in the new model.

### PR DESCRIPTION
**Pull request by hatched**
Fixes #3241

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Add a local charm to the canvas so the local charm inspector opens.
Switch models, it should close the inspector.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8180/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
