### PR TITLE
Add react lint

### PR DESCRIPTION
**Pull request by huwshimi**
Added linting for react, remove unused node-sass and jshint modules.

### CODE REVIEW

**Comment by huwshimi** [comment]
No QA, CI should pass.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3667/
Test PASSed.

**Comment by hatched** [comment]
Thanks for this! :+1: :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/1244

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
