### PR TITLE
Update styling for environment switcher

### PR DESCRIPTION
**Pull request by anthonydillon**

### CODE REVIEW

**Comment by anthonydillon** [comment]
## QA
- Load the GUI in a real environment or go to `app/extenstions/app-renderer-extenstion.js line 62` and set `showEnvSwitcher` to `true`.
- Check the environment switcher looks like the uneditable version in the design [1]
- Click on the environment name and check the switcher drop down opens correctly

[1] https://cloud.githubusercontent.com/assets/9105999/14288312/01d7e9de-fb4e-11e5-9892-3ee3f0847ac9.png

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4933/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4936/
Test PASSed.

**Comment by bac** [comment]
Looks reasonable

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
