### PR TITLE
Fix KVM environment exports.

### PR DESCRIPTION
**Pull request by hatched**
The bundle export didn't exclude KVM containers in the service placement declarations so exports with KVM would fail.

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

```
juju deploy cs:~juju-gui/trusty/juju-gui-49
juju set juju-gui juju-gui-source="https://github.com/hatched/juju-gui.git fix-kvm-export"
```

- Drag four services to the canvas
- Create two bare metal machines
- Place one unit on metal 0
- Place one unit in lxc 0
- Place one unit on metal 1
- Place one unit on kvm 1
- Commit & Export
The file should have the two machines and the `to` directives should be correctly defined.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2560/
Test PASSed.

**Comment by makyo** [comment]
:+1: QA okay!

**Comment by hatched** [comment]
Thanks! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
