### PR TITLE
Rerender the breadcrumbs when the model name changes

### LINKED ISSUE #1420: Model switcher doesn't update the active model when switching between models
Deploying the latest GUI into Juju 2.0 If you create a new model, it should automatically switch to it, when it does this the name in the breadcrumb should update. It doesn't. It also doesn't update when you switch between the models.

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #1420.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- run the gui in Juju 2.0
- open the model switcher and add a new model
- when you click New it should load the new model and update the breadcrumb with the new model name
- use the model switcher to load the first model
- the breadcrumb should update correctly
- open the user profile and switch to your new model
- the breadcrumb should update correctly

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4594/
Test PASSed.

**Comment by hatched** [comment]
:+1: :ok:
Thanks for tracking this down!

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
