### PR TITLE
Use babel to minify instead of Uglify

### PR DESCRIPTION
**Pull request by hatched**
Uglify doesn't support the ES6 spec and it was conflicting with the jujulib babel compilations. This removes uglify from the majority build process speeding it up by over 60% and providing us almost the same minification.

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

`make clean-all deps fast-babel run`

Use the gui, make sure it all works as expected.

Edit some files and save and it should auto build the files as before

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5562/
Test PASSed.

**Comment by huwshimi** [comment]
QA OK :+1:!

**Comment by hatched** [comment]
Thanks @huwshimi :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
