### PR TITLE
Adding machine method binding

### PR DESCRIPTION
**Pull request by hatched**
- When adding a machine in the machine view it now has properly bound methods.
- Lock down the version of eslint so the proper version gets installed.

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA
- Open devtools
- Add an application to a model
- Switch to the machine view and auto-place
- Click the hamburger and add-machine
- Fill in the inputs with values and then click add
- It should create a machine and not error.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7876/

**Comment by Lukewh** [comment]
## QA OK

**Comment by hatched** [comment]
Thanks @Lukewh :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
