### PR TITLE
Filter search type

### PR DESCRIPTION
**Pull request by huwshimi**
Add ability to filter searches by entity type.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- do a search
- at the top left of the search there should be a filter "All Charms Bundles" and All should be underlined
- clicking on Charms or Bundles should filter the search results by that entity type

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3516/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3518/
Test PASSed.

**Comment by hatched** [comment]
QA :ok: Too bad it has to re-render each time

**Comment by hatched** [comment]
:+1:

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3524/
Test FAILed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3525/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3526/
Test PASSed.

**Comment by fabricematrat** [comment]
:+1:  thanks.

**Comment by jaycee** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
