### PR TITLE
Restore credentials after a canceled add.

### LINKED ISSUE #2543: Cancelling adding credentials blocks deploy
On jujucharms.com, log in and add something to the canvas.
Enter the deployment flow
Using AWS
*** If you do not have a credential, add one, and refresh and start over ***
You'll have one credential selected.
Change the dropdown to add a credential
Now that you are at the add credential form, hit cancel
The deployment flow will no longer show you the changesets and deploy will be disabled

Going back to the canvas and starting the DF again, lets you start over.

### PR DESCRIPTION
**Pull request by kadams54**
Fixes #2543.

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6873/

**Comment by kadams54** [comment]
## QA

1. `make clean-gui fast-babel gui run`
2. `$GOPATH/bin/guiproxy -controller jimm.jujucharms.com:443 -config 'gisf: true, jujuEnvUUID:""'`
3. Add an application to the model.
4. Deploy.
5. In the credentials dropdown, select "Add credential".
6. Cancel.
7. You should see the machines and deployments still listed.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6874/

**Comment by jaycee** [comment]
QA OK.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
