### PR TITLE
Show subordinate units in subordinate inspector

### LINKED ISSUE #2309: Subordinate unit details show principal unit details
**How to reproduce**

1. Deploy a subordinate Charm and connect it to a principle charm (for example spark->zeppelin in the [apache hadoop zeppelin bundle](https://jujucharms.com/apache-hadoop-spark-zeppelin/)).
2. Click on the subordinate charm and choose 'units'

**What I expect:** The GUI shows the units of the subordinate Charm.

**What happens:** The GUI shows the units of the principle Charm.

**Why this is bad:**

1. You cannot see the status message of the subordinate Charms in the GUI.
2. You cannot see the opened ports of the subordinate Charms in the GUI. Subordinates like the `zeppelin` charm in the [apache hadoop zeppelin bundle](https://jujucharms.com/apache-hadoop-spark-zeppelin/) deploy a GUI accessible with the browser. The IP/Port combination of this GUI isn't visible in the GUI. You can only see it in the commandline.

### LINKED ISSUE #2329: Charm left in initial position doesn't have gui annotations
The GUI location annotations for a charm left in its initial position are not saved in the resulting bundle when exported.

*Note that "no gui annotations" is a warning for `charm proof` which means that `bundletester` will fail.*

1. Go to demo.jujucharms.com
2. Add the wordpress charm and **make sure to not move the charm from its initial position**
3. commit the changes and click "export bundle".

now: 

```yaml
applications: 
  wordpress: 
    charm: "cs:trusty/wordpress-4"
    num_units: 1
    to: 
      - "0"
```

want: 

```yaml
applications: 
  limeds: 
    charm: "cs:trusty/wordpress-4"
    num_units: 1
    annotations: 
      "gui-x": 0
      "gui-y": 0
    to: 
      - "0"
```

### PR DESCRIPTION
**Pull request by hatched**
Fixes #2309 
Fixes #2329 

The subordinate inspector used to show only the principal units in the unit list. It now shows only the subordinate units.

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7005/

**Comment by hatched** [comment]
Thanks

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7015/

**Pull request merged**
