### PR TITLE
Update eslint to v4

### PR DESCRIPTION
**Pull request by hatched**
- In eslint v4 they rewrote the `indent` rule to make it more strict and we had a _lot_ of improperly indented code.
- Indent changes were fixed with `--fix`
- `--cache` was removed from eslint command as it kept getting out of sync. It can probably be re-enabled in the future.
- I wasn't able to update eslint-react-plugin because of a bug when assigning props to another variable: `https://github.com/yannickcr/eslint-plugin-react/issues/1257`

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7803/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7804/

**Comment by hatched** [comment]
Thanks @makyo 

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
