### PR TITLE
Fix svg sprites

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #2807.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load the gui
- check the the svg sprites don't have strange grey borders

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7211/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7212/

**Comment by Lukewh** [comment]
## QA-OK

Thanks @huwshimi

**Comment by Lukewh** [comment]
:shipit: thanks huw

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
