### PR TITLE
Initial commit.

### PR DESCRIPTION
**Pull request by jaycee**
* Move the app files to the pyramid static path. 
* Add pyramid files. 
* Add new Makefile and docs. 
* Attempt pruning no longer needed files.

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2660/
Test FAILed.

**Comment by jaycee** [comment]
QA:

Run `make clean-all run`; everything should work.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2662/
Test FAILed.

**Comment by jaycee** [comment]
As a note, the CI is expected to fail; we need to set up new CI/merge jobs for things proposed against `juju:pyramid-fork`.

**Comment by hatched** [comment]
There were a few issues when deploying and executing:

1. It doesn't look like pip and virtualenv are installed in the sysdeps
2. When deploying a charm the route for `/juju-ui/assets/svgs/service_module_pending.svg` is 404ing. This shows as a broken image when you try and deploy a charm.
3. It doesn't appear that you can access anything under the `juju-ui/` path directly in the address bar.

I'm going to merge this in and then these fixes can be done as follow-ups

**Pull request merged**
