### PR TITLE
Make root state parsing less restrictive.

### LINKED ISSUE #3654: 'new' portion of url included in entity id
When logged in visiting https://jujucharms.com/apache2 "forwards" to https://jujucharms.com/new/apache2. This appears to be an invalid URL and going to there directly does not show the apache2 charm information, but "forwards" to https://jujucharms.com/new.

### PR DESCRIPTION
**Pull request by hatched**
Fixes #3654

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Visit the urls in the bug.
Navigate around the GUI and everything should work as expected

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8674/

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
