### PR TITLE
Move where query params are added with state generated urls.

### LINKED ISSUE #3088: visiting search queries directly creates invalid url
in JAAS when you visit `<host>/q/?requires=http` you get redirected to `<host>/q/?requires=http/u/hatch` because of an invalid state update.

### PR DESCRIPTION
**Pull request by hatched**
Fixes #3088

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Try and reproduce the linked issue. It should now display the search results and url correctly.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8165/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
