### PR TITLE
Remove less

### PR DESCRIPTION
**Pull request by huwshimi**
Remove the less files and builder.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- run `make clean-all`
- run `make sysdeps`
- run `make devel`
- check that there are no errors and that the gui loads the CSS fine (from the new SCSS files)

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2597/
Test PASSed.

**Comment by jaycee** [comment]
Looks good, @huwshimi :+1: 

QA to follow.

**Comment by jaycee** [comment]
QA notes:

I ran `make clean-all sysdeps devel`; the build process completed successfully and I got a running instance of the gui with no errors.

I clicked around in the gui (details from charm search, inspector, machine view, added services) and saw no css errors.

QA OK.

**Comment by makyo** [comment]
:+1: Looks great, thanks!

**Comment by huwshimi** [comment]
Thanks @makyo and @jaycee! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2600/
Test PASSed.

**Pull request merged**
