### PR TITLE
Use Elements card form

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- open your account page
- remove your payment method
- add a new one, noting the new fancy card number etc. form

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7218/

**Comment by fabricematrat** [comment]
QA:

I think it would be good to have the green button called Add instead of Add payment method.
The card holder name works but when you reveal the card it inverted and collides with the last 4 digit.

Probably need a better fancy form where we have the full address as it is not obvious it is a postal code. (don't know if they is one and not my decision also :))

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7225/

**Comment by huwshimi** [comment]
Thanks @fabricematrat @hatched :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
