### PR TITLE
Remove the country code field

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- open your account page (if you don't have a user create one via the deployment flow)
- in your addresses list there should be no country code field next to the phone number fields

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7207/

**Comment by fabricematrat** [comment]
@frankban no need to show a country code in the UI when you show the country name already.

LGTM

**Comment by huwshimi** [comment]
Thanks @fabricematrat and @frankban :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
