### PR TITLE
Remove bundle confirm step

### PR DESCRIPTION
**Pull request by hatched**
Now that bundles no longer auto-deploy we don't need to confirm that they want to add it to their canvas.

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA
```
juju deploy cs:~juju-gui/trusty/juju-gui-49
juju set juju-gui juju-gui-source="https://github.com/hatched/juju-gui.git remove-bundle-confirm"
```

- Search for a bundle
- Click to view the bundle details
- Click deploy
- It should close the details pane and then add the bundle to the change set

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2553/
Test PASSed.

**Comment by makyo** [comment]
:+1:, QAing

**Comment by makyo** [comment]
QA okay

**Comment by hatched** [comment]
Thanks! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
