### PR TITLE
Fix inconsistencies in the status pane.

### LINKED ISSUE #3158: Status pane shows empty relation entries
screen shot 2017-08-23 at 1 38 53 pm

To reproduce, add the k8s core bundle to the canvas and before committing open the status pane and scroll to the relations.

### LINKED ISSUE #3161: Subordinate without machine breaks layout in status
screen shot 2017-08-23 at 1 50 10 pm

To reproduce this, deploy the k8s-core bundle and wait with status open.

### LINKED ISSUE #3162: Status shows application as pending when it isn't
screen shot 2017-08-23 at 2 34 10 pm

screen shot 2017-08-23 at 2 34 48 pm

To reproduce, add an application to the canvas, remove the pending unit, then deploy.

### PR DESCRIPTION
**Pull request by frankban**
Specifically:
- when an app is waiting, it does not mean that it's pending (fixes #3162);
- exclude uncommitted entities from the status pane (there is no meaning in asking the status of something that does not really exist, fixes #3158);
- do not ignore that subordinate units exist, yes, yes they do (fixes #3161).

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8019/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8020/

**Comment by fabricematrat** [comment]
Code :ok:

**Comment by frankban** [comment]
Thank you all!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
