### PR TITLE
Update changelog headers

### PR DESCRIPTION
**Pull request by huwshimi**
Remove the new units header as it only makes sense when all the apps in the changelog are adding new units. Fixes: #3335.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- make some changes to a new or existing model
- open the deployment flow
- check that the model changes does not have a "new units" heading

**Comment by huwshimi** [comment]
[Update changelog headers](https://trello.com/c/J13By6vd/78-update-changelog-headers)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8305/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
