### PR TITLE
Grey healthy relationship lines

### PR DESCRIPTION
**Pull request by anthonydillon**

### CODE REVIEW

**Comment by anthonydillon** [comment]
## QA
- Add two services to the canvas and make a relation
- Commit the changes and you should the healthy relation line is no longer green but grey
- The relation icon is also grey

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3714/
Test PASSed.

**Comment by hatched** [comment]
:+1: QA :ok: :shipit: 

Thanks!

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
