### PR TITLE
Upgrade phantomjs to stop pure virtual method crashes.

### PR DESCRIPTION
**Pull request by huwshimi**
The latest phantomjs has an updated QT lib which apparently has fixed the pure virtual method crashes.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- try running `make test-mocha-karma` a number of times, there should be no crashes

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4364/
Test FAILed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4370/
Test FAILed.

**Comment by huwshimi** [comment]
This will be landed as part of https://github.com/juju/juju-gui/pull/1334

**Pull request closed without merging**
