### PR TITLE
Fix model exports

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3261.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- start a new model
- add an app
- click the export button in the header
- the yaml file should download

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8170/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8171/

**Comment by huwshimi** [comment]
Thanks @hatched :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
