### PR TITLE
Set the model names correctly

### LINKED ISSUE #1584: When using 'Create New' from profile, breadcrumb isn't updated
When you click 'Create New' the breadcrumb isn't being updated even though the environment name is being set in the db from the profile view. This is because the `jujuEnvUUID` takes precedent when rendering the breadcrumb. Why is this the case? I don't believe we ever want to show the UUID there.

https://github.com/juju/juju-gui/blob/develop/jujugui/static/gui/src/app/extensions/app-renderer-extension.js#L70

### PR DESCRIPTION
**Pull request by huwshimi**
This updates the model name setting code to do it in one place. It also removes the localStorage override as it was no longer working correctly. Fixes #1584.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- deploy the GUI to a real model using Juju 1.25
- set up jem etc.
- load the GUI
- check that the model name is set in the breadcrumb
- open the profile
- click Create new
- the model name should now be "untitled_model"
- open the profile again
- click Manage on an existing model
- the model name should now appear in the breadcrumb

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4917/
Test PASSed.

**Comment by makyo** [comment]
:+1:

**Comment by huwshimi** [comment]
Thanks @makyo and @hatched :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
