### PR TITLE
New profile model list improvements

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load the profile using the `profile` flag
- check that the model list looks somewhat like https://user-images.githubusercontent.com/9105999/33267150-5229b222-d370-11e7-94c6-243c3936143e.png (more changes to come)

**Comment by huwshimi** [comment]
[Update new profile model list](https://trello.com/c/scnlh0dY/97-update-new-profile-model-list)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8329/

**Comment by spencerbygraves** [comment]
Hi @huwshimi The order of columns in the model list has been updated, you can see the latest in the issue - https://github.com/CanonicalLtd/juju-design/issues/342#issuecomment-347170768

Thanks

**Comment by cassiocassio** [comment]
@huwshimi I see something but it's very quick! Am I doing something wrong?

um-ah

**Comment by huwshimi** [comment]
Thanks @spencerbygraves and @cassiocassio the profile currently has a separate table for shared models. I'll merge the two in the future.

**Comment by huwshimi** [comment]
@frankban anything else that might give a clue as to why you're getting that? I wasn't able to reproduce and from what I can see that shouldn't be able to happen, but obviously it can!

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8330/

**Comment by frankban** [comment]
More info: it still happens, I am using firefox quantum.
_generateMyModels
http://192.168.64.6:8042/dev/combo:22813:1
render
http://192.168.64.6:8042/dev/combo:22934:7
finishClassComponent
http://192.168.64.6:8042/dev/combo:85327:22
updateClassComponent

**Comment by frankban** [comment]
It also happens with chrome.
I am running guiproxy as `guiproxy -env prod -flags profile`

**Comment by huwshimi** [comment]
Thanks @frankban, would you be able to try running it again with my updates?

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8333/

**Comment by frankban** [comment]
Now it works better, I can see the page. It does not have the last connected info available it seems, it does not have any indication of the current model, and on hover the link is not blue. Also, it does not work when visiting other's profiles, but maybe these are all expected limitations. Thanks!

**Comment by huwshimi** [comment]
Thanks @frankban those are all fine, this is just a preliminary branch to get the table component added. :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
