### PR TITLE
Add url hash support to state.js

### PR DESCRIPTION
**Pull request by hatched**
In order to support anchor tag linking the state system first needed to support having the hash parsed and generated from state.

As a drive-by I changed the karma reporter so that skipped tests are no longer printed so that it makes debugging easier

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

There is nothing yet implemented that uses hashes, so just make sure the GUI still navigates around properly.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7124/

**Comment by hatched** [comment]
Thanks @huwshimi - that is to be expected as there is nothing currently hooked into the hash state yet.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
