### PR TITLE
Remove the border above the machines view section

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #2670.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- start a new model
- add an app
- open the machine view
- scroll down to the "Machines to be deployed" section, it should not have a dark border at the top and should be spaced appropriately from the section above it
- deploy the model (or connect to an existing model)
- add an app
- open the machine view
- the "Machines to be deployed" should now be at the top and not have a dark border at the top

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7117/

**Comment by Lukewh** [comment]
## QA OK

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
