### PR TITLE
Align the empty profile correctly

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #2849.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- open your profile when you have no models/charms etc.
- check that the spacing looks like #2849.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7307/

**Comment by Lukewh** [comment]
Thanks @huwshimi :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
