### PR TITLE
Replace the in-page nav link

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #2978.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- open a charm
- scroll to the readme
- hover a heading
- you should see an anchor icon (you might need to clean/update your svg sprites)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7768/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7769/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
