### PR TITLE
Expand add-ssh-key message in deployment flow.

### LINKED ISSUE #2562: SSH key upload description lacks specificity
screen shot 2017-03-03 at 8 45 56

The instructions state you should upload your public key and give an example like "e.g. ~/.ssh/id_rsa.pub"

Unless it is too cluttered, it may be nice to mention that SSH keys can be added later from the command line using `juju add-ssh-key` or `juju import-ssh-key`.

### PR DESCRIPTION
**Pull request by hatched**
Fixes #2562

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7006/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7007/

**Comment by hatched** [comment]
Thanks!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge/2212

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
