### PR TITLE
Allow 'disconnected' to be defined as a jujuEnvUUID

### PR DESCRIPTION
**Pull request by hatched**

### CODE REVIEW

**Comment by jaycee** [comment]
QA: This works alongside a bb branch I'm working on, I'll QA it against that build.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6025/
Test FAILed.

**Comment by hatched** [comment]
Thanks @jaycee :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6027/
Test PASSed.

**Pull request merged**
