### PR TITLE
Display statuses for units in the machine view

### LINKED ISSUE #1296: Unit icons in MV should have more status borders
When a unit has a status which makes the service icon change colour such as 'error' or 'pending' it should also be indicated in the machine view. We already show a blue outline to indicate uncommitted. This would be helpful especially when a unit is in error. One of these wordpress units is in error...

screenshot from 2016-01-27 20 42 07

### PR DESCRIPTION
**Pull request by huwshimi**
Add borders to the units in the machine view to represent their status. Fixes #1296.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add a couple of services and scale up by a few units
- deploy
- start the simulator
- open the machine view
- wait for the simulator to start changing the statuses
- the units should get orange or red borders depending on their status

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4309/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4310/
Test PASSed.

**Comment by anthonydillon** [comment]
@huwshimi I have followed the QA instructions but could not see any borders. Sorry if im missing something?
juju admin

**Comment by hatched** [comment]
:+1: :ok: WFM Thanks for this update, looks great!

**Comment by huwshimi** [comment]
@anthonydillon that's really strange, might it be worth a clean or something? Not sure why you wouldn't see it...

**Comment by anthonydillon** [comment]
QA :+1: with a fresh rebuild. Odd it didn't work before. I believe there is a plan to convert the circles in the machine view back into squirle's?

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
