### PR TITLE
Fix building of static JavaScript assets.

### PR DESCRIPTION
**Pull request by frankban**

### CODE REVIEW

**Comment by urosj** [comment]
shipit

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5155/
Test PASSed.

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
