### PR TITLE
Updates to the deployment flow to match the latest designs

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add a serivce
- click Deploy
- check that everything looks OK on the choose could screen (notice the new summary of deployment details)
- click through to the summary and check that everything looks OK there too

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4777/
Test PASSed.

**Comment by hatched** [comment]
:+1: Thanks for these updates!

**Comment by kadams54** [comment]
:+1: for me as well. Thanks @huwshimi!

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
