### PR TITLE
Account add credentials

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- visit /account
- click the Add button next to the credentials heading
- choose a cloud
- enter some credentials details
- click add
- the credentials should appear in the list

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6954/

**Comment by huwshimi** [comment]
@frankban thanks for spotting those, they should both be fixed now.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6961/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6978/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6995/

**Comment by huwshimi** [comment]
Thanks @hatched, @frankban :shipit:

**Pull request merged**
