### PR TITLE
Set socket_protocol to ws if insecure is set.

### PR DESCRIPTION
**Pull request by bac**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4355/
Test PASSed.

**Comment by bac** [comment]
QA:

Grab the charm branch at https://github.com/bac/juju-gui-charm/tree/insecure-only and inside it, 

```
JUJU_GUI_BRANCH=<path/to/2.0.2-insecure-branch> make packages
juju bootstrap && make deploy
```

- Ensure you can access the GUI over HTTPS. Look at `/config.js` and see that socket_protocol = wss.
- `juju set juju-gui secure=false`. Wait a bit for config-changed to finish.
- Ensure you can access the GUI over HTTP. Look at `/config.js` and see that socket_protocol = ws.

**Comment by frankban** [comment]
:+1:

**Comment by jaycee** [comment]
Code is :+1: -- I'll QA tomorrow morning, since it would appear git is blocked by current internet.

**Comment by jaycee** [comment]
QA notes:

Using your charm branch and this branch, I can set secure=false and access the gui on http. However looking at config.js socket_protocol is still wss.

**Comment by jaycee** [comment]
As a note, can we bump the patch version or something on this since it's a change to master and so should be a release?

**Comment by bac** [comment]
Yes, the version will be bumped before merging.

**Comment by bac** [comment]
@jaycee That's odd as it isn't what I saw.  Do you still have your environment up?

**Comment by makyo** [comment]
:+1: QA OK

**Pull request merged**
