### PR TITLE
Lint sass files

### PR DESCRIPTION
**Pull request by anthonydillon**
Convert scss files to 2 spaces and lint the files using scss-lint

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5962/
Test PASSed.

**Comment by anthonydillon** [comment]
Sorry this is a big one but mostly just very small tweaks. I have split the changes into logical commits so you may find it easier to step through them when reviewing the changes.

## QA
- Install `scss-lint` if you dont have it already (https://github.com/brigade/scss-lint#installation)
- Run `scss-lint jujugui/static/gui/src/app/assets/**/*.scss` from the root of the project
- You should only see lint errors/warnings from the plugins folder which is external

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5964/
Test FAILed.

**Comment by huwshimi** [comment]
I think we'll also need to add a make target to run the scss linter so that it gets checked by ci, could be a followup branch as this is already rather large.

**Comment by anthonydillon** [comment]
Yea that is what I thought @huwshimi. This branch is just to get the code base ready for CI linting.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5966/
Test PASSed.

**Comment by hatched** [comment]
Hey @anthonydillon when you get a moment could you resolve these conflicts so that we can get this landed. Thanks!

**Comment by anthonydillon** [comment]
It says there are no conflicts? Am I missing something?

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6000/
Test FAILed.

**Comment by anthonydillon** [comment]
These tests are failing on develop branch too.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6004/
Test PASSed.

**Comment by hatched** [comment]
:shipit: 

Thanks @anthonydillon could you do a follow-up adding the node sass lint to the deps please.

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/1957

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
