### PR TITLE
Fix inspector input heights in Firefox

### PR DESCRIPTION
**Pull request by Lukewh**
Fixes https://github.com/juju/juju-gui/issues/2378

### CODE REVIEW

**Comment by Lukewh** [comment]
**QA**
Firefox only.

- Add charm to canvas
- Open configuration in inspector
- Inputs should all be a uniform height (whether they have single line of content or are empty)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6704/

**Comment by frankban** [comment]
Code looks good. QA ok on chrome and firefox. Thank you!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
