### PR TITLE
Import changes utils

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add an app
- open the deployment flow
- toggle open the model changes panel
- the changes should be listed

**Comment by huwshimi** [comment]
[Import changes utils](https://trello.com/c/OQN6wYii/644-import-changes-utils)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8687/

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
