### PR TITLE
Expert flow cleanups

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3616.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- in the "YOU WILL NEED:" section there should be space between the instance count and the text e.g. "1 machine-instances"
- in the "Estimated costs" section there should be space between the machine count and the text e.g. "based on 1 machine"
- in the "Set your maximum monthly budget" section there should no longer be a message about emailing based on usage

**Comment by huwshimi** [comment]
[Expert flow cleanups](https://trello.com/c/DHYIq61j/709-expert-flow-cleanups)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8749/

**Comment by frankban** [comment]
What guiproxy options are required to QA this?

**Comment by hatched** [comment]
Thanks @huwshimi 

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
