### PR TITLE
Completely hide the onboarding when a service is added to the canvas

### PR DESCRIPTION
**Pull request by hatched**
This was causing the canvas interactions to be interrupted as the element was hidden but still there.

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

- Deploy wordpress
- Deploy apache
- Create a relationship from apache to wordpress
- If the little "create relation" button doesn't hide when you try to mouse to it then it's fixed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3822/
Test PASSed.

**Comment by kadams54** [comment]
QA is OK, :+1: on the code.

**Comment by hatched** [comment]
Thanks! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
