### PR TITLE
Fade a unrelatable service instead of hiding it

### PR DESCRIPTION
**Pull request by anthonydillon**

### CODE REVIEW

**Comment by anthonydillon** [comment]
## QA
- Add two services that cannot relate
- Try to create a relation on the canvas
- The other service should fade out but not hide completely

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5551/
Test PASSed.

**Comment by hatched** [comment]
Thanks @anthonydillon this looks much better! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
