### PR TITLE
Remove event tracker

### PR DESCRIPTION
**Pull request by huwshimi**
The event tracker is no longer used now that we've replace the areas that used it.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA: None, code wasn't being used.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7325/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
