### PR TITLE
Add framework for the new deployment flow

### PR DESCRIPTION
**Pull request by huwshimi**
Add the framework to allow building out of the new deployment flow without affecting the existing flows.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- use the flag "df"
- add a machine or app
- click deploy
- you should get the new blank deploy flow

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5417/
Test PASSed.

**Comment by hatched** [comment]
Thanks @huwshimi :+1: :ok:

**Comment by huwshimi** [comment]
Thanks @hatched :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
