### PR TITLE
Update shadows

### LINKED ISSUE #1553: Remove the shadow from the bottom of the visualisation
There is a shadow at the bottom of the visualisation as seen in this image:

image

It should be a #cdcdcd 1px line.

### LINKED ISSUE #1554: Missing dropshadow's in input fields in the inspector
As seen in the image below, there are no drop shadows:

image

We should be using the same as:

image

### PR DESCRIPTION
**Pull request by huwshimi**
Update the input shadows. Fixes #1554.
Remove the shadow from the bundle visualisation. Fixes #1553.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- view a bundle details
- check that underneath the bundle visualisation there is a solid border instead of a shadow
- add a service
- open the config in the inspector
- check that the input fields have shadows

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5066/
Test PASSed.

**Comment by hatched** [comment]
@anthonydillon Can you plz take a look at this, maybe this is something that should be in the theme?

**Comment by anthonydillon** [comment]
Yea I agree the default input styling should be updated in the cloud Vanilla theme so all sites use them. For now this could land with a follow up card to migrate the input styling.

**Comment by anthonydillon** [comment]
Code looks good :+1: no QA.

**Comment by hatched** [comment]
Thanks, :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
