### PR TITLE
Uncommitted service state

### PR DESCRIPTION
**Pull request by huwshimi**
Fix the uncommitted count on a committed service. Show the service token as uncommitted when there are uncommitted units on a committed service.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA: see the attached bugs.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3867/
Test FAILed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3868/
Test FAILed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3869/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3872/
Test PASSed.

**Comment by kadams54** [comment]
QA is :ok:, code is :+1:. Thanks!

**Comment by anthonydillon** [comment]
Code and QA :+1:

**Comment by huwshimi** [comment]
Thanks for the reviews @anthonydillon and @kadams54! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
