### PR TITLE
Toggle constraints

### PR DESCRIPTION
**Pull request by huwshimi**
Add toggling of constraints in the machine view.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- use the flag `/:flags:/mv/`
- add a few machines
- using the context menu at the top of the machines column click "Hide constraints"
- the constraints on the machines (except the selected machine) should be hidden.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3906/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3907/
Test PASSed.

**Comment by hatched** [comment]
:+1: QA :ok: 
With the trivial react warning solved.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3908/
Test PASSed.

**Comment by huwshimi** [comment]
Thanks @hatched :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
