### PR TITLE
Saner lint and test targets.

### PR DESCRIPTION
**Pull request by jaycee**

### CODE REVIEW

**Comment by jaycee** [comment]
QA:

* Run `make lint` -- both python and js lint should run.
* Run `make test` -- both python and js tests (js and js-old) should run.
* Run `make check` -- everything should run as it has in the past.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4887/
Test PASSed.

**Comment by hatched** [comment]
:+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4888/
Test PASSed.

**Comment by hatched** [comment]
QA OK Thanks!
:shipit: Shipping as trivial

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
