### PR TITLE
Fix unit details prop error

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3721.

### CODE REVIEW

**Comment by huwshimi** [comment]
[Fix unit details prop error](https://trello.com/c/fPKhAXj2/808-fix-unit-details-prop-error)

**Comment by huwshimi** [comment]
QA:
- load the gui with only the `terminal` flag turned on
- add an app
- navigate to the unit details in the inspector
- there should be no console errors about a missing `showSSHButtons` prop

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
