### PR TITLE
Handle channel namespaced charms gracefully

### LINKED ISSUE #1294: Searching for the juju-gui charm has an id error.
If you do a search for "juju-gui" the results do not load and there is a browser console error "Uncaught Developers must initialize charms with a well-formed id."

### PR DESCRIPTION
**Pull request by hatched**
Allow channel namespaced charms to appear in search results. Fixes #1294.

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

- do a search for "juju-gui"
- the results should load
- click on the first juju-gui charm (it should be the first result)
- you should be taken to that charm
- visit `/services/?store=development%2Ftrusty%2Fjuju-gui`
- instead of a deploy button you should see a message

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4294/
Test FAILed.

**Comment by hatched** [comment]
Passed when run manually: http://ci.jujugui.org:8080/job/juju-gui/4295/

**Comment by kadams54** [comment]
Code is :+1: doing QA now.

**Comment by kadams54** [comment]
QA is :ok: - thanks!

**Comment by hatched** [comment]
QA Not ok - the parsing of the urls is broken, it doesn't populate the series key properly any longer.

**Pull request closed without merging**
