### PR TITLE
Check list item

### PR DESCRIPTION
**Pull request by huwshimi**
Update the unit list item to be a reusable component.

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5237/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5238/
Test PASSed.

**Comment by anthonydillon** [comment]
Code and QA :+1:

**Comment by huwshimi** [comment]
:shipit:?

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
