### PR TITLE
Move image assets out of scss files and into markup.

### LINKED ISSUE #2961: Move store css image assets out of css and into markup
Because of the different asset paths across the various platforms the GUI runs in we need to rely on the static paths defined in the config. Because this isn't set dynamically in CSS the image assets are broken in one or the other platforms.

In an effort to fix this: https://github.com/juju/juju-gui/pull/2949 resolved the assets for GUI in Juju but did not fix it for JAAS where the paths are `/static_gui/static/gui/build/app/assets/images/store/k8-image.png` not `static/gui/build/app/assets/images/store/k8-image.png`

### PR DESCRIPTION
**Pull request by hatched**
Fixes #2961

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Run the GUI and view the /store in:
- BB
- GUIProxy
- GiJoe
The three hero images should be visible and loaded via an `img` tag and be properly centred. The containers banner image and the dotted lands should also be visible in all three platforms.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7747/

**Comment by huwshimi** [comment]
The images all load, but now we have the centring problem that we had before at different screen sizes
alignment

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7749/

**Comment by huwshimi** [comment]
Now it looks like this:
centring

**Comment by hatched** [comment]
screen shot 2017-05-30 at 7 01 46 pm

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7750/

**Comment by huwshimi** [comment]
Reluctantly OK with shipping this :)

**Comment by huwshimi** [comment]
@hatched maybe could you file an issue to come back and fix this up?

**Comment by hatched** [comment]
Full width:
screen shot 2017-05-30 at 8 06 22 pm

Tablet width:
screen shot 2017-05-30 at 7 01 46 pm

**Comment by hatched** [comment]
:shipit:

**Comment by hatched** [comment]
thanks @huwshimi :)

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
