### PR TITLE
Remove the crosshatched background of the canvas

### PR DESCRIPTION
**Pull request by anthonydillon**
Replaced with the new #f5f5f5 flat background color.

### CODE REVIEW

**Comment by jujugui** [comment]
please test this

**Comment by hatched** [comment]
I feel like this branch should be done against `pyramid-fork` because it's not really a required fix for the develop branch. It will also save us rebasing pyramid-fork. 

Also, I don't see any of the assets being removed.

**Comment by makyo** [comment]
The QA is okay once the app gets up and running, but I agree with @hatched that this should be done against the pyramid fork because the modifications to `app/index.html` won't make it over to `jujugui/templates/index.html.mako` automatically, leading to the crosshatch showing up on load.

**Comment by anthonydillon** [comment]
Thank you both. Should I close this PR and only work on the `pyramid-fork` branch? Good catch @hatched I'll remove the asset.

**Comment by makyo** [comment]
@anthonydillon Yes, I think that'd be easiest.

**Pull request closed without merging**
