### PR TITLE
Enable the add key button when the launchpad option is selected

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3331.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- visit /new
- add an app
- open the deployment flow
- in the public keys section select Launchpad as the Source
- the username field should be prefilled and the "Add Keys" button should be enabled
- remove the username text
- the button should become disabled

**Comment by huwshimi** [comment]
[Fix enabling ssh key button](https://trello.com/c/qW9xIdqN/79-fix-enabling-ssh-key-button)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8306/

**Comment by huwshimi** [comment]
@hatched it used to be that when you selected Launchpad in the list the name would get prefilled but the "Add Keys" button would be disabled until you modified the username text. Once I fixed it I also discovered that when you removed the username entirely the button wouldn't become disabled again.

**Comment by hatched** [comment]
Ahh great, thanks @huwshimi 
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
