### PR TITLE
Add container

### PR DESCRIPTION
**Pull request by huwshimi**
Add the UI for adding containers in the machine view.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- use `/:flags:/mv/`
- add a machine
- using the context menu on the container column click Add container
- choose a container type
- click Create
- a container should be added

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3831/
Test PASSed.

**Comment by hatched** [comment]
:+1: QA :ok: :shipit: 
Thanks!

We will have to add lxd support in the future but it looks like that'll be an easy add on.

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
