### PR TITLE
Remove small browser notification

### LINKED ISSUE #2158: Remove "Browser is too small warning"

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #2158.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load the gui
- shrink the browser down to a small size
- the small browser notification should not appear

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6109/
Test PASSed.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
