### PR TITLE
Create legacy handler module.

### PR DESCRIPTION
**Pull request by frankban**
This is a mechanical branch that just duplicates the code in handlers.js (and corresponding tests) to new files what will be used for legacy mega-watcher handlers.

### CODE REVIEW

**Comment by jaycee** [comment]
:+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5305/
Test PASSed.

**Comment by frankban** [comment]
Hey JC, thank you for the review.
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
