### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by hatched**
We were getting behind on a number of our dependencies. This brings us up to date on all.

Migration guides of interest:
- SinonJS migration guide: http://sinonjs.org/releases/v3.1.0/migrating-to-3.0/
- Chai migration guide: https://github.com/chaijs/chai/releases/tag/4.0.0

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Use the GUI, it should work as expected

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7959/

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
