### PR TITLE
User facing s/service/application/g.

### PR DESCRIPTION
**Pull request by frankban**
To QA, please run the GUI in sandbox mode and against a real env (e.g. GIJoe), and check that "service" is never encountered while using the app. Also check that the GUI still works well of course, while dpeloying applications, removing applications, using the machine view, etc.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5220/
Test PASSed.

**Comment by kadams54** [comment]
Looks good in both GIJoe/AWS and sandbox mode. I did not QA GISF - should that also be covered?

**Comment by kadams54** [comment]
:+1: on the code. Thanks @frankban!

**Comment by anthonydillon** [comment]
Code looks good :+1:

**Comment by frankban** [comment]
Thanks for the reviews!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
