### PR TITLE
Source plans when switching application and updating inspector actions

### PR DESCRIPTION
**Pull request by anthonydillon**

### CODE REVIEW

**Comment by anthonydillon** [comment]
## QA
- Login to charmstore
- Add a charm with no plans and check no plans are visible in the inspector
- Add a charm with plans and check Plans appear in the inspector
- Now click on the service block from one to another and check the Plan action in the inspector shows when it should

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5488/
Test PASSed.

**Comment by frankban** [comment]
QA ok thank you Ant!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
