### PR TITLE
Enables the gui to load without connecting to the controller

### PR DESCRIPTION
**Pull request by jaycee**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6223/
Test PASSed.

**Comment by jaycee** [comment]
QA:

Make the following change to development.ini:

```
diff --git a/development.ini b/development.ini
index 44cef45..c13553e 100644
--- a/development.ini
+++ b/development.ini
@@ -9,14 +9,16 @@ use = egg:jujugui
 pyramid.reload_templates = true
 pyramid.default_locale_name = en
 
-jujugui.sandbox = true
+jujugui.sandbox = false
+jujugui.uuid = 'anon'
 jujugui.raw = true
 jujugui.combine = true
 jujugui.gzip = true
 jujugui.cachebuster = dev
 jujugui.controllerSocketTemplate = /api
 jujugui.socketTemplate = /model/$uuid/api
-jujugui.gisf = false
+jujugui.gisf = true
+jujugui.apiAddress = jimm.staging.jujucharms.com:443
 
 ; To use a JIMM backend uncomment the following:
 ;   The actual WebSocket address for the JIMM you'd like to connect to.
```

Bring up the GUI; it should go to the canvas without you logging in, and not show a logged in user.
Deploy a charm and commit to deployment flow; you should get a login button and the model controller; the rest of DF should not load.

Login.

You should be able to complete DF.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6224/
Test FAILed.

**Comment by hatched** [comment]
Closing to apply updates.

**Pull request closed without merging**
