### PR TITLE
Support long names in scale up UI.

### PR DESCRIPTION
**Pull request by kadams54**
Fixes https://github.com/juju/juju-gui/issues/2505

### CODE REVIEW

**Comment by kadams54** [comment]
## QA

1. Add one of the openstack bundles to the model.
2. Switch to machine view.
3. Open the scale up UI.
4. Confirm that all the application names look good; they should all be aligned nicely with the icon on the left and the input on the right and longer names should be truncated. Hovering over a name should give you the full version via a tooltip.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6947/

**Comment by hatched** [comment]
Thanks @kadams54

**Comment by kadams54** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
