### PR TITLE
Fixed deploy-target

### PR DESCRIPTION
**Pull request by huwshimi**
Fixed deploy-target from erroring.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- visit `http://0.0.0.0:6543/:flags:/react/?deploy-target=cs%3Atrusty%2Fwordpress`
- the service should be deployed with no errors in your browser console

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3211/
Test PASSed.

**Comment by anthonydillon** [comment]
@huwshimi I'm getting an error in the console (`Uncaught TypeError: this._autoPlaceUnits is not a function` app.js:1990)

**Comment by jaycee** [comment]
QA notes:

I see the same failure that @anthonydillon sees.

**Comment by hatched** [comment]
I wasn't able to reproduce the issue mentioned by the others but then I noticed I was using a different target `/:flags:/react/?deploy-target=bundle%2Fdata-analytics-with-pig-latin-8`. When I switched to using the one mentioned in the QA instructions it failed with the same error.

**Comment by jaycee** [comment]
I see the same behavior as @hatch. Which is weird.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3219/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3220/
Test PASSed.

**Comment by huwshimi** [comment]
This fix should be fixed now.

**Comment by hatched** [comment]
Thanks for this :+1: QA :ok:

**Comment by huwshimi** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
