### PR TITLE
Update requirements.  Bump to 1.9.1.

### PR DESCRIPTION
**Pull request by bac**
QA: 

Run `make clean-all fast-babel qa-server` and ensure the gui comes up to the canvas w/o errors.

You'll need to grab the downloadcache from 

https://github.com/juju/juju-gui-downloadcache/pull/2

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3772/
Test FAILed.

**Comment by bac** [comment]
CI failure are expected until the companion downloadcache branch is merged.

**Comment by hatched** [comment]
:+1: QA :ok:

Pulled down the new download cache and then ran this branch it all worked as expected.

**Comment by makyo** [comment]
:+1:

**Comment by bac** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
