### PR TITLE
Update the tense of the changelog items

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3032.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add some apps, make some relations, make some config changes, expose etc.
- open the deploy flow
- open the changelog
- the items should be in the tense "will be"

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7832/

**Comment by jaycee** [comment]
Thanks @huwshimi!

**Comment by jaycee** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
