### PR TITLE
Display the same title when the cloud is chosen

### LINKED ISSUE #2471: Unclear heading on DF "Public Cloud" after I pick GCE/AWS/etc.
As I pick a cloud I can change it and there's a big heading "Public Cloud", huh? The only options are public clouds. Is this telling me anything? Do we need that? Maybe that can just stick to something like "Choose your cloud" or the like.

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #2471.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- open the df
- note the cloud section title
- choose a cloud
- check that the title hasn't changed

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6818/

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
