### PR TITLE
Fix search panel

### PR DESCRIPTION
**Pull request by huwshimi**
Fix search results display and add navigation from search results to entity details.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- using the header search box make a search
- check that the search results appear full width and above the inspector
- click on a search result
- you should navigate the the charm details page (no real content yet)

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3125/
Test PASSed.

**Comment by hatched** [comment]
:+1: QA OK 
Thanks for this fix!

If reasonable to do in this branch could you also make it so that it doesn't have a fixed height and instead shrinks like the inspector?

**Comment by huwshimi** [comment]
@hatched if you do a search that has a lot of results e.g. "apache" the search results should hit the bottom of the screen and then get a scrollbar. If you do a search with a small number of results e.g. "bob" the panel should cut off after the results list (and then if you resize your browser to cut off the results it'll get the scrollbar again). Is that not what you're getting?

**Comment by huwshimi** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3126/
Test PASSed.

**Pull request merged**
