### PR TITLE
Fix the GCE logo in Safari

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #2544.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- point guiproxy to prod
- start a new model and add an app
- open the df
- in the cloud selection section the gce logo should appear in full amazing colour

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7179/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
