### PR TITLE
Correctly display the loading spinner when getting credentials

### LINKED ISSUE #2487: GCE Credentials listing broken when using prod jimm
- Add a charm to the canvas.
- Enter the deployment flow and then click GCE.
- No credentials UI will be shown.

cloud-null is the cloud tag - but this works as expected on jujugui 
`ds":[{"user-tag":"user-hatch@external","cloud-tag":"cloud-null"}]},"version":1,"request-id":16}`

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #2487.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- use the gui with guiproxy and prod
- add an app
- open the deployment flow
- click on GCE
- check that the spinner appears and then the list of credentials or add credentials form appears
- clicking on other clouds should do the same

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6830/

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
