### PR TITLE
Setup expert flow

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- Use the `pay` flag with guiproxy on `staging`.
- load `/new/?dd=cs:~cmarstech/mattermost`
- you should see the expert flow

**Comment by huwshimi** [comment]
[Set up the expert flow logic](https://trello.com/c/fyqseuCf/544-set-up-the-expert-flow-logic)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8647/

**Comment by huwshimi** [comment]
Thanks for that @frankban. Did it give you an error above that? I'm having trouble reproducing...

**Comment by hatched** [comment]
I was also not able to reproduce the issue you are showing @frankban

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
