### PR TITLE
Make domain fields not required

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #2102.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- deploy the gui on openstack (or change the openstack provider key in deployment-flow.js to be `demonstration`)
- add an app
- open the deployment flow
- open the add credential form
- fill in all the fields except the domain name
- click submit
- there should not be a required field error

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5955/
Test PASSed.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
