### PR TITLE
Replace linkify util

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add an app e.g. mysql
- open the inspector config
- find a field with a url in the description
- the url should be a link

**Comment by huwshimi** [comment]
[Replace linkify util](https://trello.com/c/Lp6C7UJi/601-replace-linkify-util)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8668/

**Comment by huwshimi** [comment]
@hatched their website said it was only 6kb, I guess it was all lies. I'm just trying to stop us having to pass around all these custom utils... as well as maintain them.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
