### PR TITLE
Mv uncommitted

### PR DESCRIPTION
**Pull request by huwshimi**
Added uncommitted states to the machines, containers and units in the machine view.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- Use the flag `/:flags:/mv/`
- add a service
- open the machine view
- auto place the unit
- add a container
- see that the machines/containers have blue borders as does the unit icon
- deploy
- the borders should turn grey
- click destroy on the unit, the machine and the container
- the borders should change blue again

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3891/
Test PASSed.

**Comment by kadams54** [comment]
Very nicely done. QA is :ok: and code is :+1: - thanks!

**Comment by anthonydillon** [comment]
Code and QA looks great :+1:

**Comment by huwshimi** [comment]
Thanks for the reviews @anthonydillon and @kadams54! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
