### PR TITLE
Select machines when they are created

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: https://github.com/juju/juju-gui/issues/1133

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- open the machine view
- add a machine, it should be selected
- add a second machine, it should get selected
- add a service
- on the unplaced unit use the "Place to..." wizard to place the unit on a new machine, it should get selected

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4016/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4028/
Test PASSed.

**Comment by frankban** [comment]
:+1: thanks!

**Comment by bac** [comment]
code :+1:.  Starting QA

**Comment by bac** [comment]
QA-OK

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
