### PR TITLE
Implement Service.Expose and Service.Unexpose API calls (Juju 2.0).

### PR DESCRIPTION
**Pull request by frankban**
To QA, expose and unexpose services.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4460/
Test PASSed.

**Comment by hatched** [comment]
:+1: Looks good thanks! I'll ship this then follow-up with a QA with the other 2.0 branches that have landed.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
