### PR TITLE
Update ProfileHeader to use Snapshot testing

### PR DESCRIPTION
**Pull request by barrymcgee**

### CODE REVIEW

**Comment by barrymcgee** [comment]
## QA

- Run `make jest-test` and ensure no errors

**Comment by hatched** [comment]
Looks like a lint error @barrymcgee

**Comment by hatched** [comment]
That shapshot is a little crazy sized at over 1700 lines whereas the compared test is only 60 lines long. Can you double check the contents of the snapshot to make sure we're testing the appropriate thing.

**Comment by huwshimi** [comment]
@barrymcgee if you rebase after #3783 lands and update the snaphots they'll be drastically reduced in size.

**Pull request merged**
