### PR TITLE
Load when no models

### LINKED ISSUE #1657: Unable to load the GUI with JEM if you have no models
`Uncaught TypeError: Cannot read property 'hostPorts' of undefined` This is because we try to fetch the model details to pre-populate the u/p on load. This is only necessary for gui in Juju and not for gisf. The temporary fix is to simply call the callback with empty u/p and then return. The fix in the further future is to remove that call entirely and rely on macaroons.

### PR DESCRIPTION
**Pull request by huwshimi**
Don't try and connect to the first model if JEM doesn't return any. Fixes #1657.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load with jem but no models (I had to hack in an empty array: https://github.com/juju/juju-gui/blob/develop/jujugui/static/gui/src/app/app.js#L1376)
- the GUI should load without any `hostPorts` errors

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5063/
Test PASSed.

**Comment by hatched** [comment]
Thanks! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
