### PR TITLE
When deploying to an existing model, show the post deployment panel.

### LINKED ISSUE #3316: getstarted.md only shows when it's a brand new model
if I have an existing model and deploy a charm or bundle with a getstarted.md it doesn't load the getstarted.md contents. It only does so when it's a fresh new model that I walk through the longer deployment flow pattern.

### PR DESCRIPTION
**Pull request by hatched**
Fixes #3316

### CODE REVIEW

**Comment by jujugui** [comment]
Build finished.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8264/

**Comment by mitechie** [comment]
This is failing for me. I created a model and added my prometheus charm by going from the empty model, to my profile, view the charm, add to model, and then I went through the DF and saw the get started text. 

I then closed that get started box and went back to my profile, selected to view my grafana charm, and when I hit "add to model" it ends up in a new model titled "untitled-model" and not the one I'd already created/was on.

**Comment by hatched** [comment]
@mitechie so it appears that you've run into a long standing issue. When you visit your profile/account it is supposed to disconnect from your existing model. This has become problematic for a number of reasons and we're going to schedule to get this resolved in the next cycle.

**Comment by hatched** [comment]
Thanks all for looking at this

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
