### PR TITLE
Select the added credential

### PR DESCRIPTION
**Pull request by huwshimi**
Also set the focus on the model name.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- deploy with GiJ (I used aws)
- use the blues flag
- open your profile and add a new model
- add an app
- click deploy
- when the deployment flow opens the cursor should be in the model name input
- add a credential
- when the form closes the select box should have the credential you just added selected

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5867/
Test PASSed.

**Comment by hatched** [comment]
Thanks @huwshimi This is working great!

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
