### PR TITLE
Moved the 'Create new' model button to be inline with the Models header

### PR DESCRIPTION
**Pull request by Lukewh**
Fixes https://github.com/juju/juju-gui/issues/2575

### CODE REVIEW

**Comment by Lukewh** [comment]
QA: Open profile, the 'Create new' model button should be floated right.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6886/

**Comment by hatched** [comment]
Thanks @Lukewh 
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
