### PR TITLE
Esc to close and more

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA: see the attached bugs

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3887/
Test PASSed.

**Comment by kadams54** [comment]
QA is :ok:. :+1: on the code changes. Thanks!

**Comment by anthonydillon** [comment]
Code looks good but getting a QA issue with long service names in the service list. See below:
juju admin

**Comment by huwshimi** [comment]
@anthonydillon nicely spotted, this should now be fixed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3904/
Test PASSed.

**Comment by huwshimi** [comment]
Thanks for the reviews @kadams54 and @anthonydillon! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
