### PR TITLE
Handle channel namespaced charms

### LINKED ISSUE #1294: Searching for the juju-gui charm has an id error.
If you do a search for "juju-gui" the results do not load and there is a browser console error "Uncaught Developers must initialize charms with a well-formed id."

### PR DESCRIPTION
**Pull request by huwshimi**
Allow channel namespaced charms to appear in search results. Fixes #1294.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- do a search for "juju-gui"
- the results should load
- click on the first juju-gui charm (it should be the first result)
- you should be taken to that charm
- visit `http://0.0.0.0:6543/services/?store=development%2Ftrusty%2Fjuju-gui`
- instead of a deploy button you should see a message

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4292/
Test FAILed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4293/
Test FAILed.

**Comment by hatched** [comment]
Closing for #1301

**Pull request closed without merging**
