### PR TITLE
Update the table component to handle expandable rows

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA: not yet used in the UI, so nowhere to QA currently. This will be used in the profile.

**Comment by huwshimi** [comment]
[Update the table component to handle expandable rows](https://trello.com/c/ypyDTGeg/121-update-the-table-component-to-handle-expandable-rows)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8336/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8337/

**Comment by huwshimi** [comment]
Thanks @frankban :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
