### PR TITLE
Expand the profile to the bottom of the screen

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3472.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- open your profile
- click on a page with a small amount of content
- check that the profile covers the deploy button at the bottom

**Comment by huwshimi** [comment]
[Fix profile overlay](https://trello.com/c/45sgVZBu/298-fix-profile-overlay)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8489/

**Comment by hatched** [comment]
@barrymcgee can you qa this with your active branch to see if it causes any unintended side effects?

**Comment by barrymcgee** [comment]
@hatched No, all good.

**Comment by hatched** [comment]
Thanks @barrymcgee

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
