### PR TITLE
More sidebar updates

### PR DESCRIPTION
**Pull request by huwshimi**
More visual updates to the inspector including scrollbar and unit lists.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- check that the scrollbar has been updated
- add a service and check that the lists of units look OK (for pending, errors etc.)

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2811/
Test PASSed.

**Comment by anthonydillon** [comment]
Code and QA :+1:

**Comment by hatched** [comment]
:+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2815/
Test PASSed.

**Comment by huwshimi** [comment]
Thanks @anthonydillon and @hatched :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/995

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/996

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
