### PR TITLE
Render the user menu even if we don't connect to a controller.

### PR DESCRIPTION
**Pull request by hatched**

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Visit the GUI in an incognito window under /new and the "login" link should be shown in the top right.
Log in, log out, etc. it should all work as expected.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8205/

**Comment by jaycee** [comment]
QA OK. :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
