### PR TITLE
Add analytics to mv drag and drop

### PR DESCRIPTION
**Pull request by hatched**

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Use the drag and drop in the machine view all ways and it shouldn't issue any errors related to the action.

There is one setState error that's not related.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8192/

**Comment by hatched** [comment]
Thanks @Lukewh :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
