### PR TITLE
Fix GUI frozen when clicking inspector relations

### PR DESCRIPTION
**Pull request by frankban**
…on a service with peer relations.

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3966/
Test FAILed.

**Comment by makyo** [comment]
:+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3967/
Test PASSed.

**Comment by makyo** [comment]
QA :ok:

**Comment by huwshimi** [comment]
Code :+1: thanks @frankban!

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
