### PR TITLE
Fix expanded content links

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3465. Fixes: #3525.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- toggle open a charm in the profile
- if it has a charm/bundle link they should appear otherwise those links should be hidden
- in the list of permissions you should be able to right click on the usernames and open in a new tab

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8518/

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
