### PR TITLE
Add bundle notification

### LINKED ISSUE #1131: Long delay between deploying a bundle to the canvas and it actually appearing.
When you "add to canvas" a bundle it takes a considerable amount of time to actually show up on the canvas. This is because we will get a few wss errors about invalid frame headers before it eventually succeeds:

`WebSocket connection to 'wss://demo.jujucharms.com/ws' failed: Invalid frame header`

We should show a notification when this action is performed in the event of a delay but the above issue should be fixed as well.

### PR DESCRIPTION
**Pull request by hatched**
Depending on your latency it may take a considerable time to fetch the changeset from bundlelib. So put up a notification so it indicates to the user that something is happening. Fixes #1131

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Deploy a bundle, it should show a notification while it's fetching the bundlelib data.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4088/
Test PASSed.

**Comment by bac** [comment]
code :+1: 
Doing QA now

**Comment by bac** [comment]
QA was fine chrome.

In Safari, the message showed up but was not inside the notification box. A problem with notifications in general on Safari not this branch.

**Comment by hatched** [comment]
Thanks! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
