### PR TITLE
Improve observeability of redirect info errors.

### PR DESCRIPTION
**Pull request by frankban**
Now redirection info errors are more apparent in the GUI, and also the code is less confusing.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6021/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6022/
Test PASSed.

**Comment by frankban** [comment]
Thanks for the review Brad.
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
