### PR TITLE
Allow mid-word line breaks for revision content.

### PR DESCRIPTION
**Pull request by kadams54**
Fixes https://github.com/juju/juju-gui/issues/1244

### CODE REVIEW

**Comment by kadams54** [comment]
## QA

Pull up `/services/?store=trusty%2Frabbitmq-server`, click on the "See more" button in the revisions box, and verify that the long URL on the 2015-10-14 revision no longer overflows. Check the text of other revisions to make sure they still look sane.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4297/
Test PASSed.

**Comment by makyo** [comment]
:+1: QA OK

**Comment by anthonydillon** [comment]
Code and QA :+1:

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
