### PR TITLE
Added correct icons to the added services sidebar

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- Check that the ">" after "Added Services" in the sidebar is now an icon and not a font character
- click "Added Services"
- check that the close icon "x" is now an icon and not a font character

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2345/
Test FAILed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2346/
Test FAILed.

**Comment by makyo** [comment]
Passing build: http://ci.jujugui.org:8080/job/juju-gui/2347/

**Comment by makyo** [comment]
:+1: QA okay - the new icons show and hide as expected.

**Comment by mitechie** [comment]
:+1: :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
