### PR TITLE
Hide drag over notification on local charm drop

### LINKED ISSUE #1264: When dropping a local charm the blue progress bar on the bottom stays on
When you drag and drop a local charm the blue progress bar along the bottom of the app stays around indefinitely.

### PR DESCRIPTION
**Pull request by hatched**
Fixes #1264

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Drag a local charm zip over the canvas and the drag over notification (blue bar along the bottom) will appear. When you drop the local charm zip on the canvas this blue bar should disappear.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4229/
Test PASSed.

**Comment by anthonydillon** [comment]
QA :+1: and code :ok:

**Comment by hatched** [comment]
Thanks! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
