### PR TITLE
Use shapeup on the machine view component tree.

### PR DESCRIPTION
**Pull request by frankban**
This is an experiment about using shapeup in the machine view.
I am pretty happy about how testing can be made easier by introducing the library.
Of course the diff is huge due to all the changes in the properties of a quite complex component tree (and its tests).

### CODE REVIEW

**Comment by frankban** [comment]
QA: use the machine view as much as possible, check that it works and no JS errors are raised.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7989/

**Comment by frankban** [comment]
Thanks for the review and QA!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
