### PR TITLE
Escape hashes in the embedded SVGs so they work in Firefox

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3042.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- in Firefox add an app and open the expose section in the inspector
- toggle the expose
- the cross and tick icons should appear correctly

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7885/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7886/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
