### PR TITLE
Correctly reload when switching envs in the sandbox

### LINKED ISSUE #1222: Switching models in sandbox locks you out of the GUI
If you click 'Sandbox' in the model switcher in sandbox mode it shows the loading spinner but never drops you back to the canvas.

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #1222

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load the gui
- open the env switch and click "sandbox"
- the gui should reload

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4176/
Test FAILed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4177/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4178/
Test PASSed.

**Comment by hatched** [comment]
:+1: :ok: :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
