### PR TITLE
Add optional gzip compression (on by default).

### PR DESCRIPTION
**Pull request by jaycee**

### CODE REVIEW

**Comment by jaycee** [comment]
QA:

Run `make run`; load the app while watching the network tab of your browser's debug tools. Note the compression in effect by the amount being transferred being less than the file size.

Edit development.ini to set `jujugui.gzip` to "false". Re run `make run` and again check the network tab--you should see transfer size and file size now be the same.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4202/
Test PASSed.

**Comment by fabricematrat** [comment]
:+1:  Code :ok: Just wonder why we do it in the wsgi app instead of Apache with mod deflate.

**Comment by jaycee** [comment]
@fabricematrat We don't actually provide the gui with apache in the charm--the guiserver directly serves the gui, so we need this option there.

In HJC, where we do have apache (and I believe openstack is already configured to use mod_deflate or could be) we'll turn this setting off.

**Comment by hatched** [comment]
:+1: :ok:

Thanks this is awesome! With minification only 505KB(total) are now being sent over the wire :)

**Comment by jaycee** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
