### PR TITLE
Fix the positioning of the usso login notification

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3285.

### CODE REVIEW

**Comment by jujugui** [comment]
Build finished.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8240/

**Comment by hatched** [comment]
QA Notes:
- When visiting `/new` in an incognito window and hovering over the "login" link in the top right the tooltip is now partially off the screen.
- After adding items to the canvas and opening the deployment flow when not logged in. Hovering over the "Sign up" link at the bottom of the section has the tooltip cut off at the bottom.

**Comment by huwshimi** [comment]
@hatched this is what I see in the DF
hover

**Comment by huwshimi** [comment]
Closing in favour of #3311.

**Pull request closed without merging**
