### PR TITLE
Open docs windows when exporting

### PR DESCRIPTION
**Pull request by anthonydillon**

### CODE REVIEW

**Comment by anthonydillon** [comment]
## QA
- Click on export
- Check the download happens and a new tab to https://jujucharms.com/docs/stable/charms-bundles#local-deploy-via-command-line opens

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4425/
Test PASSed.

**Comment by hatched** [comment]
This isn't going to be a very good user experience for anyone but absolute beginners. There should probably be a popup in the GUI instead which can be disabled/dismissed similar to the cookie warning.

**Comment by anthonydillon** [comment]
Totally agree @Lucapaulina

**Comment by Lucapaulina** [comment]
We'll be wrapping this into a new notification so it'll be disconnected.
This should only work for the demo not for standalone.

**Pull request closed without merging**
