### PR TITLE
Upgrade react.js to 0.14.3

### PR DESCRIPTION
**Pull request by hatched**

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA
`make clean-all deps fast-babel run`
Then play around in the GUI to make sure everything still works as expected.

**Comment by makyo** [comment]
I hate shrinkwrap :P  :+1: QAing now

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3643/
Test PASSed.

**Comment by makyo** [comment]
QA :ok:

**Comment by hatched** [comment]
Thanks @makyo :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
