### PR TITLE
Add hover state for service blocks

### PR DESCRIPTION
**Pull request by anthonydillon**

### CODE REVIEW

**Comment by anthonydillon** [comment]
### QA
- Drop a service on the canvas
- Hover over the service and it should look like the hover states in the design (below)
- Commit and hover and the hover border should match the service state colour
- Check a few states and make sure the border colours match

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3135/
Test FAILed.

**Comment by anthonydillon** [comment]
service-blocks_states01 1

**Comment by makyo** [comment]
:+1: thank

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3136/
Test PASSed.

**Comment by hatched** [comment]
:+1: QA :ok:

QA Notes:
- The fade in is almost too fast. If I wasn't looking for it I probably would say there was none. 
- When I saw the designs I had assumed that it would increase it's diameter out from the solid line instead of fade in. Thoughts on this animation instead?

**Comment by anthonydillon** [comment]
Right as always @hatched, I've updated the animation to grow in radius.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3149/
Test PASSed.

**Comment by anthonydillon** [comment]
Thanks :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by hatched** [comment]
Thanks @anthonydillon It looks awesome!

**Pull request merged**
