### PR TITLE
Even more prop types

### PR DESCRIPTION
**Pull request by huwshimi**
In this branch:
- add lint to check for missing proptypes and to check they are defined alphabetically
- add prop types to the remaining components
- alphabetise prop types
- add missing prop types to tests to suppress warnings
- update props in tests to be the correct type

### CODE REVIEW

**Comment by huwshimi** [comment]
Apologies for the size of this branch, however it's not quite as bad as it seems, you can mostly just see that prop types have been added or moved arround.

QA: CI should pass.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5221/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5223/
Test PASSed.

**Comment by hatched** [comment]
Thanks for adding all of these types! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
