### PR TITLE
Move the deploy input to a generic component

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- check some of the instances where the input is being used (e.g. the profile) and check that it still appears

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5521/
Test PASSed.

**Comment by hatched** [comment]
Thanks @huwshimi more generic components are great!

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
