### PR TITLE
Added a 'watch' target to makefile

### PR DESCRIPTION
**Pull request by hatched**
When the `watch` target is run it will wait for any changes to the `GUISRC` file tree and then run the `gui` target.

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2793/
Test PASSed.

**Comment by jaycee** [comment]
Code looks :+1: 

QA notes:

Ran `make watch`; randomly edited some js and scss files. In each case saw gui get rebuilt.

QA OK.

**Comment by makyo** [comment]
:+1: awesome!

**Comment by hatched** [comment]
great thanks for the reviews! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
