### PR TITLE
Deploy with the DF

### PR DESCRIPTION
**Pull request by huwshimi**
Set up the deploy method for when we're ready to have this step work.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA: No way to QA this currently.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5618/
Test PASSed.

**Comment by anthonydillon** [comment]
Looks good thanks :+1:

**Comment by hatched** [comment]
Thanks @huwshimi 
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
