### PR TITLE
Allow pointer events through sticky header.

### PR DESCRIPTION
**Pull request by kadams54**
Fixes https://github.com/juju/juju-gui/issues/1760.

### CODE REVIEW

**Comment by kadams54** [comment]
## QA

1. Pull up details for a charm.
2. Scroll down until the sticky header appears.
3. Mouse over the sticky header.
4. Verify that you can still scroll.
5. Verify that clicking on the links and buttons still works.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5430/
Test PASSed.

**Comment by hatched** [comment]
QA Notes: If you follow the QA instructions 'exactly' the same issue persists because the pointer events were turned back on for the button (which I think they have to) So this solves the 'bigger' problem that the whole header would block the scroll. 

So I'm QA :ok: on this but we'll have to keep an eye out for more user bugs around this interaction.

**Comment by kadams54** [comment]
Thanks @hatched! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
