### PR TITLE
Mark subordinates as such

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #2883.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load /u/tengu-team/jupyter-notebook-spark/2
- you should see "Subordinate (?)" in the header, below the charm name
- clicking (?) should take you to the subordinate docs
- viewing a normal charm should not have that notice

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7338/

**Comment by jaycee** [comment]
QA OK.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
