### PR TITLE
Model switcher: properly handle the case of models never connected.

### PR DESCRIPTION
**Pull request by frankban**
Fixes https://github.com/juju/juju-gui/issues/2694
Fixes https://github.com/juju/juju-gui/issues/2695

### CODE REVIEW

**Comment by frankban** [comment]
Refer to the linked bugs for QAing this. Make sure you create at least three models. Note that using add-model from the CLI let's you add models without connecting to them, so that you can then test how those are handled in the model switcher.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7032/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7033/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7034/

**Comment by kadams54** [comment]
QA looked good; however, I decided to move "never accessed" models to the top of the list, so added my own commit to the branch. Should be easily revert-able if others feel differently or we change our minds on down the road. :shipit:

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7035/

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
