### PR TITLE
Fix status view error when open ports are not available yet.

### PR DESCRIPTION
**Pull request by frankban**
Also fix another problem when scaling up units of an application.

### CODE REVIEW

**Comment by frankban** [comment]
QA:
- deploy nagios with no units;
- expose it and commit;
- now scale it up to one unit from the inspector;
- deploy and the unit should be correctly added, with no errors in the console;
- while the unit is pending, switch to the status view;
- check that the newly deployed unit is visible, and it does not have any ports opened;
- check that there is no JS error in the console;
- wait until the unit is completely deployed, and at this point you should see that "80/tcp" is open.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8217/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge/2564

**Comment by frankban** [comment]
Seems spurious, trying again.
:shipit:

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
