### PR TITLE
Deselect check all

### LINKED ISSUE #1314: When submitting unit actions all checkboxes are deselected except select all
To reproduce, add a large number of units to a service, deploy, then turn on the simulator (ctrl+s). Once you get a number of units in error or pending, open the unit list and select all then click a unit action button. You'll notice that all of the unit checkboxes get unchecked but the 'select-all' does not.

### PR DESCRIPTION
**Pull request by huwshimi**
Deselect the select all button when a button is clicked and show a message if there are no units. Fixes #1314.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add a service
- add a few units
- view the unit list
- click select all
- uncheck one of the units
- click Remove
- check that the select all checkbox is no longer checked
- remove all the units
- there should be a message about scaling up

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4363/
Test PASSed.

**Comment by hatched** [comment]
:+1: :ok:
Thanks!

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/1491

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/1492

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
