### PR TITLE
Use proper key for addPendingResources in deployment summary.

### PR DESCRIPTION
**Pull request by hatched**
Fixes #2179

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

- Use the production charmstore and search for 'easy-rsa', 
- Add it to the canvas and enter the deployment flow.
- Expand the summary and see that it says that resources were added.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6193/
Test PASSed.

**Comment by anthonydillon** [comment]
default juju gui

**Comment by frankban** [comment]
Looks good! 👍

**Comment by hatched** [comment]
Thanks! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
