### PR TITLE
Hide buttons for the initial state of the GUI

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- open the gui
- only the import and install juju buttons should be visible in the bottom right of the canvas
- add a service
- the deploy button etc. should appear
- remove the service
- the deploy button etc. should disappear

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4412/
Test PASSed.

**Comment by kadams54** [comment]
Code is :+1: and QA is :ok:

**Comment by anthonydillon** [comment]
Code and QA :+1:

**Comment by huwshimi** [comment]
Thanks! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
