### PR TITLE
Center relation lines to the service blocks

### PR DESCRIPTION
**Pull request by anthonydillon**

### CODE REVIEW

**Comment by anthonydillon** [comment]
QA
- Create a relation between two services and check the relation line comes from the center of the service block
- Check the pending relation line appears behind the service blocks

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2855/
Test PASSed.

**Comment by huwshimi** [comment]
Maybe just a test for the new positioning. Might be worth leaving the poles test in as well if you can find a way to test it.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2863/
Test PASSed.

**Comment by makyo** [comment]
:+1: QA okay in chrome and firefox!

**Comment by huwshimi** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
