### PR TITLE
Fixed scrollbar appearing on empty canvas with a real Juju

### LINKED ISSUE #1435: When switching models a horizontal scrollbar is shown
In a real env create multiple models and then refresh the page. Switch to a different model and you'll notice a horizontal scrollbar now at the bottom of the canvas.

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #1435.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- deploy this branch with Juju (with multi env)
- add and switch to a second model with no services
- check that there is no horizontal scrollbar at the bottom of the screen

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4610/
Test PASSed.

**Comment by hatched** [comment]
Thanks @huwshimi :+1: 
I'd be interested to know why this was the cause of the issue.

**Comment by kadams54** [comment]
:+1: from me as well.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by hatched** [comment]
QA :ok:

**Comment by huwshimi** [comment]
@hatched I think what was going on was that on the empty state with a real juju the import link was forcing the hidden file input onto a new line and expanding the deployer bar, I moved the file out of the order so that it wasn't affecting the other fields.

**Pull request merged**
