### PR TITLE
Use the correct state to open the store

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3006.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- open the machine view
- click "Add applications to get started"
- the store should open and the url should contain "/store"

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7800/

**Comment by hatched** [comment]
Thanks @huwshimi 
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
