### PR TITLE
Submit scale up

### PR DESCRIPTION
**Pull request by huwshimi**
Allow scale up forms to be submitted when pressing enter in a form field. Fixes https://github.com/juju/juju-gui/issues/1212

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add a service
- open the machine view
- click the [+] new to New units
- enter a number of units and press enter
- the units should be added
- in the inspector open the unit list and click Scale service
- enter a number of units and press enter
- the units should be added

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4200/
Test PASSed.

**Comment by anthonydillon** [comment]
Code and QA LGTM :+1: 

Although I think it would be nice to focus on the input when you hit the [+] in both cases

**Comment by hatched** [comment]
:+1:

**Comment by huwshimi** [comment]
@anthonydillon I've added a card for that, thanks :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/1446

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
