### PR TITLE
Correctly collapse recommended search results

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #2616.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- search for a charm in the gui e.g. spark
- search for the same charm in jujucharms.com
- they should have the same number of recommended charms and the charms should be in the same order

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7729/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7741/

**Comment by Lukewh** [comment]
## QA OK

Really great @huwshimi, thanks!

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
