### PR TITLE
Add a 'gui' state handler for clearing out all GUI states.

### LINKED ISSUE #2282: In new state, machine view is not updated after model switch
Go to machine view, then switch model. Machine view is not updates. Neither is URL.

### PR DESCRIPTION
**Pull request by hatched**
Fixes #2282

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Try and reproduce the attached issue.
Also navigate around the GUI to make sure there are no unintended consequences.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6330/
Test PASSed.

**Comment by jaycee** [comment]
QA notes:

The url updates and I'm taken to my new model, though jarringly I am taken back to app view on the canvas.

**Comment by hatched** [comment]
Thanks @jaycee :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
