### PR TITLE
Fix the credentials form so it can be submitted by pressing enter

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3518.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- open your credentials list in your profile
- click the add button to open the form
- fill out the fields
- hit the enter key
- the form should get submitted and the credential added

**Comment by huwshimi** [comment]
[Fix the credentials form so it can be submitted by pressing enter](https://trello.com/c/6949XYkf/334-fix-the-credentials-form-so-it-can-be-submitted-by-pressing-enter)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8524/

**Comment by mitechie** [comment]
QA ok, ty helpful especially for credentials like maas. 

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
