### PR TITLE
Import normalize instead of local asset

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
[Import normalize instead of local asset](https://trello.com/c/YMnB3w1p/731-import-normalize-instead-of-local-asset)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8777/

**Comment by hatched** [comment]
Thanks @huwshimi 

Looks like this saves us 5KB of css pre-gzip.

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
