### PR TITLE
Display a commit button when committing

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3486.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- connect to a model
- make a change
- open the deployment flow
- the button at the bottom should say "Commit"

**Comment by huwshimi** [comment]
[Display a commit button when committing](https://trello.com/c/s58h7FoJ/344-display-a-commit-button-when-committing)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8531/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8532/

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
