### PR TITLE
Handle DF section display

### PR DESCRIPTION
**Pull request by huwshimi**
Add a method to handle the whether a section should be visible, disabled or complete.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5569/
Test PASSed.

**Comment by hatched** [comment]
Thanks @huwshimi :+1: :ok:

**Comment by huwshimi** [comment]
Thanks @hatched :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
