### PR TITLE
Updates to open charm and bundle cards 

### LINKED ISSUE #3460: Profile - updates to open charm and bundle cards
After our [discussion about links](https://github.com/juju/juju-gui/issues/3438) and trying various solutions, we have slightly updated the open card design for charms and bundles.

**Closed charm row**

- [x] Charm title to be a blue link, underline on hover
- [x] Tags to be #666666, blue underline on hover

**Closed bundle row**

- [x] Bundle title to be a blue link, underline on hover

**Open charm card**

- [x] Card padding 16px top and bottom
- [x] Charm title to change to 20px blue link, underline on hover
- [x] Tags to be #666666, blue underline on hover
- [x] trusty, xenial, Writeable, Readable and current release should be regular #111111 text
- [x] All other links should be blue, underline on hover
- [x] Remove padding under both the Writeable and Readable titles

**Open bundle card**

- [x] Card padding 16px top and bottom
- [x] Bundle title to change to 20px blue link, underline on hover
- [x] Writeable, Readable, machine number, unit number and current release should be regular #111111 text
- [x] All other links should be blue, underline on hover
- [x] Remove padding under both the Writeable and Readable titles

**Charms**
image

**Bundles**
image

### PR DESCRIPTION
**Pull request by barrymcgee**
Fixes #3460

### CODE REVIEW

**Comment by barrymcgee** [comment]
## QA

- Run feature branch under 'Profile' flag
- Check that open Bundles / Cards on Profile page match issues outlined in: https://github.com/juju/juju-gui/issues/3460

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8473/

**Comment by hatched** [comment]
CI failure appeared to be spurious, retrying...

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8474/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8476/

**Comment by spencerbygraves** [comment]
@barrymcgee looks good. The only thing is I'm seeing larger padding on the bundle card than charms, it looks to be 24px rather than 16px. And can the add button align with the bottom of the image please? Thanks.

image

**Comment by spencerbygraves** [comment]
@barrymcgee One other thing I've noticed is the spacing of bundle icons on the closed row could be improved. Should I make an extra issue for that as it wasn't on the list?

image

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8482/

**Comment by spencerbygraves** [comment]
@barrymcgee @hatched  👍 @cassiocassio and I are happy. Thanks.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
