### PR TITLE
Clear the selected credential when displaying the add credential form

### LINKED ISSUE #2371: when adding a credential in the DF the deploy button should be disabled
If you go to deployment flow and go to add credentials the deploy button is still available. 

I've indicated that I want to add new credentials and the fields show red/error but we still deploy with the default credential vs stopping to alert the user they've not been successful in adding those new credentials.

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #2371.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add an app
- open the df
- select a cloud
- select a credential
- scroll down and check the deploy button is enabled
- scroll back up and open the add credential form
- scroll down and check the deploy button is now disabled
- fill out the form and add the credentials
- scroll down and check the deploy button is enabled again

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6749/

**Comment by bac** [comment]
Did QA using guiproxy pointing to JIMM on production.
Everything worked as expected.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
