### PR TITLE
Fixed escape with react flag.

### PR DESCRIPTION
**Pull request by huwshimi**
Don't try and close the old deployer bar when pressing esc with the react flag.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- visit `/:flags:/react/`
- press the escape key
- make sure there are no errors in your browser console

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3307/
Test PASSed.

**Comment by hatched** [comment]
:+1: QA :ok:

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
