### PR TITLE
Update search input border

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #2794.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- check the search box now has a lighter border
- click in the search box
- the border next to the close icon should be the same colour as the input

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7208/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7209/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7210/

**Comment by huwshimi** [comment]
@hatched Thanks. Trivial so :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
