### PR TITLE
Profile header links

### PR DESCRIPTION
**Pull request by huwshimi**
Update to #3411.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- open the new profile
- you should see your name and email and links to Jaas in the header

**Comment by huwshimi** [comment]
[Update profile header](https://trello.com/c/EwplvNN2/178-update-profile-header)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8402/

**Comment by hatched** [comment]
Because of the changes required with the identity api, I'll make those changes, then pick this one up and finish it off.

**Comment by hatched** [comment]
Closing for #3418

**Pull request closed without merging**
