### PR TITLE
Update header CSS to allow clicking on the user in the sticky header.

### PR DESCRIPTION
**Pull request by frankban**
Fixes https://github.com/juju/juju-gui/issues/2890

### CODE REVIEW

**Comment by frankban** [comment]
QA: see linked bug.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7335/

**Comment by jaycee** [comment]
QA OK.

**Comment by jaycee** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Comment by hatched** [comment]
This will need to be reverted as it introduces a regression.

It was originally introduced because if your mouse was near the top of the details and you scrolled down. The header would now capture the scroll event and you'd no longer be able to scroll.

**Pull request merged**
