### PR TITLE
Display a create new model button on the empty profile.

### LINKED ISSUE #1722: Profile doesn't show create new button if you have no models
If you load the profile page when you don't have any existing models there is no create new button so you get stuck on that page.

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #1722.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5171/
Test PASSed.

**Comment by anthonydillon** [comment]
Code and QA :+1:

**Comment by hatched** [comment]
Thanks! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
