### PR TITLE
Set config options based on arguments

### PR DESCRIPTION
**Pull request by makyo**
Fixes https://bugs.launchpad.net/juju-gui/+bug/1467586

### CODE REVIEW

**Comment by makyo** [comment]
# QA

Save https://launchpadlibrarian.net/209720562/bundle%20%2816%29.yaml and drag it to the canvas.  Check the URL field on the ghost charm config and ensure that the config option matches.

**Comment by hatched** [comment]
:+1: Thanks for this fix! QA shortly

**Comment by hatched** [comment]
QA OK 

QA Notes
Imported bundles with set configuration options and deployed them. The configuration options persisted.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2625/
Test PASSed.

**Comment by jaycee** [comment]
Looks good, thanks.

:+1:

**Comment by makyo** [comment]
Thanks all :shipit:

**Comment by bac** [comment]
:+1:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
