### PR TITLE
Merge dropdowns

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3143.

### CODE REVIEW

**Comment by huwshimi** [comment]
[Merge duplicate dropdown components](https://trello.com/c/SawcNfOB/377-merge-duplicate-dropdown-components)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8554/

**Comment by huwshimi** [comment]
QA:
- click on the user menu in the top right
- it should appear/function as before
- open the credentials in your profile
- click on a ... at the end
- the edit/delete menu should appear as before
- open the machine view
- there should be a few vertical ...s, they should appear as before

**Comment by hatched** [comment]
User profile, cloud credentials dropdown:
screen shot 2018-03-06 at 10 19 40 am

QA OK with caveats

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8562/

**Comment by huwshimi** [comment]
Thanks @hatched, changes made :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
