### PR TITLE
Fix charm full path attribute

### LINKED ISSUE #2437: Charm details file list breaks for multi-series charms
On jujugui if you visit the 'term inator' charm and try and click on a file it'll generate a link like:

`https://www.jujugui.org/charmstore/v5/~hatch/xenial,trusty,precise/term-inator/archive/metadata.yaml`

where instead it should drop the series and just have

`https://www.jujugui.org/charmstore/v5/~hatch/term-inator/archive/metadata.yaml`

### PR DESCRIPTION
**Pull request by hatched**
Fixes #2437

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA
follow steps in issue.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6779/

**Comment by hatched** [comment]
:shipit: Thanks!

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
