### PR TITLE
Mv machine series

### PR DESCRIPTION
**Pull request by huwshimi**
Display the series on a committed machine (fixes https://github.com/juju/juju-gui/issues/1135). Handle missing hardware details (fixes https://github.com/juju/juju-gui/issues/1132).

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- open the machine view
- add a machine
- it should show the number of units and "hardware details not available"
- deploy
- the machine should now show the number of units, the series and the hardware details

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4015/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4031/
Test PASSed.

**Comment by bac** [comment]
Code :+1: Doing QA now

**Comment by jrwren** [comment]
:+1:  no QA

**Comment by bac** [comment]
QA-OK if run with 'make server'

If run with 'make qa-server' I get an error "Cannot read property 'replace' of null"

Unfortunately this is only showing up with minimization turned on, so it is difficult to see where it comes from.

**Comment by bac** [comment]
The following patch makes qa-server work:
```
[qa-1146]bac@salchicha:~/git/juju-gui$ git diff
diff --git a/qa.ini b/qa.ini
index 4b78abb..d5830f2 100644
--- a/qa.ini
+++ b/qa.ini
@@ -12,6 +12,7 @@ pyramid.default_locale_name = en
 jujugui.sandbox = true
 jujugui.raw = false
 jujugui.combine = true
+jujugui.apiAddress =

 # JEM/IdM connections
 jujugui.interactive_login = false
```

**Comment by bac** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
