### PR TITLE
Fix columns

### PR DESCRIPTION
**Pull request by huwshimi**
Don't allow machine view columns to expand.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add a service to the canvas
- open machine view
- click "Auto place"
- check that the machines (middle) column doesn't expand and all three columns have equal widths

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2652/
Test PASSed.

**Comment by bac** [comment]
:+1:
No QA yet.

**Comment by jaycee** [comment]
Looks good to me. :+1:

**Comment by fabricematrat** [comment]
:+1:  Code :ok:

**Comment by bac** [comment]
QA-OK in OS X on Safari, Chrome and FF and Vivid on Chrome.

**Comment by bac** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
