### PR TITLE
Support ie11

### PR DESCRIPTION
**Pull request by huwshimi**
Fix service click bug, remove unsupported browser notice.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- in IE11 load the gui
- there should not be an unsupported browser message
- add a service
- click on the service
- the service should highlight and there should be no errors in your console

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3665/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3666/
Test PASSed.

**Comment by hatched** [comment]
QA Issue: ( Win 8.1 IE11.0 )
 
It doesn't look like the inspector config pane height is limited, it appears to go off the edge of the page and does not scroll.

**Comment by hatched** [comment]
QA Issue:

Clicking "add to canvas" for a bundle fails with an error because `self` is not defined (https://github.com/juju/juju-gui/blob/develop/jujugui/static/gui/src/app/store/env/go.js#L2269) How did this get through lint? Might as well add the rule while you're here :)

**Comment by hatched** [comment]
QA Issue:

When hovering over service icons the 'create relation` icon doesn't show. Long click and drag still allows relation creation

**Comment by hatched** [comment]
QA Issue: 

Clicking the trash can in the relation tooltip does nothing, it should remove the relation.

**Comment by hatched** [comment]
QA Issue:

Clicking on a service icon does not open the inspector.

**Comment by hatched** [comment]
QA Issue:

Clicking "More" in the environment switcher updates URL but does not show the profile view.

**Comment by hatched** [comment]
QA Issue:

When clicking "Store" it fails because `makeEntityModel` is not defined. ( https://github.com/juju/juju-gui/blob/develop/jujugui/static/gui/src/app/components/search-results/search-results.js#L114)

**Comment by kadams54** [comment]
I confirmed the issues that @hatched encountered, with the exception of the first one about the inspector config pane. I just might not have looked in the right place?

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3702/
Test PASSed.

**Pull request closed without merging**
