### PR TITLE
Clear cookies, user, and charmstore cookie redirect

### PR DESCRIPTION
**Pull request by hatched**
When logging out of the GUI it should clear all the local cookies and redirect the user to log out of the charmstore if they are logged in.

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4577/
Test PASSed.

**Comment by kadams54** [comment]
QA is :ok: and code is :+1: - thanks!

**Comment by hatched** [comment]
Great thanks! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
