### PR TITLE
Fix deploy button enabling for machines.

### LINKED ISSUE #1446: Adding/Removing machines doesn't show deployer bar button
To reproduce use Juju 2.0
Create a new model and create a new machine in that model.
You'll see that no deploy button is shown on the canvas.
This issue also happens once you deploy you're not able to -only- remove a unit.
If you want to test the removal strategy you'll have to add something else like a charm to get the deployer button to show up.

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #1446.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add a machine
- the deploy button should appear
- commit
- the deploy button should still be visible

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4617/
Test PASSed.

**Comment by hatched** [comment]
:+1: :ok:

Thanks this works like a charm!

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
