### PR TITLE
Correctly display series for a multi-series charm.

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: CanonicalLtd/jujucharms.com#460

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- view your profile (or the page for a team with a multi-series charm)
- click on a charm that has multiple series
- the series should be displayed in a comma separated list

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7257/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
