### PR TITLE
Model switching menu

### PR DESCRIPTION
**Pull request by frankban**
Already reviewed at https://github.com/juju/juju-gui/pull/2632
I just flagged the addModel permission with gisf so that the button for creating new models is enabled when connected to a multicontroller.
My changes are in separate commits.

Fixes https://github.com/juju/juju-gui/issues/2573

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6949/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6950/

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
