### PR TITLE
Set focus on login page

### LINKED ISSUE #1101: Set the focus to the username when viewing the login page

### LINKED ISSUE #1120: When opening up the context menu in mv2 it makes the machine column wider

### PR DESCRIPTION
**Pull request by huwshimi**
Set focus on the username on the login page (fixes #1101). Fixed the width of the machine column changing when opening the context menu (fixes #1120).

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3990/
Test FAILed.

**Comment by hatched** [comment]
:+1: :ok:
Thanks for these tweaks!

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3991/
Test PASSed.

**Comment by huwshimi** [comment]
:shipit:!

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
