### PR TITLE
Remove static paths from CSS

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #2964. Fixes: #1698.

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7774/

**Comment by huwshimi** [comment]
QA:
- start a new model
- open a charm's details
- check that the juju deploy input has an icon on the left and right
- add the charm
- add another charm and relate the two
- click on the relation
- there should be an uncommitted icon
- open the inspector
- open the list of units
- toggling a checkbox should show the tick
- go back and open the expose section
- toggling the expose toggle should show the icons
- go back and open configure
- changing the app name should show the uncommitted icon
- click deploy
- remove the model name and click outside the field
- the error icon should appear

**Comment by Lukewh** [comment]
## QA OK

**Comment by huwshimi** [comment]
@Lukewh I've updated the colours, but when I use `url-friendly-color(...)` the colours are darker than they should be.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7787/

**Comment by Lukewh** [comment]
Sorry @huwshimi I wasn't clear. I meant put the background-image's as vars:

```
$svg-tick-off: url("data:image/svg+xml,%3C.....");
...
background-image: $svg-tick-off;
```
So we have named images, rather then embedded SVG's, also means we can reuse them with them declared in one place.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7792/

**Comment by Lukewh** [comment]
Beautiful, thanks @huwshimi

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
