### PR TITLE
Fix formatting issues

### PR DESCRIPTION
**Pull request by bac**

### CODE REVIEW

**Comment by hatched** [comment]
:+1: Thanks for this cleanup!

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4093/
Test PASSed.

**Comment by bac** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
