### PR TITLE
Update component modules

### PR DESCRIPTION
**Pull request by huwshimi**
This is the first step in the migration from YUI modules to using Browserify/require/import. This also helps us move toward upgrading React.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA: No QA required, tests should pass (you could run the GUI to make sure it loads if you really want to).

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7811/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7812/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
