### PR TITLE
mega-watcher handlers: always store the workload status message.

### PR DESCRIPTION
**Pull request by frankban**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5252/
Test PASSed.

**Comment by frankban** [comment]
Here is a command that can be useful while QAin or developing based on this new exposed info:
`juju run --unit wordpress/0 'status-set active "foo bar"'`

**Comment by anthonydillon** [comment]
Code and QA :+1: using the juju run command in the QA tip. Could not test a true pending message due to the failure between beta8 and the latest GUI.

One small question, why is the new field camelcase when all other attrs are lowercase with underscores? Would it be better for consistency to be `workload_status_message`?

QA steps taken:
- Deployed this GUI to a new LXD controller
- Checked the juju-gui application using `app.db.units.getById('juju-gui/0')` in the console
- workloadStatusMessage was empty string
- Ran `juju run --unit juju-gui/0 'status-set active "foo bar"'` and ran the above again in the console
- workloadStatusMessage was 'foo bar'

**Comment by hatched** [comment]
@anthonydillon the underscores are legacy from way back that haven't yet been updated.

**Comment by frankban** [comment]
Thanks for the reviews!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
