### PR TITLE
Export proper data

### PR DESCRIPTION
**Pull request by hatched**
We need to skip pending relations on the environment exports as well as skipping the GUI machine.

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

To set up a real environment:
```
mkdir -p ~/charms/trusty
cd ~/charms/trusty 
bzr branch lp:~juju-gui/charms/trusty/juju-gui/trunk juju-gui
juju bootstrap local
juju deploy --repository=~/charms local:trusty/juju-gui
juju set juju-gui juju-gui-source="https://github.com/hatched/juju-gui.git export-proper-data"
```

In a fake environment:
- Drag Ghost, Mysql, Haproxy
- Relate Ghost and Mysql
- Commit and autoplace
- Relate Ghost and Haproxy
- Export
- The export should only have the Ghost Mysql relation

In a real environment:
- Click export when you only have the GUI in your environment.
- The export should have empty top level objects.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2507/
Test PASSed.

**Comment by jaycee** [comment]
Code looks good, @hatched. Thanks. :+1: 

QA to follow.

**Comment by jaycee** [comment]
QA notes:

In a fake environment, following the directions, I saw the expected behavior.

In a real environment, same deal--no juju gui in export list.

**Comment by jaycee** [comment]
QA OK, in case it wasn't clear.

**Comment by makyo** [comment]
:+1: and I will QA from #730

**Comment by hatched** [comment]
Thanks for the review and QA! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
