### PR TITLE
Don't try and move the relation when showing the ambiguous relation selector

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #1712.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add mysql twice
- connect the relation
- when the ambiguous relation popup is visible then hover over the canvas
- you should not get a heap of errors in your browser console

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7204/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
