### PR TITLE
Support syntax highlighting.

### PR DESCRIPTION
**Pull request by kadams54**
Add the Prism JS library.

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4280/
Test FAILed.

**Comment by kadams54** [comment]
## QA

Since there are new dependencies, it might be a good idea to run `make clean-gui fast-babel gui` first.

1. Pull up `/?store=trusty%2Fmongodb`.
2. Scroll to the portion of the README that has juju status output and inspect that element.
3. Add the attribute, `class="language-yaml"` (mimic'ing what would happen if we had a Markdown library that supported it).
4. In the console, run `Prism.highlightAll()`.
5. Tada! The code block should now have syntax highlighting.
6. Repeat for other code blocks in the page, trying other languages (e.g., bash).

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4284/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4285/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4304/
Test PASSed.

**Comment by hatched** [comment]
QA Issue: 

When trying to load the minified versions of the code convoy responds with the error: 
`[convoy.combo][waitress] No such file: app/assets/javascripts/prism.min.js`

**Comment by hatched** [comment]
QA Issue:

Even though this now has the markdown parser I still had to manually add the class and execute the prism method to make it highlight the yaml.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4305/
Test FAILed.

**Comment by kadams54** [comment]
Missing minified file should be fixed. No automatic highlighting is to be expected. Since I added these libraries in separate PRs, we'll need a third PR to wire them together. QA instructions (i.e., manual manipulation of the class) remain the same.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4306/
Test PASSed.

**Comment by hatched** [comment]
:+1: :ok: Thanks for this update!

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
