### PR TITLE
Fix react registration problem in embedded GUI.

### PR DESCRIPTION
**Pull request by frankban**

### CODE REVIEW

**Comment by hatched** [comment]
:+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4733/
Test PASSed.

**Comment by frankban** [comment]
Thanks for the review Jeff.
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
