### PR TITLE
Fail gracefully when plans are not fetched.

### PR DESCRIPTION
**Pull request by kadams54**
Fixes https://github.com/juju/juju-gui/issues/1836.

### CODE REVIEW

**Comment by kadams54** [comment]
## QA

Probably going to be easiest to QA once we have charms with plans working in guimaas again. That said, you can fake things with a little jig-pokkery:

1. Change `entityModel.hasMetrics()` to `true` on line 166 of `entity-details.js`.
2. Load the GUI.
3. Set a breakpoint immediately inside the `_getPlansCallback` function of `entity-details.js`.
4. Hit the details page for a charm.
5. When your breakpoint triggers, use the console to set `error` to a truthy value: `error = 'foo'`.
6. Continue.

You may see plan elements show up with loading messages (pre-step #5) and then disappear (post-step #6). In the header, there is a plan dropdown. The main content has the actual plans block itself.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5423/
Test PASSed.

**Comment by hatched** [comment]
:+1: Thanks @kadams54

**Comment by hatched** [comment]
QA :ok: thanks @kadams54 :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
