### PR TITLE
Fix tour buttons

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3551.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- start the tour
- check that the next/previous buttons have arrows on them

**Comment by huwshimi** [comment]
[Fix tour buttons](https://trello.com/c/ef9hp21M/351-fix-tour-buttons)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8536/

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
