### PR TITLE
Inspector updates

### PR DESCRIPTION
**Pull request by anthonydillon**
Action buttons in the inspector now have a dividing line. Added the charm icon to the top bar of the inspector with a white border. The unit listing numbers found in the headers have been moved down to the "Select all units" row's.

### CODE REVIEW

**Comment by anthonydillon** [comment]
### QA
- Add a service to the canvas and see the charm icon persists in the inspector header.
- Check the unit count has now been moved to the Select all units row in the unit lists
- See that the action buttons have a divider line above them

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4748/
Test PASSed.

**Comment by hatched** [comment]
:+1: Looking good, no qa yet

**Comment by hatched** [comment]
QA :ok: Thanks!

**Comment by makyo** [comment]
:+1:

**Comment by anthonydillon** [comment]
Thanks :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
