### PR TITLE
Import urls from jaaslib

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
[Import urls from jaaslib](https://trello.com/c/ZrzKOtDt/677-import-urls-from-jaaslib)

**Comment by huwshimi** [comment]
QA:
- open charm details in the store, there should not be any console errors
- open status on a deployed model, there should not be any console errors

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8735/

**Comment by jaycee** [comment]
QA OK.

* open charm details in the store, there should not be any console errors :heavy_check_mark: 
* open status on a deployed model, there should not be any console errors :heavy_check_mark:

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
