### PR TITLE
Minor fixes to releasing instructions.

### PR DESCRIPTION
**Pull request by frankban**

### CODE REVIEW

**Comment by frankban** [comment]
Self-review: trivial doc change.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8375/

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
