### PR TITLE
Fix a number of small UI issues

### PR DESCRIPTION
**Pull request by anthonydillon**
Fixes: https://github.com/juju/juju-gui/issues/1819
Fixes: https://github.com/juju/juju-gui/issues/1816
Fixes: https://github.com/juju/juju-gui/issues/1707

### CODE REVIEW

**Comment by anthonydillon** [comment]
## QA
- Check the following issues have been resolved:
 - https://github.com/juju/juju-gui/issues/1819
 - https://github.com/juju/juju-gui/issues/1816
 - https://github.com/juju/juju-gui/issues/1707

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5365/
Test PASSed.

**Comment by huwshimi** [comment]
Great stuff @anthonydillon. QA OK :+1:

**Comment by urosj** [comment]
👍 

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
