### PR TITLE
Remove focus styling from service list item in inspector

### PR DESCRIPTION
**Pull request by anthonydillon**

### CODE REVIEW

**Comment by anthonydillon** [comment]
## QA
- Add two service to the canvas
- Hover over the service blocks and check the services in the inspector get the hover effect
- Hover over the inspector list and check the hover styling is correct
- Click the hide toggle in the inspector and mouse off the inspector and see the hover style does not persist

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3728/
Test PASSed.

**Comment by anthonydillon** [comment]
Related issue: https://github.com/CanonicalLtd/blues_browser/issues/1063

**Comment by hatched** [comment]
Thanks! :+1: QA :ok: :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
