### PR TITLE
Discharge when calling charm store whoami.

### PR DESCRIPTION
**Pull request by frankban**

### CODE REVIEW

**Comment by frankban** [comment]
QA:
connect guiproxy to production jimm (with gisf set to true), visit your profile with the GUI and ensure that you are automatically authenticated to the charm store (you can see your charms and bundles).

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7297/

**Comment by Lukewh** [comment]
QA OK frankban, no 'login to charmstore'

**Comment by frankban** [comment]
Thanks Luke for the review!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
