### PR TITLE
Remove the WebSocket logger.

### PR DESCRIPTION
**Pull request by frankban**
This allows for a YUI free reconnecting WebSocket module, therefore fixing teh currently broken GUI develop branch.
The WebSocket logging utility does not seem to be actually used by anyone.
We can discard this PR if proved otherwise.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5574/
Test PASSed.

**Comment by urosj** [comment]
LGTM, didnt find any other aspects of code that use this. 

QA OK on juju tip and beta14.

**Comment by frankban** [comment]
As discussed, we are going ahead and merge this. If the WebSocket logging utility is in use elsewhere we can reintroduce it later, but for now this fixes the GUI.
Thanks for the review Uros!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
