### PR TITLE
Fix login with USSO.

### PR DESCRIPTION
**Pull request by frankban**
QA:
- bootstrap a Juju controller with: `juju bootstrap lxd lxd --upload-tools --config identity-url=https://api.jujucharms.com/identity`;
- grant access to your USSO user with something like: `juju grant --acl write frankban@external default`;
- upgrade the GUI with the dist from this branch;
- login with credentials and with USSO: both should work.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5373/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5375/
Test PASSed.

**Comment by urosj** [comment]
Code 👍 QA 🆗

**Comment by frankban** [comment]
Thanks for the review Uros!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
