### PR TITLE
Set root to null when switching models.

### PR DESCRIPTION
**Pull request by hatched**
Fixes: #2285

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Reproduce steps in bug

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6336/
Test PASSed.

**Comment by hatched** [comment]
Thanks @huwshimi :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
