### PR TITLE
Right-clickable profile breadcrumb link.

### LINKED ISSUE #2588: cannot right-click open in new window on the breadcrumbs
per the title

### PR DESCRIPTION
**Pull request by kadams54**
Fixes #2588.

### CODE REVIEW

**Comment by kadams54** [comment]
## QA

1. Startup the GUI in your favorite fashion (guiproxy, gijoe, gisf, whatever).
2. Verify that the profile link in the header breadcrumbs is right-clickable.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7102/

**Comment by frankban** [comment]
QA ok, thank you!

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
