### PR TITLE
Only show the inspector header links on the application overview

### LINKED ISSUE #3433: Inspector header broken on some screens
The new charm details link doesn't work properly on some screens e.g.
header

### PR DESCRIPTION
**Pull request by hatched**
Fixes #3433

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Open the inspector and switch between the various tabs, the `charm details` and `get started` links should only be on the application overview.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8472/

**Comment by hatched** [comment]
Thanks @frankban 

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
