### PR TITLE
Replace copy to clipboard icon

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3000.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load details for a charm
- the deploy input in the top right should have the updated icon

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7861/

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
