### PR TITLE
When props are updated for user profile, update page title.

### LINKED ISSUE #3164: Incorrect page title when switching users in /profile
To reproduce:
- connect to a model owned by another user
- click their username in the breadcrumb to open their profile
- open the user menu in the top right and select 'profile' to view your profile.
- the page title will still be the other user.

### PR DESCRIPTION
**Pull request by hatched**
Fixes #3164

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Reproduce steps in the bug.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8199/

**Comment by jaycee** [comment]
QA OK

**Comment by hatched** [comment]
Thanks @jaycee 
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
