### PR TITLE
Update app circle panning

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #2147.

In this branch:
- bring the app circle inside the viewport if it's partially outside the viewport,
- only pan enough to bring the circle inside the viewport.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- start a new model
- add a new app
- the canvas should center on it
- drag it so that it is overlapping one of the edges
- click on the charm in the inspector list
- the canvas should pan so that the circle is within the viewport
- repeat with the other edges
- add some more bundles and charms and all should behave sensibly

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7290/

**Comment by jaycee** [comment]
QA notes:

I deployed the ghost charm; it was centered. On each edge of the screen as well as completely off the edge of the screen (e.g. no longer visible in canvas) clicking on the inspector brought it back to just inside the edge.

Deployed mysql, related the two, dragged them both off, and clicking them in the inspector brought them into just inside view.

QA OK.

**Comment by Lukewh** [comment]
Thanks @huwshimi :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
