### PR TITLE
Update the login command

### LINKED ISSUE #1418: The login screen find password text should be split onto two lines
When logging into a Juju 2.0 model.

screenshot from 2016-03-02 14 33 06

### PR DESCRIPTION
**Pull request by huwshimi**
Update the login command for Juju 2.0 and split over two lines. Fixes #1418.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- deploy the gui with juju 2.0 (or fake it)
- check that the password message is split over two lines and that it has the new command

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4611/
Test PASSed.

**Comment by hatched** [comment]
:+1: :ok:
Looks good, I like the 'code' block.
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
