### PR TITLE
Update search style in masthead

### PR DESCRIPTION
**Pull request by anthonydillon**

### CODE REVIEW

**Comment by anthonydillon** [comment]
## QA
- Check the search in the header matches the design [1]
- Click the search and see it stretches and shows the midpoint
- Check the store link has been removed
- Scale down to small screen and see the search icon opens to midpoint

[1] https://cloud.githubusercontent.com/assets/9105999/14288312/01d7e9de-fb4e-11e5-9892-3ee3f0847ac9.png

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4915/
Test PASSed.

**Comment by bac** [comment]
QA: The search box matches the design.

The only discrepancy I found was after expanding the search box, in the design the box, the rightmost charm card, and the 'Show more' box are all right aligned. In the current implementation the lower two align with the search close X.

**Comment by anthonydillon** [comment]
@bac good spot. I am working on the midponit in a follow up branch and that should take care of that. This branch is just updating the search box really.

**Comment by makyo** [comment]
:+1:

**Comment by bac** [comment]
:+1:

**Comment by anthonydillon** [comment]
Thank you :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
