### PR TITLE
Fix direct deploy loading

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA: Jeff

**Comment by huwshimi** [comment]
[Fix direct deploy loading](https://trello.com/c/ZzSP227c/623-fix-direct-deploy-loading)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8677/

**Comment by hatched** [comment]
Thanks @huwshimi looks good

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
