### PR TITLE
Remove inspector plans demo component

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA: everything is broken, there's no way to QA this at the moment. Tests should pass.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5648/
Test PASSed.

**Comment by anthonydillon** [comment]
Code removal seems ok. Why do we need to remove this? Seems close to what we want? :+1:

**Comment by huwshimi** [comment]
@anthonydillon this code was just added for a demo. See https://github.com/CanonicalLtd/juju-design/issues/98 for the UX that was decided on in Vilnius (minus the change/choose plan buttons).

**Comment by hatched** [comment]
Thanks for this @huwshimi 

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
