### PR TITLE
Update react-click-outside

### PR DESCRIPTION
**Pull request by hatched**
After updating the other dependencies this asset was throwing errors. So this updates it to the latest version with a couple modifications to allow it to work with our codebase.

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7967/

**Comment by hatched** [comment]
#### To QA

Open the search, model switcher, help menu and make sure you can click outside of them and they close with no errors in the console.

**Comment by hatched** [comment]
Thanks all! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge/2484

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
