### PR TITLE
Login update

### PR DESCRIPTION
**Pull request by huwshimi**
When the user authenticates from the profile page the data is now automatically updated.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- visit /profile/ in a new or private browser
- click the login button and complete the steps
- switch back to the profile tab and notice that your bundle and charm data has been updated without you refreshing the profile

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4518/
Test PASSed.

**Comment by anthonydillon** [comment]
Code and QA :+1: although I have to allow pop ups to login.

**Comment by hatched** [comment]
QA Issue:
- If you were already logged in but not 'really logged in' and you click the login button. Nothing happens. Once you refresh it then shows the users charms.
- After clearing and starting from a fresh state, logging in, etc. It updated my username but didn't actually update to show any bundles or charms unless I closed and re-opened `/profile`

**Comment by hatched** [comment]
There may actually be something wrong with how the macaroons/cookies are being handled here. @kadams54 is investigating.

**Comment by kadams54** [comment]
My investigation didn't really go anywhere. I found out that my local branch was in a weird git state. Once I sync'd up with develop and did a clean build, everything worked good.

I didn't run into the QA issues @hatched reported. Most everything seemed find. I did notice one issue, but I'm going to file a separate bug for it: the env switcher dropdown menu doesn't interact well with the user profile page. For example, it doesn't close when the user profile is opened. And if you click on it to re-open it while the profile is up, it opens underneath the profile.

QA is :ok: and :+1:

**Comment by kadams54** [comment]
After further discussion with @hatched we may have an issue with expired macaroons. That said, I think that's outside the scope of this PR. I'd be fine with this landing. What say you @hatched?

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4555/
Test PASSed.

**Comment by kadams54** [comment]
Continued in https://github.com/juju/juju-gui/pull/1409.

**Pull request closed without merging**
