### PR TITLE
Create new target to speed up babel builds

### PR DESCRIPTION
**Pull request by hatched**
To stop babel from starting a new instance for every file it's building on a fresh build use the new `fast-babel` target.

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3360/
Test FAILed.

**Comment by hatched** [comment]
#### To QA

`make clean-gui fast-babel gui`

It should be much faster processing babel and not attempt to re-build the js files when it starts the `gui` target.
Open the GUI, it should be normal

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3361/
Test PASSed.

**Comment by makyo** [comment]
It's certainly better!  Thanks :+1: QA ok

**Comment by hatched** [comment]
Thanks for the check! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
