### PR TITLE
Abort requests when unmounting the profile

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- open the profile
- immediately click Manage on the model
- in your browser console you should have no setState errors

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4597/
Test PASSed.

**Comment by hatched** [comment]
:+1: :ok: :shipit: 

Thanks for fixing this, nice to see those errors gone.

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
