### PR TITLE
Move store state out of root key

### LINKED ISSUE #2963: Navigating 'back' doesn't properly re-generate state
This issue is exposed by #2962 

Steps:
- Be connected to a model ie) /u/{username}/{model}
- Open the store
- Search for "ghost"
- View the charm
- Hit the browsers 'back' button until you reach /store
- Click another charm
The state will now be incorrect and so will the url. This is because when navigating 'back' the state that is generated see's that there is something in the 'root' portion of the url and stops generating state for the model component. This will also introduce another issue as the state will be parsed into the user component and not into the model component as it is coming from the url and will need to be disambiguated which may expose other complications.

### PR DESCRIPTION
**Pull request by hatched**
Having the 'store' state handled by root was causing a number of conflicts in app state. To resolve this, store has been moved to its own key.

Fixes #2963

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Use the store in every way you can think of, from many different places and keep an eye on the url, it should all still work as expected.

Note:
If you are connected to a model, then view your profile, then show the store, the URL will get out of sync because we don't actually disconnect from the model when you enter the profile. This is a separate existing issue that will be solved in a follow-up.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8198/

**Comment by hatched** [comment]
@Lukewh so there isn't really any convention for this anywhere but my rational was that we wanted the store to be shown, but not show a specific entity so `{store: ''}` seemed ok. I did consider `{store: true}` but because other values are `{store: 'u/hatch/ghost'}` having a boolean there seemed like mixing types.

**Comment by hatched** [comment]
Thanks all :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
