### PR TITLE
Fix bundle deployment in sandbox mode.

### PR DESCRIPTION
**Pull request by frankban**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA OK :+1: Thanks heaps for that!

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3297/
Test PASSed.

**Comment by frankban** [comment]
Thank you for the review!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
