### PR TITLE
Expose and deploy errors

### PR DESCRIPTION
**Pull request by huwshimi**
Added notifications for service expose and bundle deploys errors.

### CODE REVIEW

**Comment by huwshimi** [comment]
No QA (notifications have not been implemented yet).

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3688/
Test PASSed.

**Comment by kadams54** [comment]
:+1: LGTM.

**Comment by hatched** [comment]
:+1: QA :ok:

**Comment by huwshimi** [comment]
Thanks @kadams54 and @hatched :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
