### PR TITLE
Open active model, update empty image background

### LINKED ISSUE #1407: Update empty profile image with transparent/grey background.

### LINKED ISSUE #1422: Open by default the active model when viewing the profile page
Many people have asked how to exit the /profile view. It's not clear that you have to select a model then select 'manage'. As a temporary fix for this release we'll automatically open the active model in the profile page so that the manage button is clearly visible.

### PR DESCRIPTION
**Pull request by huwshimi**
Open the active model on the profile page, fixes #1422.

Update the empty profile image with a grey background, fixes #1407.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- open your profile
- see that the sandbox model is open
- check that the profile header reads "1 model" (it used to read "1 environment")
- load the profile when you have no charms/models/bundles (you can comment out the `componentWillMount` in user-profile.js)
- see that the cloud image is no longer on a white background

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4583/
Test PASSed.

**Comment by anthonydillon** [comment]
Code :ok: QA :+1: Much nicer with the new image!

**Comment by hatched** [comment]
:+1: 
Thanks! 
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
