### PR TITLE
Fix redoing relations in bundles

### LINKED ISSUE #1154: openstack-base in sandbox can't recreate relations once removed
Deploy openstack-base in snadbox mode. Remove relations between mysql, glance and nova controller. Try to recreate those relations.

@makyo @kadams54 Please take a look at this one.

### PR DESCRIPTION
**Pull request by makyo**
Fixes #1154

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4099/
Test FAILed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4100/
Test FAILed.

**Comment by makyo** [comment]
Passing tests: http://ci.jujugui.org:8080/job/juju-gui/4101/

**Comment by makyo** [comment]
# QA

* Deploy a bundle
* delete relation between two services
* add it back (should be possible)

**Comment by bac** [comment]
code :+1:, no qa

**Comment by hatched** [comment]
:+1: :ok:

I created and removed relations between pre-deployed and subordinate, and regular services. Added a bundle and removed/recreated relations between the pre-deploy and deployed services in the bundle. All worked as expected.

**Comment by makyo** [comment]
Thanks, :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
