### PR TITLE
Only show the controller info on the current user's profile

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3516.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- view your profile
- in the header you should see Jaas/home/about links
- view another user's profile
- the links should not be there

**Comment by huwshimi** [comment]
[Only show the controller info on the current user's profile](https://trello.com/c/cwi6Yzcd/335-only-show-the-controller-info-on-the-current-users-profile)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8525/

**Comment by hatched** [comment]
There have been a number of design discussions around the best way to handle this so until those are resolved it's best to not land this.

**Comment by huwshimi** [comment]
@hatched is there any reason to show that info? It has nothing to do with viewing a user's details...

**Comment by cassiocassio** [comment]
I’m working on this - have some sketches for discussion I’ll be putting on
the design repo. Removing those details is one possibility. Hang in there !

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
