### PR TITLE
[#2089] Moved header above panel.

### LINKED ISSUE #2089: Tool tip on the profile page hidden behind body of the page
image

### PR DESCRIPTION
**Pull request by kadams54**
Fixes #2089.

### CODE REVIEW

**Comment by kadams54** [comment]
## QA

1. Go to the user profile (you'll need to be running against guiproxy or a non-local JIMM).
2. Hover over the import button. Verify that the tooltip appears above the user profile panel.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6339/
Test PASSed.

**Comment by hatched** [comment]
Thanks @kadams54 :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
