### PR TITLE
Updated juju.js jem commands and tests for v2.

### PR DESCRIPTION
**Pull request by hatched**
A continuation of https://github.com/juju/juju-gui/pull/1604 to add Juju 2 support to JEM

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4941/
Test PASSed.

**Comment by frankban** [comment]
:+1: great stuff!

**Comment by hatched** [comment]
:shipit: Thanks!

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
