### PR TITLE
End of an era - Remove sandbox code

### PR DESCRIPTION
**Pull request by hatched**
With JAAS and GUIProxy we've determined that it's no longer a valuable use of our time to maintain the sandbox functionality in the GUI. This branch removes the sandbox and fakebackend code.

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6963/

**Comment by kadams54** [comment]
QA is :ok: - always love a PR that removes thousands of LOCs!

**Comment by frankban** [comment]
QA in gisf seems ok.
When going to the `make run` URL (http://0.0.0.0:6543/) the GUI hangs on the splash screen and the console has an `Uncaught TypeError: Cannot read property 'replace' of null at BuiltClass.createSocketURL`. Since `make run` is required if you want to use guiproxy, it would maybe be nice if the GUI detected the *static mode* (it's no longer sandbox) and handled that case better, for example with a page explaining how to use guiproxy and no console errors. This can be done as a follow up.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6971/

**Comment by hatched** [comment]
Thanks everyone! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6972/

**Pull request merged**
