### PR TITLE
[#2323] Fix drag-n-drop overlay in Safari.

### LINKED ISSUE #2323: Safari does not show drop overlays
When you try to drop a charm on the canvas using Safari the drop notification overlay does not appear.

### PR DESCRIPTION
**Pull request by kadams54**
Fixes #2323.

### CODE REVIEW

**Comment by kadams54** [comment]
## QA

You'll need an environment where you can use Safari to test the GUI. I use Vagrant to get up and running locally, but whatever floats your boat.

1. Pull the GUI up in Safari.
2. Try to drag-n-drop a .zip file (which is not a bundle) - you should see the overlay appear. When you drop the file, you should see an error.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6594/

**Comment by bac** [comment]
I have a text file that I compressed, so it is called notes.txt.zip. Clearly it is not a charm but is a proper zip file.

When I drag onto the canvas I get the overlay. When I drop I get the error message but the overlay stays and the canvas stays greyed out.

screen shot 2017-01-11 at 15 54 35

**Comment by bac** [comment]
After getting a branch based on Huw's work the QA was successful.  Thanks.

**Comment by kadams54** [comment]
Should be merged/shipped only after #2321 has landed.

**Comment by hatched** [comment]
Thanks @kadams54 :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
