### PR TITLE
use juju gui --show-credentials --no-browser

### PR DESCRIPTION
**Pull request by jrwren**
instead of juju show-controller --show-password as doc to login

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5957/
Test FAILed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5959/
Test FAILed.

**Comment by hatched** [comment]
Thanks for this update @jrwren but there are conflicts which need resolving before we can land it

**Comment by jrwren** [comment]
I do not know why there are merge conflicts.

**Pull request closed without merging**
