### PR TITLE
Remove old deployment flow

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
WARNING: do not land this until we are really sure we are ready for it!

**Comment by huwshimi** [comment]
QA:
- load the GUI with no flags
- open the profile
- click Create new model
- it should close the profile and give you a new model
- click Deploy
- the new deployment flow should open

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5856/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5857/
Test PASSed.

**Comment by urosj** [comment]
QA:
- model name, the text box should be selected by default, enables you to just type in the name
- credential name like aws_admin@local_aws should be better parsed ... but can be left for other PR
- later PR: we should select the default region as the one a controller is on (if possible)
- when creating new credentials, they are not selected by default, you have to reselect them
- same with region, even if it's selected with new creds, it needs to be reselected
- the checkboxes before deploy should be hidden (for now)

Tested on AWS ... looks good otherwise, nice to see this working! 

Also, please rebase so that we can test with 2.1.13 fixes (I couldn't deploy observable-kubernetes bundle).

Thanks, @huwshimi !!!

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5865/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5876/
Test PASSed.

**Comment by hatched** [comment]
Thanks @huwshimi This works great in Juju 2 but not so well in Juju 1 :) The DF doesn't open when clicking the commit button and there is an error:

`Uncaught TypeError: Cannot read property 'getCredentials' of undefined` from the `_renderDeployment` method.

**Comment by huwshimi** [comment]
@hatched I've updated this to deploy with Juju1, could you do another QA to check?

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5877/
Test PASSed.

**Comment by hatched** [comment]
Thanks @huwshimi after those updates it now works as expected on Juju 1 and 2!

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
