### PR TITLE
Remove old blues deployment flow

### PR DESCRIPTION
**Pull request by huwshimi**
This flow has now been superceded by a whole new implementation. We no longer have any need to keep it around.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- the tests should pass (the flow has already been disabled)

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5533/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5534/
Test PASSed.

**Comment by anthonydillon** [comment]
Write that is a lot of code being removed. Looks good :+1:

**Comment by hatched** [comment]
:cry: Lets shed a tear for all this code :shipit: 

Thanks @huwshimi

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
