### PR TITLE
Add auth options from settings to config.js

### PR DESCRIPTION
**Pull request by jaycee**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2940/
Test PASSed.

**Comment by jaycee** [comment]
QA notes:

QA for this branch actually needs to be done in a PR for another branch. If that branch QA's successfully, this is also successful.

**Comment by hatched** [comment]
:+1:

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2941/
Test FAILed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2942/
Test FAILed.

**Comment by bac** [comment]
:+1: once you make Jenkins happy.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2943/
Test PASSed.

**Comment by bac** [comment]
And please bump the version of this one too.  Or was there some reason you don't want to @jaycee ?

**Comment by jaycee** [comment]
@bac We haven't figured out the release process for this--should it maintain the juju-gui release numbers, should we start over with the python package, is this releasable outside of the charm, etc. Until we know what we're doing that release number and monkeying with it doesn't really mean anything.

**Comment by mitechie** [comment]
Why would we not maintain the juju gui release numbers? I guess with the pyramid change we're looking at a big change. I'd say the whole new UX is 2.0, but until then this would be 1.5?

**Comment by jaycee** [comment]
@mitechie Sure. So when we do a charm release we'll set the version to 1.5 on this?

**Comment by bac** [comment]
Yeah, but releasing the charm should be just about fetching the latest one.  If I release the charm I don't want to monkey with every piece of fat that goes into it.  Maybe I'm thinking about it from the wrong vantage point.

**Comment by mitechie** [comment]
@jaycee right, perhaps better put is:

"when pyramid-fork is merged with master...the version should be changed to 1.5.0"

The charm work is a secondary and is its own release from the gui release.

**Comment by jaycee** [comment]
> "when pyramid-fork is merged with master...the version should be changed to 1.5.0"

Sounds reasonable to me. Let's call that the decision, then.

**Comment by jaycee** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2945/
Test PASSed.

**Pull request merged**
