### PR TITLE
Fix error when closing a notification.

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #2998.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- open /new in a private window
- click Login in the top right
- when the notification appears click the x to dismiss it
- the notification should close
- there should be no error in your browser console

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7793/

**Comment by Lukewh** [comment]
## QA OK

**Comment by hatched** [comment]
Thanks @huwshimi :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
