### PR TITLE
Allow null unit placements and collocation

### PR DESCRIPTION
**Pull request by makyo**
Fixes problems with the openstack bundle as provided here: http://paste.ubuntu.com/12006147/

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2693/
Test FAILed.

**Comment by makyo** [comment]
# QA

Download the [openstack bundle](http://paste.ubuntu.com/12006147/) and deploy it in the GUI (can be done in develop; the issue was with changeset processing).  You should wind up with four machines with services collocated on them.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2695/
Test FAILed.

**Comment by hatched** [comment]
Code looks good :+1: 
No time for QA atm.

**Comment by makyo** [comment]
Rerunning http://ci.jujugui.org:8080/job/juju-gui/2696/

**Comment by huwshimi** [comment]
QA OK! I got four machines with four or five units each. Each machine had two units in the root container and the rest in individual containers. :+1:

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2702/
Test FAILed.

**Comment by makyo** [comment]
Thanks all :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/953

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
