### PR TITLE
Correctly set the id on the first unit.

### PR DESCRIPTION
**Pull request by huwshimi**
Correctly set the id for the unit that is created with a service.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add a charm
- add the same charm again
- open the unit list for the second service (e.g. wordpress-2)
- check that the unit name has the count in it (e.g. wordpress-2/0)

**Comment by jaycee** [comment]
Changes look good :+1: 

QA to follow.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3465/
Test FAILed.

**Comment by jaycee** [comment]
QA:

Deployed wordpress twice; The second one correctly was IDed as wordpress-2 and its 1 unit was wordpress-2/0 across the interface.

QA :OK:

**Comment by hatched** [comment]
:+1: Thanks for this fix! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/1186

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
