### PR TITLE
Add export link

### LINKED ISSUE #1076: Export bundle?
We've lost functionality to export bundles in new GUI.

### PR DESCRIPTION
**Pull request by huwshimi**
Add export env link to the deployment bar. Fixes #1076

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add some services to the canavs
- click Export
- a yaml file should be exported containing your changes

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3911/
Test PASSed.

**Comment by hatched** [comment]
:+1: :ok: :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/1338

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3912/
Test PASSed.

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
