### PR TITLE
Add unload event listener to wipe macaroons

### PR DESCRIPTION
**Pull request by makyo**

### CODE REVIEW

**Comment by frankban** [comment]
:+1: thanks!

**Comment by urosj** [comment]
:+1: QA

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3344/
Test FAILed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3345/
Test FAILed.

**Comment by makyo** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3348/
Test FAILed.

**Pull request merged**
