### PR TITLE
Add hover states to icons on overview actions.

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- visit `/:flags:/react/`
- add a service `app.get('charmstore').getEntity('precise/python-django', function(entity) { app.deployService(entity[0]); });`
- hover an item with an icon (e.g. Units, Configure)
- the icon should fade to a slightly darker grey

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3176/
Test PASSed.

**Comment by hatched** [comment]
:+1: QA :ok:

**Comment by kadams54** [comment]
:+1: Looks good to me.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/1085

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
