### PR TITLE
Remove Local cloud from DF

### PR DESCRIPTION
**Pull request by hatched**

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Use the blues flag.
Open the GUI in sandbox mode, add a charm to the canvas and click Deploy, there should not be a "Local" option.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5773/
Test PASSed.

**Comment by kadams54** [comment]
:+1: and QA is :ok:. Thanks!

**Comment by hatched** [comment]
Thanks @kadams54 
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
