### PR TITLE
Update package lock again, npm is 6.1.0 on xenial

### PR DESCRIPTION
**Pull request by frankban**

### CODE REVIEW

**Comment by frankban** [comment]
Self-review: package lock update.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8768/

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
