### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by hatched**
Update the dependencies and fix the lint errors after upgrading eslint.

### CODE REVIEW

**Comment by hatched** [comment]
It's a large diff but besides the package.json and shrinkwrap changes, it's all mechanical lint fixes.

#### To QA
`make clean-all deps fast-babel run`
QA the GUI to make sure it works in Juju 2, guiproxy

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6953/

**Comment by bac** [comment]
QA-OK for gisf.  Could not get GIJoe to cooperate but it is likely my environment.

**Comment by frankban** [comment]
QA ok on gijoe.

**Comment by hatched** [comment]
Thanks all :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
