### PR TITLE
Handle empty config fields in Firefox

### LINKED ISSUE #3402: Editing then removing charm changes doesn't remove the 'changed' indicator in Firefox
To reproduce:

Add Nagios to the canvas, scroll down to an input that is empty. Add a character and delete it. The blue indicator should disappear (as it does in Chrome).

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #3402.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load the gui in Firefox
- add an app
- open the inspector config
- add some text to an empty field
- the field should get a blue border
- delete the text
- the border should go back to grey

**Comment by huwshimi** [comment]
[Fix empty config fields in Firefox](https://trello.com/c/BnrbHj4o/222-fix-empty-config-fields-in-firefox)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8442/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8443/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8444/

**Comment by hatched** [comment]
When deleting then adding back the 0, the input still stays highlighted blue.

**Comment by huwshimi** [comment]
@hatched I can't reproduce that in the `AllowRoot` of zabbix-server. I'm using Firefox 58.0. Silly question, but you've got my latest changes?

**Comment by hatched** [comment]
Sorry @huwshimi maybe I had a bad cache, it appears to be working as expected now.

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
