### PR TITLE
Fix credential help spacing

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3495.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- go to your profile and open the form to add a credential
- check that is space between the fields and the help text unlike the screenshot in #3495.

**Comment by huwshimi** [comment]
[Fix credential help spacing](https://trello.com/c/RUGTAGf2/311-fix-credential-help-spacing)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8500/

**Comment by mitechie** [comment]
QA is ok-ish. The overlap is fixed but wonder if then there should be more space to the right of the icon before the text. 

updated-spacing

**Comment by huwshimi** [comment]
@mitechie oops, thanks, I forgot to copy over some classes.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8503/

**Comment by huwshimi** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
