### PR TITLE
On bundle import the drop indicator is removed

### LINKED ISSUE #1200: When dropping a bundle yaml on the canvas the blue indicator never disappears
To reproduce drag a bundle.yaml over the canvas, then out again. The blue bar across the bottom should disappear. Now drag it over and drop the bundle, you'll see that the blue line stays forever.

### PR DESCRIPTION
**Pull request by anthonydillon**
Fixes #1200

### CODE REVIEW

**Comment by anthonydillon** [comment]
## QA
- Drag a bundle.yaml over the canvas and check the blue indicator along the bottom appears
- Drag off the canvas and check the indicator is removed
- Drag back over and see the indicator appears again
- Drop the bundle.yaml on the canvas and check the indicator is removed

Fixes: https://github.com/juju/juju-gui/issues/1200

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4128/
Test PASSed.

**Comment by hatched** [comment]
:+1: :ok: Thanks for this fix!

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/1419

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/1420

**Comment by anthonydillon** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
