### PR TITLE
Apply cloud vanilla theme

### PR DESCRIPTION
**Pull request by anthonydillon**
Replaced vanilla with cloud-vanilla-theme (https://github.com/ubuntudesign/cloud-vanilla-theme) a theme of Vanilla with some small content tweaks to use the themed components.

### CODE REVIEW

**Comment by anthonydillon** [comment]
## QA
- Remove `node_modules` and clean-gui
- Run the GUI and check as many views as you can think of and check it matches tip/develop

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4784/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4785/
Test PASSed.

**Comment by anthonydillon** [comment]
Back ported components to cloud-vanilla-theme:
- Buttons
- Links

**Comment by hatched** [comment]
"Blocking" this branch until the 2.1.2 release is cut shortly.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4843/
Test PASSed.

**Comment by hatched** [comment]
:+1: QA :ok:

Thanks for this @anthonydillon

**Comment by makyo** [comment]
:+1:!

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
