### PR TITLE
Various fixes to the authentication system.

### PR DESCRIPTION
**Pull request by frankban**
This is a forward port of https://github.com/juju/juju-gui/pull/2301 but it also includes some improvements for the _getAuth method.

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6562/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6564/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6566/

**Comment by jaycee** [comment]
Loading `/new` while not logged in started out correct; I was able to view the charmstore, add a charm to canvas, and start deployment flow. DF loaded correctly with the model name ui and the sign in/log in button, but clicking that button didn't do anything. I see no errors in console--it just doesn't seem to engage login.

This was in an incognito session to ensure pre-existing session/cookies didn't screw anything up.

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
