### PR TITLE
Remove old UI

### PR DESCRIPTION
**Pull request by huwshimi**
Remove the subapp, browser, inspector and anything else related to the old UI. I've tried to be as thorough as I can, removing CSS, templates, docs, images, utils and tests.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3423/
Test PASSed.

**Comment by hatched** [comment]
This is a little sad...so much history here... :sob: 

:+1: QA :ok:

**Comment by jaycee** [comment]
Setting all that old code on :fire:. Thanks @huwshimi!

QA OK. :+1:

**Comment by huwshimi** [comment]
Thanks @hatched and @jaycee! With trepidation: :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
