### PR TITLE
Workaround cpu-cores bug in juju-core

### LINKED ISSUE #3560: "cores" constraint not working
On VMWare vsphere 6.5.0.13000, Juju 2.3.3, Juju GUI 2.12.1

Steps to reproduce:

1. Create controller on VMWare vsphere
2. Go to "machines" tab, click on the middle hamburger menu and choose "add machine"
3. Type in "4" in the "Cores" field and click "create"

What should happen: a machine with 4 cores is made
What happens: the default machine is created (2 cores)

### PR DESCRIPTION
**Pull request by hatched**
Fixes #3560 

Workaround for: https://bugs.launchpad.net/juju/+bug/1755580

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Bootstrap a new controller on GCE
Switch to the machine view and add a machine with 4 cores.
Deploy, you should have a machine with 4 cores.

Repeat with JAAS.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8585/

**Comment by huwshimi** [comment]
QA fine in JAAS and bootstrapped controller (both using AWS).

**Comment by hatched** [comment]
Thanks @huwshimi  :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
