### PR TITLE
Resize on subordinate status change

### PR DESCRIPTION
**Pull request by makyo**
This appropriately deals with all cases of a service moving between subordinate and not subordinate status except one (moving from subordinate back to non-subordinate service, there is a rendering issue with the add-relation button showing up off to the side, which appears in chrome).  As this situation has not cropped up (would be impossible in core\*), I'm leaving it until we find a way to fix that rendering

\* Why we're receiving subordinate information separate from environment status is the root of the problem, but not addressed in this card.  This card only touches on the display of services.

### CODE REVIEW

**Comment by makyo** [comment]
# QA

* If you're Uros, deploy a subordinate service (or a bundle containing one) and ensure that it shows as subordinate
* All: deploy a non subordinate service (displays as normal), open the console and enter `app.db.services.item(0).set('subordinate', true)` (service shows as a subordinate)

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3631/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3638/
Test PASSed.

**Comment by hatched** [comment]
QA Issue:
 I know the case we're trying to fix here is the case where the service goes from full to subordinate. But when I do that, then try and run it in reverse it puts the relation link in the incorrect spot.

**Comment by hatched** [comment]
:+1: QA :ok: Thanks for stickin with this and getting it solved!

**Comment by huwshimi** [comment]
Thanks @makyo QA OK :+1:!

**Comment by makyo** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
