### PR TITLE
Merge model tables

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- using the `profile` flag load the model list for your user
- check that your model list has both the models you own and those shared with you

**Comment by huwshimi** [comment]
[Merge my/shared model tables](https://trello.com/c/C75OJ8nN/132-merge-my-shared-model-tables)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8357/

**Comment by mitechie** [comment]
I tried this using staging first and it worked and i could see my staging model there. I do not have any shared models on staging. 

I then tested it on production and there I got the following error traceback and it behaved badly by flashing and redirecting to the canvas but with no model attached/etc. Clicking on the button in the upper right would repeat this. 

Traceback:

qa-error

**Comment by mitechie** [comment]
I tried this using staging first and it worked and i could see my staging model there. I do not have any shared models on staging. 

I then tested it on production and there I got the following error traceback and it behaved badly by flashing and redirecting to the canvas but with no model attached/etc. Clicking on the button in the upper right would repeat this. 

Traceback:

qa-error

**Comment by huwshimi** [comment]
Thanks @mitechie. Would you mind trying again with my update?

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8361/

**Comment by mitechie** [comment]
@huwshimi I've QA'd but still getting the same error. I'll reach out to you when you start tonight to see if we can figure out why my account is unhappy.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8366/

**Comment by mitechie** [comment]
The latest update works and QA-ok for my account. Thanks for sticking through that.

**Comment by huwshimi** [comment]
Thanks heaps @mitechie :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
