### PR TITLE
Don't mention JAAS in the non-gisf help

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3484.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load the GUI in gisf mode
- use the header link to open the help
- the "Getting started" section should mention JAAS
- load the GUI non-gisf mode
- open the help again 
- the "Getting started" section should mention Juju

**Comment by huwshimi** [comment]
[Non-gisf help link](https://trello.com/c/yQcXwme4/305-non-gisf-help-link)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8494/

**Comment by mitechie** [comment]
QA ok

**Comment by mitechie** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
