### PR TITLE
[#2216] Revert sticky header button to full width.

### LINKED ISSUE #2216: Add to canvas button should be the same size on sticky header as it is as the top of the page
image

screen shot 2016-11-21 at 11 14 51

### PR DESCRIPTION
**Pull request by kadams54**
Fixes #2216.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6231/
Test PASSed.

**Comment by kadams54** [comment]
## QA

1. Open a charm or bundle details page.
2. Scroll down enough to trigger the sticky header.
3. The button in the sticky header should be the same size as the one in the non-sticky header.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
