### PR TITLE
getstarted.md file should not be case sensitive.

### LINKED ISSUE #3293: getstarted.md request is case sensitive
The request for the getstarted.md file is case sensitive but shouldn't be.

https://github.com/juju/juju-gui/blob/2f29138b1d911bf82c94f05c18d64c5987f99c0f/jujugui/static/gui/src/app/components/post-deployment/post-deployment.js#L56

### PR DESCRIPTION
**Pull request by hatched**
Fixes #3293

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8235/

**Comment by hatched** [comment]
Change made, thanks @frankban 

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build finished.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8238/

**Pull request merged**
