### PR TITLE
Close profile on model-list model click.

### LINKED ISSUE #3479: New Profile: Right header links reference JAAS even in bootstrapped controller

### PR DESCRIPTION
**Pull request by hatched**
Fixes #3479

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Open the profile and click on a model. It should close the profile and connect to that model.
Open the profile again and click on the same model, it should return you to the canvas.
Open the profile again and click on a different model, it should change to that model.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8498/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8499/

**Pull request merged**
