### PR TITLE
Make sure the container exists when the gui is initialised in the tests

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- open test_app.js
- add `.only` to the top level describe
- run the tests
- the tests should pass
- comment out my change
- the tests should fail

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6031/
Test PASSed.

**Comment by hatched** [comment]
Thanks for this @huwshimi this is great! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
