### PR TITLE
For the user profile the root should always be blank

### PR DESCRIPTION
**Pull request by Lukewh**

### CODE REVIEW

**Comment by Lukewh** [comment]
QA: Follow steps described here: https://github.com/juju/juju-gui/issues/2317
You can also:
- Go to profile
- Create new model
- When back on canvas, click user profile link

**Comment by Lukewh** [comment]
Also - there's probably a follow up for adding this code path to the tests

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6627/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6628/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6629/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6630/

**Comment by hatched** [comment]
Thanks for this @Lukewh but in another branch I've also resolved this issue and moved some code around which will cause a conflict. So closing this to avoid that.

**Pull request closed without merging**
