### PR TITLE
Fix spinner

### PR DESCRIPTION
**Pull request by huwshimi**
Fix module conflict for spinner.

### CODE REVIEW

**Comment by huwshimi** [comment]
After a `make clean-all` I see a file `jujugui/static/gui/src/app/assets/javascripts/spinner.js` that also provides `YUI.add('spinner'...` which we use in the GUI currently.

QA:
- view a charm details page, it should display the spinner on load

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3316/
Test PASSed.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
