### PR TITLE
Speed up `make dist`

### PR DESCRIPTION
**Pull request by makyo**

### CODE REVIEW

**Comment by makyo** [comment]
# QA

* run `make dist`; still works
* run `GUI_NO_CLEAN=1 make dist`; dist builds without cleaning/refetching

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4420/
Test PASSed.

**Comment by hatched** [comment]
:+1:  Nice speedup!

**Comment by bac** [comment]
Why not just add a different target that does the dist without the clean?

dist: clean-all fast-dist

fast-dist: deps fast-babel gui test-deps collect-requirements
     do stuff here


:-1:

**Comment by bac** [comment]
But thanks for tackling the problem!

**Comment by bac** [comment]
Sweet. :+1:

**Comment by kadams54** [comment]
QA is :ok:

**Comment by makyo** [comment]
Sweeeet :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4421/
Test PASSed.

**Pull request merged**
