### PR TITLE
Close the search results when clicked outside

### LINKED ISSUE #2375: When looking at search results clicking the canvas doesn't close the search overlay
Noticed specifically when no search results appear. Also happens with the header.
When there are search results, the header click seems to work, but the canvas doesn't.

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #2375.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- do a search from the header
- click on the grey background at the top of the search results
- the search results should close

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6820/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6821/

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
