### PR TITLE
Allow credentials to be deleted

### PR DESCRIPTION
**Pull request by huwshimi**
Hook up the Destroy button on the account page to delete the credential.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add a service or machine
- start the deploy flow
- click on the AWS option to add a new credential
- fill in the fields and click "Add credential"
- close the deploy flow
- visit http://0.0.0.0:6543/account/
- click on the credential that you just added
- click Destroy on the top right
- after a brief pause the credential should be removed

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4863/
Test PASSed.

**Comment by hatched** [comment]
:+1:

**Comment by bac** [comment]
:+1:

**Comment by hatched** [comment]
QA :ok: I deployed this branch via the charm into a real env and was able to destroy existing credentials from jem.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
