### PR TITLE
Disable mangle to to prevent babili memory leak

### LINKED ISSUE #3707: make dist explodes
```
echo '{"version": "2.12.3", "commit": "69c74cb8dd14a27d6693f240bd686e6e23bd7623"}' > jujugui/static/gui/build/app/version.json
# We are only minifying the init bundle here because it takes considerable time.
node_modules/.bin/babel --presets babel-preset-babili --minified --no-comments ./jujugui/static/gui/build/app/init-pkg.js -o ./jujugui/static/gui/build/app/init-pkg-min.js

<--- Last few GCs --->

[30769:0x30ed7a0]   227931 ms: Mark-sweep 1282.4 (1472.1) -> 1282.4 (1473.6) MB, 1718.5 / 0.0 ms  allocation failure GC in old space requested
[30769:0x30ed7a0]   229667 ms: Mark-sweep 1282.4 (1473.6) -> 1282.3 (1433.1) MB, 1735.5 / 0.0 ms  last resort GC in old space requested
[30769:0x30ed7a0]   231443 ms: Mark-sweep 1282.3 (1433.1) -> 1282.3 (1427.6) MB, 1775.5 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2ee10b5a5879 <JSObject>
    1: set [native weak-collection.js:~27] [pc=0x3cb92cec4e29](this=0x25afa1957c19 <JSWeakMap>,key=0x1f10e18b0821 <Object map = 0x2333e2098c51>,value=0x4f5799fa6a9 <JSArray[0]>)
    2: set [/home/ubuntu/code/juju-gui/node_modules/babel-runtime/node_modules/core-js/library/modules/_collection.js:~37] [pc=0x3cb92cec567c](this=0x2f6e3858b7f9 <WeakMap map = 0x9891c3ee681>,a=0x1f10e18b0821 <Object ma...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x8c20ec [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [node]
 6: v8::internal::HashTable<v8::internal::ObjectHashTable, v8::internal::ObjectHashTableShape>::NewInternal(v8::internal::Isolate*, int, v8::internal::PretenureFlag) [node]
 7: v8::internal::HashTable<v8::internal::ObjectHashTable, v8::internal::ObjectHashTableShape>::New(v8::internal::Isolate*, int, v8::internal::PretenureFlag, v8::internal::MinimumCapacity) [node]
 8: v8::internal::HashTable<v8::internal::ObjectHashTable, v8::internal::ObjectHashTableShape>::EnsureCapacity(v8::internal::Handle<v8::internal::ObjectHashTable>, int, v8::internal::PretenureFlag) [node]
 9: v8::internal::ObjectHashTable::Put(v8::internal::Handle<v8::internal::ObjectHashTable>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int) [node]
10: v8::internal::JSWeakCollection::Set(v8::internal::Handle<v8::internal::JSWeakCollection>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int) [node]
11: v8::internal::Runtime_WeakCollectionSet(int, v8::internal::Object**, v8::internal::Isolate*) [node]
12: 0x3cb92c8842fd
Makefile:334: recipe for target 'dist' failed
make: *** [dist] Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by hatched**
Fixes #3707 

By disabling the 'mangle' option in babili we no longer get the memory leak causing `make dist` to crash. 

Re: https://github.com/babel/minify/issues/332

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Bootstrap a new controller and build a dist using `make dist` then `juju upgrade-gui <dist>`. Check to make sure that it functions correctly.
Do the same with `make fast-dist` 
Also check that `make run` works as expected.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8750/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8751/

**Comment by hatched** [comment]
Thanks @huwshimi :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
