### PR TITLE
services components

### PR DESCRIPTION
**Pull request by huwshimi**
Split out the deployment flow services components

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- use the df flag
- open the deployment flow
- check that the services/budgets/plans section appears

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5444/
Test PASSed.

**Comment by hatched** [comment]
Thanks @huwshimi this is really coming together nicely :+1: :ok:

**Comment by huwshimi** [comment]
Thanks heaps @hatched :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
