### PR TITLE
Centre the Kubernetes block

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by hatched** [comment]
This looks great @huwshimi thanks for figuring this out!

Full width:
screen shot 2017-05-30 at 8 06 22 pm

Tablet width:
screen shot 2017-05-30 at 8 27 29 pm

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7751/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
