### PR TITLE
Fix display of the subordinate relation count

### LINKED ISSUE #1448: Subordinate handle doesn't display the number of subordinate units
AIUI This should show the number of subordinate units that are deployed elsewhere.
screenshot from 2016-03-07 17 54 37

Is this still a feature @Lucapaulina can you outline exactly what count this is supposed to be showing, Thanks!

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #1448.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add a subordinate service
- notice that the count text is now visible and should read "0"
- add another service and connect it to the subordinate
- the counter should now read "1"

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4618/
Test PASSed.

**Comment by anthonydillon** [comment]
Code :ok: QA works but the number is off center.

juju admin

**Comment by hatched** [comment]
:+1: :ok:
@anthonydillon you might have had a cache issue because there was a style adjusted to position it properly in this PR.

Thanks
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
