### PR TITLE
Group errors

### PR DESCRIPTION
**Pull request by huwshimi**
Group erroring units by type.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add a service
- add 20 more units
- place the units on machines
- deploy
- press ctrl-s to start the simulator
- wait for units to be in error
- navigate to the units error list
- check that the units are grouped by error

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3371/
Test PASSed.

**Comment by jaycee** [comment]
QA notes:

* Added wordpress, added 20 units; committed.
* Auto placed the units on machines, deployed.
* Started simulator.
* Eventually saw 2 errors; in the list one was install, one was config-changed-they were in separate lists.
* As more of those errors accumulated they grouped with the originals.

QA OK and :+1:, this is great @huwshimi, thanks.

**Comment by hatched** [comment]
Watching the UI update while the simulator runs is awesome :)

:+1: QA :ok:
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
