### PR TITLE
Change the logic used to display the signup component.

### PR DESCRIPTION
**Pull request by frankban**
It is displayed only in sandbox mode. Later, we will prevent the page to be displayed if the user has already opted in or out.

### CODE REVIEW

**Comment by frankban** [comment]
QA: ensure that the sign up page is always displayed in sandbox mode and never displayed in gijoe.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6182/
Test PASSed.

**Comment by hatched** [comment]
Thanks @frankban this works great!

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
