### PR TITLE
Fix hover states on inspector icons.

### PR DESCRIPTION
**Pull request by kadams54**
Fixes https://github.com/juju/juju-gui/issues/1238, https://github.com/juju/juju-gui/issues/1239, and https://github.com/juju/juju-gui/issues/1257.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4204/
Test PASSed.

**Comment by kadams54** [comment]
## QA

1. Deploy a service.
2. Open the inspector for that service.
3. Hover over the icons in the inspector (units, configure, and expose).
4. Each icon should be the same color as the rest, in both hover and normal states.
5. No black rectangle artifact should appear on the expose icon.
6. Hover states should work in both Chrome and FF.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4205/
Test FAILed.

**Comment by anthonydillon** [comment]
Code and QA is good in Chrome and FF :+1:

**Comment by hatched** [comment]
It looks like the change version icon is lighter than the rest. Other than that :+1: :ok:

**Comment by kadams54** [comment]
Verified that the icons work in Safari as well.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4210/
Test PASSed.

**Comment by kadams54** [comment]
Thanks all! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4211/
Test FAILed.

**Pull request merged**
