### PR TITLE
Fix deploying local charms with juju 1

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #1928.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA: the GUI charm does not currently work so this can't be QAed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5663/
Test PASSed.

**Comment by frankban** [comment]
The code looks good Huw, thank you! 👍

**Comment by huwshimi** [comment]
Thanks @frankban :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
