### PR TITLE
Change tag color on profile charm items to #666

### LINKED ISSUE #3439: new profile - charms - tag text colour
Tag colour should be #666666

### PR DESCRIPTION
**Pull request by barrymcgee**
Fixes #3439

### CODE REVIEW

**Comment by barrymcgee** [comment]
## QA

- Run jujugui with 'profile' flag
- Navigate to http://192.168.64.2:8042/u/{USERNAME}/#charms
- Verify that tags in each row are #666

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8449/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
