### PR TITLE
Re-enable the deploy button if deploying fails

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3561.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- start a new model
- add an app
- open the deployment flow
- enter a model name that is exactly the same as an existing model
- click deploy
- an error message should appear and the deploy button should become enabled again

**Comment by huwshimi** [comment]
[Re-enable the deploy button if deploying fails](https://trello.com/c/R54lq6yG/362-re-enable-the-deploy-button-if-deploying-fails)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8547/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
