### PR TITLE
Tweak the position of the import and export buttons on mobile

### PR DESCRIPTION
**Pull request by anthonydillon**

### CODE REVIEW

**Comment by anthonydillon** [comment]
## QA
- Open inspector and hit the mobile tool
- Check the import and export buttons are aligned with the deploy button on the bottom left

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5038/
Test PASSed.

**Comment by kadams54** [comment]
:+1: and QA is :ok:. Thanks @anthonydillon!

**Comment by anthonydillon** [comment]
Thanks :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
