### PR TITLE
Rename juju.ubuntu.com references to jujucharms.com.

### PR DESCRIPTION
**Pull request by fabricematrat**

### CODE REVIEW

**Comment by fabricematrat** [comment]
QA: 

Check the changed links are working.

**Comment by frankban** [comment]
:+1: QA ok good catches thanks!

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2611/
Test PASSed.

**Comment by mitechie** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
