### PR TITLE
Update the model name when the user changes it to avoid onblur browser bugs.

### LINKED ISSUE #3336: model name isn't changed unless focus is lost on input field
In the deployment flow, if you update the model name and then immediately click 'deploy' the model name is not updated internally so it will be deployed as 'newmodel'.

As a workaround you have to blur the input field (click outside it) then click the deploy button.

### PR DESCRIPTION
**Pull request by hatched**
Fixes #3336

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Create a model called 'mymodel' and then refresh the GUI.
- Create a new model and then enter the deployment flow
- select your cloud provider
- focus on the model name input and change the name
- now without clicking anywhere else, did the modelname in the header update?
- click the deploy button, did it deploy or complain about it already existing as 'mymodel'

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8269/

**Comment by jaycee** [comment]
QAing now.

**Comment by hatched** [comment]
Thanks all :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
