### PR TITLE
Fix shortcuts panel

### PR DESCRIPTION
**Pull request by huwshimi**
Remove the unused model name label to fix the shortcuts screen layout.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load the gui
- open the shortcuts panel (shift+/)
- check that everything is laid out OK

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5619/
Test PASSed.

**Comment by anthonydillon** [comment]
Thanks @huwshimi good quick fix :+1:

**Comment by hatched** [comment]
Thanks @huwshimi :shipit:

**Pull request merged**
