### PR TITLE
Separate tests for Juju2 API and legacy API clients.

### PR DESCRIPTION
**Pull request by frankban**
Mechanical branch.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5278/
Test PASSed.

**Comment by makyo** [comment]
👍

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
