### PR TITLE
Convert CharmInfo call to the new Juju 2 API.

### PR DESCRIPTION
**Pull request by frankban**
Also fix some leftovers in sandbox mode: handle mega-watcher stream and annotation correctly.

### CODE REVIEW

**Comment by frankban** [comment]
QA: gijoe and sandbox mode, fracking deploy charms, just DO IT!

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5360/
Test PASSed.

**Comment by urosj** [comment]
👍 This one looks good, we're close once we add AddCharm for bundles as well.

**Comment by urosj** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
