### PR TITLE
Entity Details Sticky header fix for bundles with counts

### PR DESCRIPTION
**Pull request by Lukewh**

### CODE REVIEW

**Comment by Lukewh** [comment]
Fixes https://github.com/juju/juju-gui/issues/2944

## QA:

Take a look at the `realtime-syslog-analytics` bundle. When you scroll down you should see the add to canvas button, title and the line starting with author.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7725/

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Comment by Lukewh** [comment]
:shipit:

**Pull request merged**
