### PR TITLE
Change the acl lib implementation

### PR DESCRIPTION
**Pull request by hatched**
After a discussion in a previous repo (https://github.com/juju/juju-gui/pull/1799#issuecomment-229107696) we decided to modify the implementation of the acl library. This implements that change while maintaining the same functionality.

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5333/
Test PASSed.

**Comment by jrwren** [comment]
👍

**Comment by bac** [comment]
:+1:
That is some crazy QA but it works as you described.

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
