### PR TITLE
Move profile section

### PR DESCRIPTION
**Pull request by huwshimi**
Move the account and profile so they can be displayed at the same time as the mid-point. This is the first step towards #1652.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5068/
Test PASSed.

**Comment by makyo** [comment]
👍

**Comment by hatched** [comment]
Thanks! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
