### PR TITLE
Pass the hideDragOverNotification method into the bundle importer to fix failing tests

### PR DESCRIPTION
**Pull request by hatched**
Because the hideDragOverNotification method wasn't passed in it was failing in the tests when it tried to access the app global.

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Drag a bundle yaml onto the canvas, the blue line at the bottom should disappear after drop.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4139/
Test PASSed.

**Comment by huwshimi** [comment]
Looks good. QA OK :+1:

**Comment by hatched** [comment]
Thanks! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
