### PR TITLE
File tree handles bundle urls

### PR DESCRIPTION
**Pull request by anthonydillon**

### CODE REVIEW

**Comment by anthonydillon** [comment]
## QA
 - Visit `?store=wordpress` and check the file urls in the file tree to work
 - Visit `?store=mediawiki-single` and check the file urls in the file tree to work

Fixes: https://github.com/juju/juju-gui/issues/1185

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4129/
Test PASSed.

**Comment by hatched** [comment]
:+1: :ok:
Looks good! Could you update a test for this component to catch this case?

**Comment by anthonydillon** [comment]
Added tests for charm and bundle rendering of the file URL

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4130/
Test FAILed.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
