### PR TITLE
Remove relations from db when destroying a service

### PR DESCRIPTION
**Pull request by makyo**
* Remove relations when destroying a pending service
* Remove relations when destroying committed services

### CODE REVIEW

**Comment by makyo** [comment]
# QA

* Get the GUI up and running in a live env (can be sandbox=true)
* Open console
* deploy two services and relate them without committing
* ensure app.db.relations.size() === 1
* destroy one service
* ensure app.db.relations.size() === 0
* repeat, but this time, commit the services

**Comment by hatched** [comment]
:+1: Will QA

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2568/
Test PASSed.

**Comment by hatched** [comment]
QA OK! 

Followed the qa instructions above and tried it in a real environment.

Thanks for this fix!

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
