### PR TITLE
Display page titles for the store and search results

### LINKED ISSUE #2830: Page title no longer seems to reflect the current state.
Search results show 'undefined' in the title bar for me.

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #2830

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load the gui
- open the store, the window title should be "Store"
- search for a charm, the window title should be "Search results for..."

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7256/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
