### PR TITLE
Add a default model name

### LINKED ISSUE #1224: env breadcrumb missing name in local provider
Bootstrap local provider with latest juju "agent-version": "1.26-alpha4.1" and deploy GUI to it. The env breadcrumb is 
/juju/admin/ 
as there is no name of the controller/model. 

Let's not have an empty string there and in case it is empty by some reason and is not sandbox mode. Just calling it "model" sounds better.

### PR DESCRIPTION
**Pull request by huwshimi**
Set a default model name when one isn't provided. Fixes #1224.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- Bootstrap local provider with latest juju "agent-version": "1.26-alpha4.1" and deploy GUI to it
- you should see "model" for the model name in the header

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4179/
Test PASSed.

**Comment by urosj** [comment]
QA :+1:

**Comment by hatched** [comment]
:+1:  Thanks! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
