### PR TITLE
Update cloud-vanilla-theme to 0.0.24

### PR DESCRIPTION
**Pull request by anthonydillon**
Fixes: https://github.com/juju/juju-gui/issues/1774

### CODE REVIEW

**Comment by anthonydillon** [comment]
## QA
- Run `make clean-all fast-babel run`
- Check the GUI looks ok
- Search for something and see the search filters (Sort by and Series) drop downs are styled

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5267/
Test PASSed.

**Comment by huwshimi** [comment]
Nice one @anthonydillon QA OK :+1:

**Comment by hatched** [comment]
Thanks @anthonydillon !
:+1: 
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
