### PR TITLE
Fix unit removal update

### PR DESCRIPTION
**Pull request by huwshimi**
Fixed viewing unit details when the unit gets removed.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add a service
- place the unit and deploy
- navigate to the unit details
- in your console run `app.env.remove_units(['wordpress/0'], null, {immediate: true})` using the name of your service
- no errors should appear in your console
- click the details header to go back to the unit list
- it should navigate back with no errors in your console

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3623/
Test PASSed.

**Comment by fabricematrat** [comment]
Code :ok:

**Comment by hatched** [comment]
QA Issue:

Deploy and autoplace wordpress with 6 units 
Turn on the simulator
When a unit goes into a pending or error status, enter that unit list and click on the unit
Repeatedly switch 'back' and 'into' that unit 
That unit will eventually move into a different state.
At that point clicking 'back' from the unit details will do nothing. You aren't able to navigate to another service either.

**Comment by huwshimi** [comment]
@hatched I have updated this to navigate back to the unit list if the unit is removed, this should have fixed your issue.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3633/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3634/
Test PASSed.

**Comment by hatched** [comment]
Nice thanks! :+1: QA :ok:

**Comment by huwshimi** [comment]
Thanks @fabricematrat and @hatched! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/1232

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
