### PR TITLE
Update selecting creds

### PR DESCRIPTION
**Pull request by huwshimi**
In this branch:
- if there is only one cloud then automatically select it
- don't set the region/cloud/creds if the model is disconnected
- credential selection should always be able to be changed/added

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add a service
- open the deployment flow
- the cloud should be selected
- the credentials select box should be enabled (the region should be disabled)
- set `modelCommitted={false}` in app.js
- reload
- add a service
- open the deployment flow
- there deployment flow should open and there should be no errors in your console about map and null

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5818/
Test PASSed.

**Comment by hatched** [comment]
Thanks @huwshimi 

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
