### PR TITLE
Fix sticky header

### PR DESCRIPTION
**Pull request by huwshimi**
Fixed the sticky header when you navigate to a charm after scrolling the search results.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- search for a charm
- scroll down the search results
- click on a charm
- the charm header should not be sticky and scrolling down should make the header sticky when the header disappears from screen

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3915/
Test PASSed.

**Comment by hatched** [comment]
:+1: :ok: :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
