### PR TITLE
Add unit status lists

### PR DESCRIPTION
**Pull request by huwshimi**
Added filtered lists of units by status to the inspector.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3162/
Test PASSed.

**Comment by huwshimi** [comment]
QA:
- add a service (e.g. `app.get('charmstore').getEntity('precise/python-django', function(entity) { app.deployService(entity[0]); });`)
- add 20 more units
- commit
- press ctrl+s to start the simulator
- click on the service and you should see items for the different unit statuses e.g. Pending (5)
- click on a status
- you should get a list of the units with that status
- click on a unit
- the unit should have the correct status header
- click the header to go back
- you should be taken to the correct unit status list
- click back to get to the service overview
- click Units
- click a unit to get the unit details
- click the header to go back
- you should be taken back to the all units list

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3174/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3175/
Test PASSed.

**Comment by hatched** [comment]
:+1: QA :ok: 

Thanks this looks great!

**Comment by kadams54** [comment]
Nicely done. :+1:

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
