### PR TITLE
Update the form for adding Azure credentials

### LINKED ISSUE #2333: Adding creds for Azure is not supported
cannot update credentials: updating cloud credentials: validating cloud credentials: credential "azure/uros-jovanovic@external/azure-maybe-test" with auth-type "userpass" is not supported (expected one of ["interactive" "service-principal-secret"])

auth-type: service-principal-secret
application-id: 
application-password: 
subscription-id: 

These are the fields needed. 

The instructions how to get these are wrong as well. Best way to do it is with CLI and copy/paste the values. We should redirect the user to get the creds using CLI. The link in the GUI is useless.

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #2333.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- deploy the Gui on azure
- add an app
- click deploy
- click add credentials
- fill in the form (I used the details out of my credentials.yaml)
- click add
- the credentials should get added

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6602/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6603/

**Comment by urosj** [comment]
Sorry, QA 👎 

1)
I could not get any machine up, all of them ended up in "down" state. There's an error for 'length' in parse data in JS console every time, but not sure it's related. 
Machines in down state happened to any user deploying GUI, whether admin or @external. Both of them could use creds in CLI and got machine up and running.

2)
Instructions are useless. We should redirect them to the azure creds page for juju and then instruct them to get the information from the credentials.yaml file and copy/paste them to this form.

**Comment by frankban** [comment]
This has been merged elsewhere, and the QA issues will be addressed. This was a good step in the right direction to fix the bug, and sorry for having duplicated the effort here.
Thank you!

**Pull request closed without merging**
