### PR TITLE
Workaround for allowing committing to newly created models.

### PR DESCRIPTION
**Pull request by frankban**
Starting from anonymous user and logging in as part of the deployment flow.

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6834/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6835/

**Comment by hatched** [comment]
Thanks for iterating on this with me @frankban 

QA OK!

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
