### PR TITLE
Update the ECS when app names change

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3328.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add an app
- open the inspector config panel
- change the app name and some config settings
- add another app and relate it to the first
- open the deployment flow
- open the changelog
- check that all references to the first app use the updated name

**Comment by huwshimi** [comment]
[Fix opening DF when app names have changed](https://trello.com/c/ditkxBlr/28-fix-opening-df-when-app-names-have-changed)

**Comment by jujugui** [comment]
Build finished.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8265/

**Comment by hatched** [comment]
Thanks for this @huwshimi 

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
