### PR TITLE
Update more tables to use new Vanilla

### LINKED ISSUE #3853: Deployment flow machines table is mis-styled
To reproduce, add the Elasticsearch and Kibana bundle then open the deployment flow...

screen shot 2018-10-26 at 11 01 56 am

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #3853.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load the expert flow
- the plan table should display using the new Vanilla styles (not the orange header ones)
- reload the GUI and add an app
- open the deployment flow and open the changes section
- the machines section should display using the new tables

**Comment by huwshimi** [comment]
[Fix more GUI table styles](https://trello.com/c/aawAITDE/1037-fix-more-gui-table-styles)

**Comment by barrymcgee** [comment]
@huwshimi Is it correct to say this salmon header should not appear anywhere?

https://d3vv6lp55qjaqc.cloudfront.net/items/0o1g2R291j0p0H46070P/Screenshot%202018-10-30%20at%2012.36.12.png?X-CloudApp-Visitor-Id=a2ee0f06bc5ac9b8bf420723ade08813&v=dd861e45

**Comment by hatched** [comment]
@barrymcgee just to clarify, do you mean to delete the .v1 styles in that file or to move them outside of it?

**Comment by barrymcgee** [comment]
@hatched Move them outside of it and remove the `.v1 & { ... }` wrapper.

**Comment by huwshimi** [comment]
@barrymcgee am I right in thinking that when we eventually move everything to the latest vanilla that everything inside that `.v1 & {...}` wrapper can be removed? If so maybe we should leave things as they are now so we know what styles are related to the overrides.

**Comment by barrymcgee** [comment]
@huwshimi No, not everything inside it, just the wrapper itself as it's simply as a namespace while we concurrently load old and new Vanilla.

Ok, leave it for now. 👍🏻

**Pull request merged**
