### PR TITLE
Profile nav updates

### PR DESCRIPTION
**Pull request by hatched**
Update the user profile page interactions to appear as a level above the model. The user profile is supposed to appear like a page before viewing a model. As such the close button has been removed, the styling as been updated and you can now navigate to the profile from clicking the username in the header breadcrumb

### CODE REVIEW

**Comment by hatched** [comment]
Fixing merge test failure from https://github.com/juju/juju-gui/pull/1399

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4542/
Test FAILed.

**Pull request merged**
