### PR TITLE
Improve search interaction

### PR DESCRIPTION
**Pull request by anthonydillon**
User experience improvements to the interactions with the active and inactive search field.

### CODE REVIEW

**Comment by anthonydillon** [comment]
## QA
- Open in sandbox
- Focus on the search field and check the that the design matches [1]
- Open in live env and see that the Logout sits next to the search nicely when open.
- Open inspector and show the `MAAS UI` link above the search field and check the style matches the Logout link.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5947/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5948/
Test PASSed.

**Comment by hatched** [comment]
When deployed into a real model where you have the logout button focusing on the input animates the input to the right in a stepped motion. Maybe it shouldn't animate at all? Or the animation should be much smoother.

**Comment by anthonydillon** [comment]
There should be no animation at all. That is the problem in the first place. I have removed the movement.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5950/
Test PASSed.

**Comment by hatched** [comment]
Thanks @anthonydillon Looks great!

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/1945

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
