### PR TITLE
Correctly style all select boxes

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes https://github.com/juju/juju-gui/issues/1141

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4011/
Test FAILed.

**Comment by huwshimi** [comment]
QA:
- do a search
- check that the filter select boxes are styled as they were
- open the machine view
- add a machine
- add a container
- check that the container type selector is styled the same as the search filters

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4012/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4014/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4032/
Test PASSed.

**Comment by bac** [comment]
:+1: will QA now

**Comment by frankban** [comment]
:+1: thank you!

**Comment by bac** [comment]
QA-OK

**Comment by bac** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
