### PR TITLE
Add store button tooltips

### LINKED ISSUE #3062: no hover over feedback for the add to model buttons (or the username links)
On hover there should be some textual hover feedback on "add to current model" and for the username maybe something like "See other items by *containers*"

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #3062.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- search for a charm
- hovering the authors should show a tooltip
- click on a charm
- hovering the add to model button should show a tooltip
- connect to a deployed model
- open a charm in the store
- hovering the add to model button should show a tooltip

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7913/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7914/

**Comment by hatched** [comment]
QA Note

After searching for the charms the (+) has a tooltip which says "Group"

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7919/

**Comment by huwshimi** [comment]
Thanks @hatched :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
