### PR TITLE
Match the Show changelog button with the design

### PR DESCRIPTION
**Pull request by anthonydillon**

### CODE REVIEW

**Comment by anthonydillon** [comment]
## QA
- Add an application
- Enter deployment flow
- Scroll down to the "Applications to be deployed" section
- Check the Show changelog button matches the design [1]

[1] https://raw.githubusercontent.com/CanonicalLtd/juju-design/master/Deployment%20flow/Standard/5.png?token=ABWRnkUJu-hMxSNsVU1ypPuQd_pYpQVfks5YR9fywA%3D%3D
_Apart from the white background as that is not how the button component was build. We don't want to much bespoke styling overriding component styles. Therefore that will need to be discussed and may result in an update to our button component_

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6300/
Test PASSed.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
