### PR TITLE
Change version to 0.0.2 to propagate the baseUrl fix

### PR DESCRIPTION
**Pull request by bac**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2986/
Test PASSed.

**Comment by jaycee** [comment]
:+1:

**Comment by bac** [comment]
thanks @jaycee :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
