### PR TITLE
Test updates

### PR DESCRIPTION
**Pull request by hatched**

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

If CI passes then it's ok.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4311/
Test FAILed.

**Comment by hatched** [comment]
Spurious failure ran properly: http://ci.jujugui.org:8080/job/juju-gui/4312/

**Comment by huwshimi** [comment]
Big fat :+1:

**Comment by hatched** [comment]
:D thanks! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
