### PR TITLE
Move jujulib into the root tree

### PR DESCRIPTION
**Pull request by hatched**
This branch simply moves the jujulib into the root tree of the GUI so that it can be transpiled using babel. It also moves the reconnecting websocket lib into jujulib.

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Deploy the GUI, everything should work as usual.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5567/
Test PASSed.

**Comment by hatched** [comment]
Thanks @bac :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
