### PR TITLE
Fix empty post-deployment being displayed.

### PR DESCRIPTION
**Pull request by Lukewh**
Fixes https://github.com/juju/juju-gui/issues/3251

### CODE REVIEW

**Comment by Lukewh** [comment]
## QA

Deploy any charm/ bundle you shouldn't get the panel as shown in https://github.com/juju/juju-gui/issues/3251.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8156/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8157/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8158/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8159/

**Comment by hatched** [comment]
Thanks @Lukewh 

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
