### PR TITLE
Add ability to destroy services and units in Juju 2.0.

### PR DESCRIPTION
**Pull request by frankban**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4470/
Test PASSed.

**Comment by urosj** [comment]
LGTM

**Comment by frankban** [comment]
Thanks for the review Uros! I'll QA this later together with the annotations branch.
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
