### PR TITLE
WSGI app: remove API path leftovers.

### PR DESCRIPTION
**Pull request by frankban**

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5004/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5005/
Test PASSed.

**Comment by bac** [comment]
charmstore_api_path and jem_api_path are still in development.ini

**Comment by bac** [comment]
:+1: with the above change.

**Comment by bac** [comment]
@frankban We'll need to make corresponding changes to juju-gui-charm which currently has:

```
    wsgi_settings = {
        'jujugui.apiAddress': options.apiurl,
        'jujugui.combine': not options.jujuguidebug,
        'jujugui.gisf': options.gisf,
        'jujugui.GTM_enabled': options.gtm,
        'jujugui.gzip': options.gzip,
        'jujugui.insecure': options.insecure,
        'jujugui.interactive_login': options.interactivelogin,
        'jujugui.jem_url': options.jemlocation,
        'jujugui.jem_api_path': options.jemversion,
        'jujugui.charmstore_url': options.charmstoreurl,
        'jujugui.charmstore_api_path': options.charmstoreversion,
        'jujugui.jujuCoreVersion': options.jujuversion,
        'jujugui.raw': options.jujuguidebug,
        'jujugui.sandbox': options.sandbox,
        'jujugui.socketTemplate': WEBSOCKET_SOURCE_TEMPLATE,
        'jujugui.uuid': options.uuid,
    }
```

**Comment by bac** [comment]
I'll do QA but it is blocked until the charm is updated.

**Comment by frankban** [comment]
Thanks for the review Brad, thanks for spotting the leftovers in development.ini.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5007/
Test PASSed.

**Comment by frankban** [comment]
Ready to be QAed with https://github.com/juju/juju-gui-charm/pull/63

**Comment by bac** [comment]
See QA comments on the related PR.

**Comment by frankban** [comment]
Thanks for the review and QA Brad.
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
