### PR TITLE
Remove model destroying

### PR DESCRIPTION
**Pull request by huwshimi**
Remove the ability to destroy models so we can make a release without functionality that doesn't fully work.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load the profile
- click on a model
- check that there is no 'Destroy model' button

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5179/
Test PASSed.

**Comment by kadams54** [comment]
QA is :ok: and code is :+1: - thanks @huwshimi!

**Comment by kadams54** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
