### PR TITLE
Add commit flow

### PR DESCRIPTION
**Pull request by huwshimi**
After there has been a deploy we should display the commit flow when the user deploys.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add a machine or a service
- click "Deploy changes"
- work through the deploy flow and deploy
- the "Deploy changes" button should now read "Commit changes"
- add a machine or a service
- click "Commit changes"
- you should now see the summary screen, there should be no steps in the header, there should be no "Change cloud" button, there should be a "Clear all changes" link next to the heading, and the green "Deploy" button should now read "Commit"

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4737/
Test PASSed.

**Comment by hatched** [comment]
:+1: :ok:

Thanks!

**Comment by makyo** [comment]
:+1:

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
