### PR TITLE
Removed the features tab and related code from the charm and bundles details pages

### PR DESCRIPTION
**Pull request by hatched**
This information is no longer relevant with the apiv4 endpoint so it's being removed.

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

View the charm and bundle details panes and make sure that you can still navigate around them as expected and that the `features` tab doesn't exist.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2406/
Test PASSed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2407/
Test FAILed.

**Comment by huwshimi** [comment]
Looks good @hatched, thanks for removing the CSS as well! :+1: 

NO QA as I'm getting merge conflicts with develop.

**Comment by makyo** [comment]
:+1: QA okay.  No features, no errors in the console.

**Comment by hatched** [comment]
Thanks guys! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
