### PR TITLE
Account page: make the add credentials feature work.

### PR DESCRIPTION
**Pull request by frankban**

### CODE REVIEW

**Comment by frankban** [comment]
QA:
- add/remove credentials from the account page and from the deployment flow;
- ensure all clouds are displayed correctly when adding credentials from the account page and when opening the deployment flow for creating a new model.

**Comment by Lukewh** [comment]
QA OK @frankban

**Comment by frankban** [comment]
Thank you for the review Luke!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
