### PR TITLE
Split jujulib.

### PR DESCRIPTION
**Pull request by frankban**
Also rename jem to jimm.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5225/
Test PASSed.

**Comment by hatched** [comment]
👍 Thanks for this refactor

**Comment by makyo** [comment]
:+1:

**Comment by frankban** [comment]
Thanks for the reviews!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
