### PR TITLE
Fix modal shadow on the canvas

### LINKED ISSUE #2840: Faded horizontal line on GUI
On develop:
screen shot 2017-05-03 at 10 38 57 am

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #2840.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load the canvas
- there shouldn't be a strange line as per the screenshot in #2840.
- open the keyboard shortcuts and gui settings
- they should appear correctly

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7264/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
