### PR TITLE
Replace YUI router with native code

### PR DESCRIPTION
**Pull request by anthonydillon**
Removed the YUI routes and replaced them with some basic parsing and routing.

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6059/
Test FAILed.

**Comment by anthonydillon** [comment]
Tests failing as the functionality is not complete. Also would don't want to add a lot of new tests to the old test suite. 

## QA
- Open the store
- Search for something
- Navigate to a details page
- Add application
- Check inspector works as before
- Check machine view works

Searching for tags, type, sort, series, provides, requires and owner is to come in a follow up branch with an improvement to the `parseURL`.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6080/
Test FAILed.

**Comment by huwshimi** [comment]
It looks like this needs a rebase!

**Comment by hatched** [comment]
I'll take over this branch and integrate it with the new state object. Closing this PR.

**Pull request closed without merging**
