### PR TITLE
Update new profile charm list to table component

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- use the profile flag and view your profile
- you should be able to see a list of charms

**Comment by huwshimi** [comment]
[Update new profile charm list](https://trello.com/c/RWx2oRJD/109-update-new-profile-charm-list)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8331/

**Comment by frankban** [comment]
QA is ok, I can see the list of charms.

**Comment by huwshimi** [comment]
Thanks @frankban :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
