### PR TITLE
Update state to support the new querystring components

### PR DESCRIPTION
**Pull request by hatched**
The new query string based store urls required updates to the state system to function correctly.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3095/
Test PASSed.

**Comment by hatched** [comment]
#### To QA

This requires the use of the `react` flag.
- Click to make a search. The input should appear and the url should change to have `?midpoint=` appended to it.
- Click the X to close the midpoint and the url should update accordingly.
- Click to make a search and search for something. The url should change to `?search=<yoursearch>`
- Click the X to close the search results and the url should update accordingly.
- Visit the gui `?midpoint` to make sure the midpoint shows up and then works properly
- Visit the gui `?search=apache` to make sure the search shows up and then works properly
- Visit the gui with the `?midpoint` and then click on a charm. The url should update to `?store=<charmid>`

**Comment by huwshimi** [comment]
Brilliant, thanks @hatched! QA OK :+1: :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
