### PR TITLE
Clean up credential adding

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add an app
- open the deployment flow
- select a cloud
- select add credential
- fill out the form and submit
- the credential should get added

**Comment by huwshimi** [comment]
[Clean up add credential component](https://trello.com/c/PDP38ESy/254-clean-up-add-credential-component)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8450/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8451/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8452/

**Comment by huwshimi** [comment]
@hatched thanks, yeah I just did this cleanup first so I'm not landing too much stuff at once. :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
