### PR TITLE
Add a drop-shadow to the terminal container

### LINKED ISSUE #3416: launching the juju shell hides and breaks the styling of the save changes button in application config
You can no longer find/use the save changes button even if you close the shell and have to reload the page to be able to change config.

### PR DESCRIPTION
**Pull request by hatched**
Fixes #3416

### CODE REVIEW

**Comment by hatched** [comment]
screen shot 2018-02-07 at 10 38 19 am

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8483/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
