### PR TITLE
Remove pip internals from setup.py

### LINKED ISSUE #2188: setup.py uses unsafe pip internal api...and breaks
As described here: https://github.com/pypa/pip/issues/3687

We do:
```
install_requires = [str(req.req) for req in requirements]
```

That works fine in pip 8.x but breaks in pip 9.x.

### PR DESCRIPTION
**Pull request by bac**
Fixes #2188

### CODE REVIEW

**Comment by bac** [comment]
# QA
* `make dist`, Then with pip 8 and pip 9:
* `pip install dist/jujugui...`

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6165/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6166/
Test PASSed.

**Comment by bac** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
