### PR TITLE
Lightly style dropdown menus

### PR DESCRIPTION
**Pull request by anthonydillon**

### CODE REVIEW

**Comment by anthonydillon** [comment]
## QA
- Search for a charm or bundle
- See that the sort by and series dropdowns a tthe top left of the screen has just a grey border around it (webkit only)
- Check that the dropdown still functions

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3888/
Test PASSed.

**Comment by huwshimi** [comment]
Hmm... I noticed in the mockups these have a chevron in them (also rounded corners and a shadow), without the chevron it's not super obvious that these are dropdowns.
chrome

Also this change makes them pretty ugly in firefox:

firefox

**Comment by anthonydillon** [comment]
Thanks @huwshimi will look into matching the styles and adding a chevron

**Comment by bac** [comment]
In Chrome on OS X I see rounded corners:

screen shot 2015-12-15 at 9 18 20

Firefox looks like Huw's screenshot.  

Safari looks like Chrome, rounded corners with no chevron.

Your QA instructions say the dropdown boxes should be in the top left of the screen.  Mine are in the right:

screen shot 2015-12-15 at 9 22 16

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3896/
Test FAILed.

**Comment by anthonydillon** [comment]
@huwshimi @bac Thanks, add some more styling to cover the issues spotted.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3897/
Test PASSed.

**Comment by huwshimi** [comment]
Looks awesome @anthonydillon , thanks for getting that all looking good. :+1:!

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
