### PR TITLE
Add default value to region list.

### LINKED ISSUE #2122: Default option in region is misleading, should be a intelligent "default"
Instead of submitting an empty string (and giving the impression that the first option listed will be chosen) we need to have a "Default" option in the list. When that option is chosen, there should be some logic to select a region based on the region for the controller.

### PR DESCRIPTION
**Pull request by kadams54**
Fixes #2122.

### CODE REVIEW

**Comment by kadams54** [comment]
## QA

In a GUI connected to a real controller...

1. Create a new model and deploy something.
2. In the deployment flow, verify that the "Default" option is first & selected. 
3. Deploy.
4. In your cloud provider's console, verify that a machine's been added in the same region as your controller machine.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5991/
Test PASSed.

**Comment by frankban** [comment]
Looks good 👍

**Comment by hatched** [comment]
:ok: 

Thanks @kadams54 I used the Default option and it deployed to the default, I changed the region and it deployed to that region.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
