### PR TITLE
Remove charmbrowser squircles and fix search state

### LINKED ISSUE #1756: There are squircles in the charmbrowser
They should probably be updated to be circles to match the rest of the UI. Look in the mid-point, search results, charm details etc.

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #1756.

### CODE REVIEW

**Comment by jujugui** [comment]
Build finished.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6550/

**Comment by huwshimi** [comment]
QA:
- open a charm details page, the big icon should be a circle
- do a search
- you should be taken to the search results page and the icons should all be circles

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6349/
Test PASSed.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
