### PR TITLE
Add no-undef eslint rule

### PR DESCRIPTION
**Pull request by hatched**
This rule was missing and there were issues with undefined variables.

### CODE REVIEW

**Comment by hatched** [comment]
No QA necessary, if the tests and lint pass then it's O K

**Comment by hatched** [comment]
Thanks @huwshimi :shipit: as trivial

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5692/
Test PASSed.

**Pull request merged**
