### PR TITLE
Display apps with cross model relations

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6589/

**Comment by huwshimi** [comment]
QA:
- update your local juju to the latest develop
- run `export JUJU_DEV_FEATURE_FLAGS=cross-model`
- bootstrap a controller
- then:
```
juju add-model model1
juju deploy mysql
juju add-model model2
juju deploy wordpress
juju expose wordpress
juju relate wordpress model1.mysql
```
- open the gui and switch to model2
- you should see two apps on the canvas with a relation

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6590/

**Comment by hatched** [comment]
Because we are so close to merging this to develop and creating a 2.3 I'm concerned about landing this without proper tests and qa as this modifies code which is a high traffic path.

**Comment by frankban** [comment]
Ok, I see Jeff's point. I'll push this on a a separate branch in the juju repository, so that it's still simple to create releases for demoing cmr.

**Comment by frankban** [comment]
Ok so I pushed this to the juju repository as "cmr".

**Comment by frankban** [comment]
To be clear, Huw, when the follow-up is done for adding tests, please propose that against cmr.

**Comment by bac** [comment]
I followed the QA instructions and it worked pretty well.  In both model1 and model2 the application local to that model was shown but the other one was just an empty circle.  The counts both showed 1 application.

screen shot 2017-01-16 at 14 02 04
screen shot 2017-01-16 at 14 02 22

**Comment by hatched** [comment]
Thanks for the qa @bac this is known and awaiting fixes in Juju before the icon can be properly shown.

**Comment by bac** [comment]
qa-ok per @hatched's explanation.

**Comment by huwshimi** [comment]
The tests are in this branch: #2374.

**Pull request closed without merging**
