### PR TITLE
Cleanup from socket template branch

### PR DESCRIPTION
**Pull request by jaycee**

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4022/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4023/
Test PASSed.

**Comment by jaycee** [comment]
QA: 

Ensure sandbox mode works.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4024/
Test PASSed.

**Comment by makyo** [comment]
:+1: QA ok

**Comment by kadams54** [comment]
:+1: QA is also OK for me. Thanks!

**Comment by jaycee** [comment]
:shipit:

Thanks all!

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
