### PR TITLE
Point Install Juju button to the main get started page

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load the gui
- check that the Install Juju button takes you to "https://jujucharms.com/get-started"

**Comment by urosj** [comment]
:+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4245/
Test PASSed.

**Comment by bac** [comment]
:+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4246/
Test PASSed.

**Comment by huwshimi** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by Lucapaulina** [comment]
Is this the white "Install Juju" button that sits in the bottom left of the
GUI? If so, then it should point to
https://jujucharms.com/docs/stable/getting-started.

**Pull request merged**
