### PR TITLE
Align side nav to match spec

### PR DESCRIPTION
**Pull request by barrymcgee**

### CODE REVIEW

**Comment by barrymcgee** [comment]
Run jujugui with 'profile' flag - guiproxy -env prod --flags profile
Navigate to models table on your profile - http://192.168.64.3:8042/u/$USERNAME/#models
Cross-ref with the design spec - https://github.com/CanonicalLtd/juju-design/blob/master/Profile/10-Navigation-specs.png

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8422/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
