### PR TITLE
Change notification close

### LINKED ISSUE #1552: Unable to copy text from error notifications
When you get an error in the GUI it opens a notification that persists until you close it. If you try to copy the message to, say, file a bug it disappears before you're able to do so. The click to dismiss should probably be updated so that only the X can close the error notifications.

### PR DESCRIPTION
**Pull request by huwshimi**
Only close the notifications when the close button is clicked. Fixes #1552.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load the GUI
- in your console run `app.db.notifications.add({title: 'catastrophe', message: 'Catastrophe, apostrophe, epistrophe!', level: 'error'});`
- click the notification
- it should not close
- click the x
- it should now close

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5065/
Test PASSed.

**Comment by hatched** [comment]
Thanks! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
