### PR TITLE
Use eslint cache to speed up repeated lintings by only checking files that have changed

### PR DESCRIPTION
**Pull request by hatched**

### CODE REVIEW

**Comment by hatched** [comment]
No QA necessary, CI should pass successfully

```
: time make lint-js
node_modules/.bin/eslint --rulesdir eslint-rules/ jujugui/static/gui/src

real    0m11.802s
user    0m12.240s
sys     0m0.319s

: time make lint-js
node_modules/.bin/eslint --cache --rulesdir eslint-rules/ jujugui/static/gui/src

real    0m1.040s
user    0m1.003s
sys     0m0.112s
```

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7744/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
