### PR TITLE
Correctly pluralise the canvas switcher

### LINKED ISSUE #1759: Canvas switcher not properly pluralised
screen shot 2016-06-14 at 9 33 47 am

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #1759.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add some machines and applications, the machines/applications switcher should pluralise correctly

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5336/
Test PASSed.

**Comment by anthonydillon** [comment]
Thanks Huw :+1:

**Comment by hatched** [comment]
:+1: Thanks @huwshimi

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
