### PR TITLE
Update juju logo

### PR DESCRIPTION
**Pull request by anthonydillon**

### CODE REVIEW

**Comment by anthonydillon** [comment]
## QA
- Check the logo in the loading screen and header look ok

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5525/
Test PASSed.

**Comment by hatched** [comment]
I think you should also add these updates to the index.html.go

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5543/
Test PASSed.

**Comment by anthonydillon** [comment]
Added it to index.html.go too. Out of curiosity why do we have two @hatched

**Comment by hatched** [comment]
@anthonydillon thanks, the `index.go` template is for the GUI embedded in Juju and the `mako` is for the  GUI when it's served by pyramid (Charm, Sandbox).

**Comment by anthonydillon** [comment]
@hatched can I have a +1?

**Comment by kadams54** [comment]
:+1: from me as well.

**Comment by anthonydillon** [comment]
Thanks :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
