### PR TITLE
Don't set an empty htmlFor property in Firefox so there aren't errors.

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3483.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load the GUI in Firefox
- add a charm
- open the unit list in the inspector
- hover over the unit in the list
- you should not get an error in your console
- click on the unit
- you should not get an error in your console

**Comment by huwshimi** [comment]
[Fix firefox inspector errors](https://trello.com/c/UjWkm8Dm/306-fix-firefox-inspector-errors)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8495/

**Comment by mitechie** [comment]
QA ok, no error in the console. :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
