### PR TITLE
Allow for three digit unit counts.

### PR DESCRIPTION
**Pull request by kadams54**
Fixes https://github.com/juju/juju-gui/issues/1565.

### CODE REVIEW

**Comment by kadams54** [comment]
## QA

Deploy a service. Scale up to several hundred units in the inspector. Verify that the unit count does not wrap.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4874/
Test PASSed.

**Comment by hatched** [comment]
:+1:

**Comment by hatched** [comment]
QA OK Thanks!
:shipit: shipping as trivial

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
