### PR TITLE
Budget methods

### PR DESCRIPTION
**Pull request by huwshimi**
Add methods for interacting with budgets to jujulib.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- connect to guimaas
- run `app.plans.createProfile('[your username here]', '99', 'my-budget', '99', (error, data) => {console.log(error, data)})`
- it should create a profile
- run `app.plans.createBudget('my-budget', '33', (error, data) => {console.log(error, data)})`
- it should create a budget
- run `app.plans.listBudgets((error, data) => {console.log(error, data)})`
- you should get your budgets

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5402/
Test PASSed.

**Comment by hatched** [comment]
Thanks @huwshimi This looks good! :+1:

**Comment by kadams54** [comment]
QA is :ok: and :+1: on the code. Thanks!

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
