### PR TITLE
Post deployment panel shapes

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
[Post deployment panel shapes](https://trello.com/c/SpnqDSSE/749-post-deployment-panel-shapes)

**Comment by huwshimi** [comment]
QA:
- open the post deployment panel (on prod run `JujuGUI.state.changeState({postDeploymentPanel: {show: true, entityId: 'cs:bundle/canonical-kubernetes-206'}});`)
- there should be no console errors

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8791/

**Comment by huwshimi** [comment]
This won't pass CI until #3715 lands.

**Comment by hatched** [comment]
@huwshimi looks like it's got some conflicts now.

**Comment by huwshimi** [comment]
As discussed :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge/2880

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8796/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8893/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
