### PR TITLE
Handle zero templates

### LINKED ISSUE #1609: Gracefully fail when no templates are found
If you have no available templates then the `listTemplates` command throws an error when it tries to iterate through them here: https://github.com/juju/juju-gui/blob/develop/jujugui/static/gui/src/app/assets/javascripts/jujulib/juju.js#L285

`response.templates` can be null if you do not have any templates available to you.

`combo?app/store/env/bakery.js&app/assets/javascripts/jujulib/juju.js:868 Uncaught TypeError: Cannot read property 'map' of null`

### PR DESCRIPTION
**Pull request by huwshimi**
Fix breakage when no templates are returned. Fixes #1609.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load the templates when none exist (or fake it)
- check the console that there are no errors

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5013/
Test PASSed.

**Comment by hatched** [comment]
:shipit: Thanks @huwshimi

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
