### PR TITLE
Fixed empty inputs in Firefox.

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- open the GUI in Firefox
- add a service
- open the config
- find a text input containing no text
- check that the input's height is OK

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3637/
Test PASSed.

**Comment by hatched** [comment]
:+1: QA :ok:

**Comment by hatched** [comment]
:shipit: Shipping as trivial

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
