### PR TITLE
So many ux qa updates

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA: See the attached bugs.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3832/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3833/
Test PASSed.

**Comment by anthonydillon** [comment]
Really nice @huwshimi code and QA good with a few queries below:
- When clicking on the owner in search results it searches for charms and bundles which I find it weird. I expected to go to that users profile. 
- Bundle entity pages do not show a series so have a trailing grey mid-dot in the list
juju admin

Good to land with follow ups if the points are valid.

**Comment by anthonydillon** [comment]
:+1:

**Comment by hatched** [comment]
QA Issue:

When dragging the canvas with the inspector open it also closes the inspector.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3844/
Test PASSed.

**Comment by hatched** [comment]
:+1: QA :ok: Looks awesome!

**Comment by huwshimi** [comment]
@anthonydillon I've fixed the series bullet, we don't have profiles (yet?) so I've left it for now until we decide what happens with profiles.

Thanks for the reviews :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
