### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by makyo**
* Typo fix on using the wrong index when generating text.
* Update series in fakebackend from precise to trusty.

### CODE REVIEW

**Comment by hatched** [comment]
:+1: QA OK! Thanks for these fixes

**Comment by makyo** [comment]
Thanks!  Trivial :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2503/
Test FAILed.

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/874

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
