### PR TITLE
Move notification list up in z-index.

### PR DESCRIPTION
**Pull request by kadams54**
Fixes https://github.com/juju/juju-gui/issues/1613.

### CODE REVIEW

**Comment by kadams54** [comment]
## QA

This can be done locally, without any modifications to `development.ini`.

1. `make run`
2. Open the GUI.
3. In your console, run `app.db.notification.add({message: 'Hello!'})`. You should see a notification message appear that says "Hello!".
4. Nav to the user profile.
5. Re-run `app.db.notification.add({message: 'Hello!'})`. You should see the same notification appear.

**Comment by kadams54** [comment]
The only question I have about this change is whether I moved the notification-list up high enough in the z-index list. It seems to me that it should be pretty high, maybe just under `full-screen-mask`.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5029/
Test PASSed.

**Comment by anthonydillon** [comment]
Code and QA :+1:

**Comment by hatched** [comment]
Thanks :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/1662

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
