### PR TITLE
Add options parsing for charmstore api v4

### PR DESCRIPTION
**Pull request by hatched**
Fix for bug: https://bugs.launchpad.net/juju-gui/+bug/1416469
 
When the user drag & dropped a charm from the charmbrowser it wasn't requesting and storing any charm configuration options so when trying to export it would fail as the options object was empty.

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2356/
Test FAILed.

**Comment by huwshimi** [comment]
Looks good, thanks Jeff. QA OK :+1:

**Comment by hatched** [comment]
Thanks @huwshimi 

After a few tries CI passed: http://ci.jujugui.org:8080/job/juju-gui/2358/

**Comment by frankban** [comment]
:+1: thank you!

**Comment by hatched** [comment]
Thanks for the reviews! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/821

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
