### PR TITLE
WIP: Re-add centering on load.

### PR DESCRIPTION
**Pull request by kadams54**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4151/
Test PASSed.

**Comment by hatched** [comment]
When comparing the output of this to my implementation #1209, this one appeared to not center on the actual center point whereas mine did. After investigating it turned out to be a combination of things:

use `this.panToCenter();` instead of `this.findCentroid();`
wrap it in a setTimeout()

https://github.com/juju/juju-gui/pull/1209/files#diff-790b1c2888009d1df84ab1f76e621d22R69

**Comment by hatched** [comment]
The `centeredOnce` needs to be reset on switching Models

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4170/
Test FAILed.

**Pull request closed without merging**
