### PR TITLE
Update sysdeps target to selectively use sudo where required.

### PR DESCRIPTION
**Pull request by bac**

### CODE REVIEW

**Comment by mitechie** [comment]
:+1: ty for the update

My only concern is that someone updates https://github.com/juju/juju-gui/blob/develop/install-sysdeps.sh to do something that should not be sudo'd. I know it's a bigger diff, but I think I'd prefer the sudo in the script vs in the make call.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2390/
Test PASSed.

**Comment by bac** [comment]
Thanks @mitechie . I took your suggestion. It is how I originally did it but then rejected it as the script is about installing sysdeps so I figured the whole thing would need sudo. But being explicit is ok too.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2398/
Test PASSed.

**Comment by makyo** [comment]
:+1: QA okay on a fresh LXC

**Comment by bac** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
