### PR TITLE
Fix inspector header height

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3493.

### CODE REVIEW

**Comment by huwshimi** [comment]
[Fix inspector header height](https://trello.com/c/ByyvgXWv/343-fix-inspector-header-height)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8530/

**Comment by frankban** [comment]
I can no longer dupe the original bug in trunk tip. Os this branch still relevant?

**Comment by mitechie** [comment]
I agree this looks fine in trunk for me as well. 
with-pr

**Comment by huwshimi** [comment]
@hatched I was able to reproduce it (Chrome only).

Looks like this has been resolved on develop. Thanks all.

**Comment by hatched** [comment]
So I ran into this....somehow today

screen shot 2018-02-23 at 9 31 12 am

So can we land this still @huwshimi ?

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8540/

**Comment by huwshimi** [comment]
@hatched yeah, I saw the same thing on Friday, I just checked and this branch still fixes the problem, so if it looks good to you then ship it.

**Comment by hatched** [comment]
Thanks @huwshimi :shipit:

**Pull request merged**
