### PR TITLE
Display the default model on the profile for older versions of Juju

### LINKED ISSUE #1424: No models listed on ec2
When running the GUI on ec2 I viewed the profile page and it didn't list any models.

There was an error in the console:

operation not supported by API server: {"Type":"EnvironmentManager","Request":"ListEnvironments","Params":{"Tag":"user-admin"}}

I also did not have a login button in the profile header.

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #1424.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- using Juju 1.25 deploy this branch with the charm
- open your profile
- you should seen an admin model listed
- click Manage
- you should be taken to the model

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4620/
Test PASSed.

**Comment by hatched** [comment]
:+1: :ok:

Thanks this works great!

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
