### PR TITLE
Revert state changes when opening store from the user profile.

### LINKED ISSUE #2917: Regression when clicking search results from profile page
Introduced by https://github.com/juju/juju-gui/pull/2879
Start from your profile, click to open the store, click to view a charm (either from the store initial page or search results), you'll end up in a URL like /u/{user}/{charm} which is not ok, as it overlaps with the user owned charm. We need to close the profile when opening a charm detail.

### PR DESCRIPTION
**Pull request by hatched**
Fixes #2917

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Follow the instructions in the bug.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7709/

**Comment by hatched** [comment]
Thanks all :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
