### PR TITLE
Remove YUI from relation utils

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- adding and removing relations from the canvas and via the inspector should work

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5685/
Test PASSed.

**Comment by hatched** [comment]
:+1: :ok:

Thanks @huwshimi 

slowly and surely moving away from YUI :)

**Comment by huwshimi** [comment]
Thanks @hatched :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
