### PR TITLE
Avoid multiple dispatches of special state callbacks.

### PR DESCRIPTION
**Pull request by frankban**
This caused charms to be added to the canvas twice when using the deploy-target query.

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6587/

**Comment by frankban** [comment]
QA:
- switch to production jimm;
- run `make run` on this branch;
- run `guiproxy -uuid disconnected` so that gisf mode is simulated;
- visit the proxy address and ensure you are logged out (anonymous user);
- visit `http://localhost:8042/?deploy-target=cs:trusty/kibana-11` end ensure the charm is added to the canvas in uncommitted state only once;
- do the same check with a bundle, like `http://localhost:8042/?deploy-target=bundle/mediawiki-single-9
`

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
