### PR TITLE
Profile model list improvements

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8394/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8395/

**Comment by huwshimi** [comment]
QA:

Changes in this branch are as follows:

Models
- Add hover style to row
- Make the blue link style for model name  on the hover
- Expand to MPV card
- Need a hand cursor over
- - Model name
- - Expandable row area
- - Trash can
- Correct column order
- - Move the permissions column to after the after the machines/cloud column
- Make the escape key successfully close the profile overlay
- Row height is too high

Charms
- Missing title and number of charms
- Charms rows need hover state

Bundles 
- Missing title and number of bundles
- Row vertical height (BARRY)

**Comment by huwshimi** [comment]
[Tweaks to model list etc.](https://trello.com/c/A8NmAO3v/173-tweaks-to-model-list-etc)

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Comment by frankban** [comment]
Ah, also, there is an error in the console: Warning: Expected `onClick` listener to be a function, instead got a value of `boolean` type. In the ModelActions component.

**Pull request merged**
