### PR TITLE
Small trivial changes.

### PR DESCRIPTION
**Pull request by frankban**
Some of them are done to make debugging easier, others to make required work more explicit.

### CODE REVIEW

**Comment by bac** [comment]
:+1:

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5467/
Test PASSed.

**Pull request merged**
