### PR TITLE
Fix profile redirect

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #2825.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- visit a user's profile e.g. /u/yellow or /u/hatch
- you should see that profile, the url should be the same and the username at the top of the profile should be correct
- visit /u/none
- you should see the empty user profile message

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7330/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
