### PR TITLE
Get versions error

### PR DESCRIPTION
**Pull request by huwshimi**
Display notifications for errors getting charm versions and doing the upgrade.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- replace `charmId` with a string `'not-a-charm'` here: https://github.com/huwshimi/juju-gui/blob/get-versions-error/jujugui/static/gui/src/app/components/inspector-change-version/inspector-change-version.js#L131
- add a service to the canvas
- deploy
- navigate to 'Change version'
- the list of versions should spin for a few seconds and then display a message

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3513/
Test FAILed.

**Comment by hatched** [comment]
I think that that was a spurious error...

**Comment by hatched** [comment]
:+1: QA :ok:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3517/
Test PASSed.

**Comment by fabricematrat** [comment]
:+1: thanks.

**Comment by jaycee** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
