### PR TITLE
Improve handling of local credentials in the account page.

### PR DESCRIPTION
**Pull request by frankban**
Also include minor fixes to the app and the credentials section of the deployment flow.

Fixes https://github.com/juju/juju-gui/issues/2881

### CODE REVIEW

**Comment by frankban** [comment]
QA:
- open the account page in gisf: it should work as usual for listing/adding/removing credentials;
- open the account page in gijoe connected to an LXD controller: the page should open without errors, and without allowing adding or removing credentials;
- ensure you can deploy and create new models in both scenarios.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7326/

**Comment by Lukewh** [comment]
QA OK

**Comment by frankban** [comment]
Thanks both!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
