### PR TITLE
Machine column drop

### PR DESCRIPTION
**Pull request by huwshimi**
Allow dropping units on machine and container columns to place onto new machines or containers.

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4036/
Test FAILed.

**Comment by huwshimi** [comment]
QA:
- add a service
- add several units
- drag the unplaced unit
- a drop target with a + in it should appear in the machine column
- dropping the unit on the machine column should bring up the new machine form
- click Place
- a new machine should have been created
- drag another unit and a drop target with a + in it should appear in the container column
- drop the unit on the container column
- a form for placing the unit should appear
- choose a container type and click Place
- a container should have been created

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4037/
Test PASSed.

**Comment by kadams54** [comment]
Two things noticed during QA:

1) The selected machine no longer obscures the border between the machine and container columns, diminishing the tab UI effect: http://cl.ly/2Q3N0l3I2S1y
2) When multiple machines are present, the scrollbar pops in and further diminishes the visual illusion of tabs: http://cl.ly/2R2S0s3R443a

**Comment by kadams54** [comment]
Aside from the issues noted above (which don't need to be addressed in order for this branch to land) QA is :ok: and code is :+1:.

**Comment by bac** [comment]
:+1:
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/1392

**Comment by kadams54** [comment]
Closing this PR out to correct the merge problem in my own branch.

**Comment by bac** [comment]
Merged by @kadams54 in https://github.com/juju/juju-gui/pull/1156

**Pull request closed without merging**
