### PR TITLE
Track first commit.

### PR DESCRIPTION
**Pull request by huwshimi**
The deploy button should read "Commit" changes after the first commit.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- visit `/:flags:/react/`
- add a charm `app.get('charmstore').getEntity('trusty/wordpress', function(entity) { app.deployService(entity[0]); });`
- the deploy button should read "Deploy changes"
- deploy
- the deploy button should now read "Commit changes"

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3233/
Test PASSed.

**Comment by hatched** [comment]
Shouldn't this be based on content actually in the environment or not? With this change if they refresh the  page it'll go back to "Deploy" even if the environment has items in it.

**Comment by huwshimi** [comment]
@hatched on render I could loop through the db and check the status of the added services to see if one has been deployed. Would that work?

**Comment by hatched** [comment]
Yeah I think that every time the deployer bar is rendered it will have to check to see if anything has been deployed to the environment already, as the db can be updated over the wire after it was rendered for the first time.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3251/
Test PASSed.

**Comment by hatched** [comment]
:+1: QA OK!

**Comment by huwshimi** [comment]
Thanks @hatched :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
