### PR TITLE
Fix the wrapping of long entity titles

### LINKED ISSUE #2453: Long charm/bundle names are not wrapped properly.
The design (showing how things should look with a title that wraps): Good wrapping

And reality:

Bad wrapping

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #2453.

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6819/

**Comment by huwshimi** [comment]
QA:
- find a charm or bundle with a long name or view an entity and use your browser tools to modify the name
- check that the title wraps correctly onto a new line

**Comment by Lukewh** [comment]
First QA instruction won't work properly as the height of the container is set via the JavaScripts, so changing the title after it's loaded won't refresh the height (which is also pretty bad if you increase font-size in browser). 

Therefore QA-OK, however your branch doesn't seem to include the revision number in the header?

**Comment by frankban** [comment]
:shipit: 
@huwshimi , please consider the suggestion from @Lukewh for a follow-up branch.

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
