### PR TITLE
Set up the deployment summary for the controller

### PR DESCRIPTION
**Pull request by huwshimi**
Display the appropriate fields on the deployment commit screen for a controller.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load GUI with the controller (i.e. embedded in Juju)
- make a change (e.g. add a service or machine)
- click commit
- you should see the summary screen and there should be no errors in the console

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5194/
Test PASSed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5230/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5240/
Test PASSed.

**Comment by huwshimi** [comment]
The deployment flow is about to be replaced, so this is now redundant.

**Pull request closed without merging**
