### PR TITLE
Fix env switcher layout in Firefox.

### PR DESCRIPTION
**Pull request by kadams54**

### CODE REVIEW

**Comment by kadams54** [comment]
## QA

You'll need to have `jujugui.jem_url` set to staging in `development.ini` and `showEnvSwitcher = true` on line 58 of `app-renderer-extension.js` in order to see the switcher in sandbox. Once those changes are in place, open the switcher in Firefox and verify that the layout looks sane. Check Chrome and (if possible) Safari as well.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4816/
Test PASSed.

**Comment by huwshimi** [comment]
Thanks for figuring this one out @kadams54! :+1: :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
