### PR TITLE
Implement the new profile header UI

### PR DESCRIPTION
**Pull request by barrymcgee**

### CODE REVIEW

**Comment by barrymcgee** [comment]
screen shot 2018-01-09 at 17 22 10

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8397/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8398/

**Comment by hatched** [comment]
In order to display the users name and email address additional API calls needed to be implemented in the GUI. This branch (https://github.com/juju/juju-gui/pull/3413) Implements those. At which point this branch can be updated to populate the necessary fields and the 'company' field can be removed for the time being.

**Comment by hatched** [comment]
Moving barry's notes from the initial comment so they don't show up in the gitlog:

...

I've amended the profile header to match the design specced out here: https://raw.githubusercontent.com/CanonicalLtd/juju-design/master/Profile/09-Header-specs.png?token=AAe24gixrYJMw7BVDA3ogl_WwUFqAC2Eks5aXglBwA%3D%3D

As you can see, I've hard coded the user profile info. Can you please swap in the correct info here?

screen shot 2018-01-09 at 17 22 10

**Comment by barrymcgee** [comment]
@hatched As all these changes are now included in #3414, this PR can be closed without merging, right?

**Comment by hatched** [comment]
Yep that's right.

**Pull request closed without merging**
