### PR TITLE
Handle new ModelManager API for creating models.

### PR DESCRIPTION
**Pull request by frankban**
QA:
- `make dist` on this branch: this will generate a `~/code/juju-gui/dist/jujugui-2.1.7.tar.bz2` archive;
- bootstrap a Juju controller after compiling latest master tip: `juju bootstrap lxd lxd --upload-tools`;
- upload the GUI archive to the controller: `juju upgrade-gui ~/code/juju-gui/dist/jujugui-2.1.7.tar.bz2`;
- open the GUI in the browser: `juju gui --show-credentials`, accept the self-signed certificate and the GUI should show up (note that login inputs are kind of weird);
- log in and use the profile page to create new models;
- repeat the above on aws or any other public cloud.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5353/
Test PASSed.

**Comment by urosj** [comment]
Taking over QA of GIJoe for LXD and AWS.

**Comment by urosj** [comment]
LXD 🆗

**Comment by urosj** [comment]
AWS 🆗

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5355/
Test PASSed.

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
