### PR TITLE
Add background to modal dialogues

### LINKED ISSUE #2209: All modal windows should have transparency behind them to hide the UI behind

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #2209.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- pop up a modal dialogue (e.g. open the profile when you have uncommitted changes)
- check that there is a semi translucent background over the gui

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6301/
Test PASSed.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
