### PR TITLE
Skip spurious failing simulator tests

### PR DESCRIPTION
**Pull request by hatched**

### CODE REVIEW

**Comment by makyo** [comment]
:+1:  The simulator was pretty useful, so we may want to keep it around, but I agree on making our tests more representative.

**Comment by hatched** [comment]
Yes I agree the simulator was very useful however I think it should live on the other side of a simulated websocket so that it actually tests the entire stack.

**Comment by hatched** [comment]
Thanks for the review!

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2471/
Test FAILed.

**Pull request closed without merging**
