### PR TITLE
Fix icon urls for charms and bundles in the profile page.

### PR DESCRIPTION
**Pull request by frankban**

### CODE REVIEW

**Comment by urosj** [comment]
👍

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by makyo** [comment]
👍

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5057/
Test PASSed.

**Pull request merged**
