### PR TITLE
Update old account components

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3473.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- use the pay flag and settings (ask me)
- load your profile and navigate to the payments section
- hopefully you should see something, but it seems like the data has been removed from the server

**Comment by huwshimi** [comment]
[Clean up old account components](https://trello.com/c/n2FenytZ/299-clean-up-old-account-components)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8490/

**Comment by hatched** [comment]
Thanks @huwshimi :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge/2686

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
