### PR TITLE
Update to use new bakery

### PR DESCRIPTION
**Pull request by frankban**
Use the bakery directly, not through jaaslib. Update how we create the instance with the new API.
Also upgrade jaaslib to newer version not depending on the bakery, so that we don't have two versions of the bakery around.

### CODE REVIEW

**Comment by frankban** [comment]
QA:
run the gui, check that you can login, and access jaas services as usual.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8915/

**Comment by hatched** [comment]
Thanks @frankban :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
