### PR TITLE
Add missing controller's data.

### PR DESCRIPTION
**Pull request by fabricematrat**

### CODE REVIEW

**Comment by fabricematrat** [comment]
QA: I added console log to display the data where I made the change, then deployed with gijoe and the output was there for aws on the default controller after bootstrap.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5780/
Test PASSed.

**Comment by hatched** [comment]
Thanks @fabricematrat 

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
