### PR TITLE
Display tooltips for the charm icons on search results

### LINKED ISSUE #1384: Implement tooltips showing the charm names on search

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #1384.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- do a search
- check that the icons for charms and bundles display the charm name in a tooltip above the icon when hovered

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4638/
Test PASSed.

**Comment by anthonydillon** [comment]
Code :ok: QA :+1: I think design wants the tooltips to grow with the word like in the store and not be set to a width. But if that is difficult then I think its ok.

**Comment by Lucapaulina** [comment]
Ant is right :)

**Comment by kadams54** [comment]
Code is :+1: for me as well, assuming the width issue is addressed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4653/
Test PASSed.

**Comment by huwshimi** [comment]
Thanks all, I've updated this to be auto width and on one line. :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
