### PR TITLE
Add macaroons to config if provided

### PR DESCRIPTION
**Pull request by makyo**

### CODE REVIEW

**Comment by makyo** [comment]
(Waiting on current branches around macaroons to land before integrating the rest of the way)

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4567/
Test PASSed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4649/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4668/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4683/
Test PASSed.

**Comment by makyo** [comment]
# QA (once jem gets /whoami)

* Deploy the embedded-gui-dev charm using this branch for the GUI
* Log into the storefront and enable the gui flag
* Log out and back in
* Go to view an environment - ensure that double-login doesn't happen

**Comment by jaycee** [comment]
Code looks :+1:

I'll QA later today.

**Comment by hatched** [comment]
:+1: No QA yet

**Comment by jaycee** [comment]
I've got the embedded charm spinning up with this branch now; should have qa notes shortly.

**Comment by frankban** [comment]
:+1: thank you!

**Comment by jaycee** [comment]
QA notes:

We hit some issues with macaroon verification.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4720/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4721/
Test PASSed.

**Comment by jaycee** [comment]
QA notes:

Using the embedded gui dev charm w/ this branch, I am able to load a model on api.jujugui.org/jem w/o logging in a second time in the GUI.

QA OK!

Thanks, @makyo

**Comment by makyo** [comment]
:shipit:!

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
