### PR TITLE
Entity details visual updates

### PR DESCRIPTION
**Pull request by Lukewh**

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7336/

**Comment by Lukewh** [comment]
## QA
They should look very similar to
https://github.com/CanonicalLtd/juju-design/blob/master/Charm%20and%20bundle%20details/Bundle%20details%20-%20header.png
https://github.com/CanonicalLtd/juju-design/blob/master/Charm%20and%20bundle%20details/Charm%20details%20-%20header.png

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
