### PR TITLE
Fix removed payment method message

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load the gui with payment set up (see my email)
- ope your profile and remove your payment method
- add `cs:~cmarstech/mattermost`
- open the deployment flow
- scroll down to the payment section
- you should see a message and a link to add a payment method

**Comment by huwshimi** [comment]
[Show the form for adding cards if missing](https://trello.com/c/YUYRAmwi/662-show-the-form-for-adding-cards-if-missing)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8695/

**Comment by huwshimi** [comment]
Thanks @hatched :shipit:

**Pull request merged**
