### PR TITLE
Add deploy-target support

### PR DESCRIPTION
**Pull request by hatched**
Add the ability to do the deploy-target query string functionality with the new state system.

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

- Use the production charmstore in the development.ini
- Visit the gui with the url suffix `?deploy-target=cs:ceph-268` and it should add the charm to the canvas. 
- You should then be able to commit and work in sandbox as usual.
- Refresh
- Visit the gui with the url suffix `?deploy-target=cs:bundle/kubernetes-core-10` and it should add the bundle to the canvas.
- You should then be able to commit and work in sandbox as usual.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6308/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6312/
Test PASSed.

**Comment by hatched** [comment]
Thanks @huwshimi :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
