### PR TITLE
Do not show the logout link if in sandbox mode

### LINKED ISSUE #1243: Logout shouldn't show in sandbox mode.

### PR DESCRIPTION
**Pull request by hatched**
Fixes #1243

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Open the GUI in sandbox mode, the logout button shouldn't be visible in the top right
Open the console and run `app.set('sandbox', false)`
Now navigate (open and close the charmbrowser)
The logout button should appear.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4206/
Test PASSed.

**Comment by kadams54** [comment]
Code is :+1: and QA is :ok: - thanks!

**Comment by hatched** [comment]
Thanks! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
