### PR TITLE
Remove visibility toggles

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add a service
- hover over the item in the added services list
- the controls for hiding and focusing on a service should not appear

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4415/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4416/
Test PASSed.

**Comment by kadams54** [comment]
:cry: :cry: :cry:

**Comment by kadams54** [comment]
Code is :+1: and QA is :ok:

**Comment by makyo** [comment]
:+1;

**Comment by huwshimi** [comment]
Thanks! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
