### PR TITLE
Update login page to show new api call

### LINKED ISSUE #1192: Update login screen with new information
As it turns out you can get the users password using the following command:

`juju api-info --password password`

This means the login screen can be converted into a single column with this message.

### PR DESCRIPTION
**Pull request by hatched**
With the newer juju's you can use a simple cli api call to fetch your password. This branch updates the login screen to show that instead of the long message. Fixes #1192

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

In sandbox mode, click Logout in the top right
Make sure the login screen looks decent and is still functional (u:admin p:password)

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4153/
Test PASSed.

**Comment by huwshimi** [comment]
Nice work, much cleaner :+1:

**Comment by hatched** [comment]
Thanks! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
