### PR TITLE
Profile header tooltips

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3436.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- open your profile
- hover your avatar and username
- they should show tooltips
- visit another user's profile
- hovering the avatar/username should not show tooltips

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8534/

**Comment by huwshimi** [comment]
@frankban good catch. Is there any way to tell what the provider is? I think the point of the tooltip is to hint at where the details are coming from. So for local it could read "Your local account details" and for SSO it could remain the same, but as you say we'd want to be able to configure that to show the correct SSO provider.

**Comment by cassiocassio** [comment]
+1 to “username at juju controller x.x.x.x” or dns name if we know it.
“Local”  means local to the Idm, not using a plugin that could be the usso
connector for Jaas or ldap who knows what else. Local is a bit overloaded -
local host etc. The tooltip should let the user where  the identity shown
ultimately resides.

**Comment by frankban** [comment]
We don't have an easy way to tell the id provider. We have the `@local` vs `@external` postfix on the user name to tell at least whether the user is a local controller user or an external one, authenticated through the idm.

**Comment by cassiocassio** [comment]
when adding users in the share dialog, we assume @external, and describe
the users so-added as "Ubuntu SSO user"

but we don't use @external in the juju path in the gui, and we assume it in
the share dialog if you provide a username

The idea of the tooltip for the username was to (i) help people discover
and use the gravatar functionality, and to help them remember that the JAAS
identity lives at login.ubuntu.com, which is somewhat hard to
remember/access otherwise (I know we'll send you there if you logout)

"Your Ubuntu One *account details*" -> links to login.ubuntu.com in new tab

In the local case... we *do* show @local in the GUI path, so perhaps the
tooltip could show

"Your *local username* at the juju controller" -> links to
https://jujucharms.com/docs/stable/tut-users#create-a-user

On Thu, Feb 22, 2018 at 8:40 AM, Francesco Banconi <notifications@github.com

**Comment by huwshimi** [comment]
I've updated this to remove the username tooltip until such time as we know exactly how to handle all those cases.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8561/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
