### PR TITLE
Correctly handle shared models in new profile

### PR DESCRIPTION
**Pull request by hatched**
The new profile view was not correctly handling shared models where you do not have admin permissions. This branch also cleans up some of the markup by removing two unnecessary nested divs.

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Be sure you have had a model shared with you where you have `read-only` permissions. Then view the new profile model list. It should not throw and return you back to the canvas.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8378/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8379/

**Comment by mitechie** [comment]
👍 QA ok with changes tested during pair QA'ing.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8380/

**Comment by hatched** [comment]
Thanks!

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
