### PR TITLE
Deployment flow and entity detail pages fixes.

### PR DESCRIPTION
**Pull request by frankban**
Changes include:
- improving the machines message on the deployment flow (fixes https://github.com/juju/juju-gui/issues/2510);
- making the link in the AWS credentials notes in the deployment flow a proper link vs full URL (fixes https://github.com/juju/juju-gui/issues/2591);
- fixing the links to files and zip archive in user owned charms and bundles (fixes https://github.com/juju/juju-gui/issues/2494);
- correctly displaying the number of revisions in charm/bundle detail pages (fixes https://github.com/juju/juju-gui/issues/2495).

QA:
- go to the deployment flow on your local lxd model and on a cloud model, and check that the machines message makes sense (and has the correct punctuation, space after the end of the sentence, etc.);
- in the deployment flow, select AWS, click to add credentials and check that the link points to the AWS credentials page correctly, and it is a link, not a full URL;
- go to the detail page of a promulgated charm, a promulgated bundle, a user owned charm and a user owned bundle: in all pages, the links to download the zip and to the included files should work;
- go to charm/bundle detail pages and check that the number of revisions is visible at the bottom right and it's not 0. Note that we can argue on the helpfulness of this information, but at least now it works, and in the future it might contain actual info, like charm push commits.

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6944/

**Comment by hatched** [comment]
QA Notes:

The revisions count has some extra spacing on the bottom. This can be fixed by applying the following:

```diff
diff --git a/jujugui/static/gui/src/app/components/entity-details/content/_content.scss b/jujugui/static/gui/src/app/components/entity-details/content/_content.scss
index 677ee82..751649e 100644
--- a/jujugui/static/gui/src/app/components/entity-details/content/_content.scss
+++ b/jujugui/static/gui/src/app/components/entity-details/content/_content.scss
@@ -160,8 +160,8 @@
     }
   }

-  .revisions {
-    padding-bottom: 20px;
+  .revisions h3 {
+    margin-bottom: 0;
   }

   .revisions__list {
```
QA OK otherwise.

**Comment by frankban** [comment]
Thank you Jeff for the review and for the css suggestion. Patch applied.
:shipit:

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6948/

**Pull request merged**
