### PR TITLE
Add watching with make run.

### PR DESCRIPTION
**Pull request by huwshimi**
Have the file watcher run with `make run`.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- run 'make run`
- check that the server runs
- modify a file
- check that the console outputs a file change

**Comment by hatched** [comment]
:+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2840/
Test PASSed.

**Comment by anthonydillon** [comment]
QA ok :+1:

**Comment by huwshimi** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
