### PR TITLE
Added method for getting agreements to the terms module

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- you may have to clean to pick up the jujulib changes
- if guimaas is up then connect to it
- run `app.terms.getAgreements()` (I think, I couldn't run it)

**Comment by hatched** [comment]
:+1: Thanks for this!

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5277/
Test FAILed.

**Comment by kadams54** [comment]
**QA Notes:**

Got an error after running the function:

~~~~
XMLHttpRequest cannot load https://api.jujugui.org/terms/v1/agreements/. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://0.0.0.0:6543' is therefore not allowed access. The response had HTTP status code 404.
~~~~

Maybe something needs tweaking API-side to allow requests from locally-running instances?

**Comment by kadams54** [comment]
Code looks good. :+1:

**Comment by hatched** [comment]
The issue has been fixed on the back end so once the tests are updated and we get a passing run it can be landed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5292/
Test PASSed.

**Comment by huwshimi** [comment]
Thanks @hatched and @kadams54, the tests are passing now. :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
