### PR TITLE
Fixed SCSS building.

### PR DESCRIPTION
**Pull request by huwshimi**
The SCSS files should rebuild when the files change.

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2816/
Test FAILed.

**Comment by huwshimi** [comment]
QA:
- change a scss file
- run `make css`
- the files should be built
- run `make css`
- the console should output "make: Nothing to be done for 'css'."
- change the scss again
- run `make css`
- the files should be built

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2817/
Test PASSed.

**Comment by hatched** [comment]
:+1: QA OK! Thanks for fixing this up

**Comment by huwshimi** [comment]
Thanks @hatched :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
