### PR TITLE
Display the bundle config for Juju 2

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #2492.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- open the bundle details page for a bundle
- scroll down to the bottom of the readme
- you should see the list of charms/config

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6841/

**Comment by hatched** [comment]
QA Notes:

While there is a list of applications, expanding them shows only "No config options available for this service.". This appears to be on all bundles so it doesn't appear to be fetching the config options and "service" should be renamed to "application"

**Comment by huwshimi** [comment]
@hatched that's strange, you should be seeing the config options e.g. openstack-base has some.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6847/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6848/

**Comment by hatched** [comment]
So it turns out I misunderstood what was actually supposed to be shown :) QA OK

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6849/

**Comment by huwshimi** [comment]
@hatched thanks, the new message should hopefully help others to not be confused in the future. :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
