### PR TITLE
Fix flicker when switching between the status and machine views

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3160.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- connect to a real model
- switch between the status and machine views
- the canvas should not flicker into view as you change views

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8035/

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
