### PR TITLE
Update the doCharmstoreLogout method to get the config from the correct location

### PR DESCRIPTION
**Pull request by hatched**

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

In an incognito tab using gisf.
Log into the GUI and view your profile, you should be logged into the charmstore.
Refresh the page and click "Login to charmstore".
Then click the user menu, it should work as expected.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8195/

**Comment by Lukewh** [comment]
## QA OK

**Comment by Lukewh** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
