### PR TITLE
Remove compare semver util

### PR DESCRIPTION
**Pull request by huwshimi**
We only support Juju 2 now, there was one use, but it was not required.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA: I'm not sure the plans in the inspector are ever actually shown, from memory it might have been disabled.

**Comment by huwshimi** [comment]
[Remove compare semver util](https://trello.com/c/YkS8GOwt/603-remove-compare-semver-util)

**Comment by frankban** [comment]
Thanks for this clean up!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
