### PR TITLE
Login size

### LINKED ISSUE #1089: Design of resolve button
resolve-button

### LINKED ISSUE #1092: login screen overlaps with instruction text.
This happens when windows narrow. Apparently, I use a somewhat narrow web browser window.

screen shot 2015-12-16 at 11 39 11 am

### PR DESCRIPTION
**Pull request by huwshimi**
Fix the login help text on smaller windows (fixes #1092). Adjust button padding to allow longer labels (fixes #1089).

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- remove the auth details in views.py
- open the gui
- check that the help text does not overlap the login form in a small browser window
- login
- add a service and some units
- deploy
- turn on the simulator
- wait until there are units in error
- view the error unit list
- check that "Resolve & retry" fits on one line in the button

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3935/
Test PASSed.

**Comment by hatched** [comment]
:+1: :ok: :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
