### PR TITLE
Fix the go config template

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- build a dist and deploy with gij
- the built config.js template should have a boolean value for `bakeryEnabled`

**Comment by huwshimi** [comment]
[Fix the go config template](https://trello.com/c/YsGFXDfa/668-fix-the-go-config-template)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8707/

**Comment by frankban** [comment]
Thanks!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
