### PR TITLE
Selected state for service blocks

### PR DESCRIPTION
**Pull request by anthonydillon**

### CODE REVIEW

**Comment by anthonydillon** [comment]
### QA
- Open `http://0.0.0.0:6543/:flags:/react/?deploy-target=bundle%2Fdjango-2`
- Click on a service
- Check the selection style matches the design below
- Click off the service and see it unselected
- Click from service to service and make sure it selects and de-selects correctly

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3163/
Test FAILed.

**Comment by anthonydillon** [comment]
service-blocks_states01 1

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3164/
Test PASSed.

**Comment by hatched** [comment]
This looks really good @anthonydillon 

QA Issue:

If you select a service then click the empty canvas the selected state goes away. I figure that it should stay selected because its inspector is still open.

**Comment by huwshimi** [comment]
Code :+1:. Thanks @anthonydillon!

**Comment by anthonydillon** [comment]
@hatched I think the service block interaction maybe correct and that the inspector should be reset when the user clicks off the service block. We will need a round of cards to wire the react inspector and canvas together. Such as, hover a service in the inspector should add hover style to service block in the canvas. Also if you enter a service in the inspector it should get the selected state.

I think these should be handled in follow up cards. That sounds good?

**Comment by anthonydillon** [comment]
@hatched after the discussion on IRC could you +1 so I can land please.

**Comment by hatched** [comment]
:+1:

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3194/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3196/
Test PASSed.

**Comment by anthonydillon** [comment]
Thanks @hatched @huwshimi  :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/1091

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
