### PR TITLE
Drop bundles

### PR DESCRIPTION
**Pull request by huwshimi**
Fixed dropping bundles outside the onboarding.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
 - with the onboarding visible, try dropping a bundle.yaml on the canvas outside of the onboarding image

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3337/
Test FAILed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3339/
Test FAILed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3341/
Test FAILed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3343/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3346/
Test PASSed.

**Comment by hatched** [comment]
:+1: QA :ok: Thanks for this fix

I tested that I could drop on both the onboarding and the canvas. Both cases it imported the bundle without opening the file instead.

**Comment by huwshimi** [comment]
Thanks @hatched :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
