### PR TITLE
Update generic button props

### LINKED ISSUE #2563: Update GenericButton to repurpose the title prop
GenericButton now supports child elements for content, just as `<button>` does, which means we no longer need to use the title prop for content. That, in turn, means we can use it to set `<button>`'s title attribute, and drop the tooltip prop. We may also be able to drop the icon prop, as SvgIcon elements can just be added as children.

### PR DESCRIPTION
**Pull request by huwshimi**
Cleanup of props that was previously left unfinished. Fixes #2563.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- have a poke around the GUI, the buttons should appear with icons and labels

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7854/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7855/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
