### PR TITLE
Use the new GetChanges endpoint on the Bundle facade.

### PR DESCRIPTION
**Pull request by frankban**
This way a controller connection is enough for retrieveing bundle changes from the GUI.

Also change the args passed to the getBundleChanges callback to conform better with the (err, response) pattrern.

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5945/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5946/
Test PASSed.

**Comment by hatched** [comment]
QA Looks good!

I qa'd in Sandbox and Juju 1 & 2.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
