### PR TITLE
Add machines

### PR DESCRIPTION
**Pull request by huwshimi**
Added machine listing to the machine view.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load the gui with `/:flags:/mv/`
- add a service
- open the machine view
- click Auto place
- you should get a machine in the machines column

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3726/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3727/
Test PASSed.

**Comment by hatched** [comment]
:+1: QA :ok: !

This is coming together nicely!

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
