### PR TITLE
Only show the relations component for charms and not bundles

### PR DESCRIPTION
**Pull request by hatched**

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

- View a charm in the charmbrowser, it should show the relations as usual.
- View a bundle in the charmbrowser, it should not show the relations component.
- There should not be any errors in the console.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3781/
Test PASSed.

**Comment by huwshimi** [comment]
QA OK :+1:

**Comment by hatched** [comment]
Thanks! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
