### PR TITLE
Missing null check

### PR DESCRIPTION
**Pull request by makyo**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3499/
Test PASSed.

**Comment by urosj** [comment]
QA (throw glance, mysql, haproxy & juju-gui on canvas):
- icon dragging works now (after second commit)
- creating relations with long press works OK, no issues
- double-click on icon, select build-relation ... still same issues with relation rendering as before (lines snap to icon and stop following cursor)

**Comment by hatched** [comment]
:+1: QA :ok:

QA Notes:
I dragged mysql, apache, and wordpress to the canvas and then created and destroyed relations. Then committed one relation with the services, destroyed that, created new ones and everything works as expected. Repeated this process a few times in hope to catch any spurious issues.

**Comment by hatched** [comment]
I repeated the same steps in Firefox and Chrome, QA :ok:

**Comment by urosj** [comment]
QA :+1: , Ty @makyo !!!

**Comment by makyo** [comment]
:shipit: with youthful vigor and destruction!!! (I've been watching too much anime)

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3500/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3501/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3502/
Test PASSed.

**Pull request merged**
