### PR TITLE
Update static urls

### PR DESCRIPTION
**Pull request by huwshimi**
Some static urls were not updated to the new pattern. Fixes: #1559.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load the GUI
- drop a zip of a charm on the canvas
- you should see the local inspector and no errors in the console

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4975/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4976/
Test PASSed.

**Comment by anthonydillon** [comment]
Code :ok: QA :+1:

**Comment by hatched** [comment]
👍 Thanks!

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
