### PR TITLE
Underline the link in the notification

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3053.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- open the GUI in a private window
- the login popup should appear
- 'click here' should be underlined

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7853/

**Comment by frankban** [comment]
QA ok.
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Comment by spencerbygraves** [comment]
The link here should be blue (#007AA6) and underlined on hover. Thanks.

**Pull request merged**
