### PR TITLE
Update the way boolean config values are calculated.

### PR DESCRIPTION
**Pull request by frankban**
Apparently, there is a minification problem leading to the "truetrue", "falsetrue" results in the bug.

Fixes https://github.com/juju/juju-gui/issues/2324

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6942/

**Comment by bac** [comment]
QA was ok on Chrome. On Safari the export button did nothing the first attempt. Subsequently it worked, opening a tab with the yaml as Safari does.

**Comment by frankban** [comment]
Thanks for the reviews!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
