### PR TITLE
Add service icon to unit inspector header.

### PR DESCRIPTION
**Pull request by kadams54**
Fixes https://github.com/juju/juju-gui/issues/1512.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4826/
Test PASSed.

**Comment by hatched** [comment]
Can you add some tests to this branch please

**Comment by anthonydillon** [comment]
Code and QA :+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4833/
Test PASSed.

**Comment by hatched** [comment]
:+1: Thanks for those tests!

**Comment by kadams54** [comment]
Thanks all! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
