### PR TITLE
* Missing Wily references

### PR DESCRIPTION
**Pull request by urosj**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3447/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3449/
Test PASSed.

**Comment by jaycee** [comment]
Code is :+1: -- I see no QA instructions, but I think this is sufficiently trivial that it doesn't need one (and I don't know that we have any charms in wily to check search results against anyway).

This can probably be landed with only one review.

**Comment by urosj** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
