### PR TITLE
Update file-field styling to match design

### PR DESCRIPTION
**Pull request by anthonydillon**

### CODE REVIEW

**Comment by anthonydillon** [comment]
## QA
- Bootstrap on GCE
- Run this branch locally
- Use [guiproxy](https://github.com/frankban/guiproxy) to run it on GCE
- Add something to the canvas
- Enter deployment flow
- Click the drop down and add new credentials
- See that the file input style matches the design [1]
- Use the mouse to click on the upload area and check it opens the file picker
- Tab down the form and see that the label styling reflects the action when active
- Press `Enter` and check the file picker dialog opens

_Left off the drag and down functionality, dont tell design_

[1] https://raw.githubusercontent.com/CanonicalLtd/juju-design/master/Deployment%20flow/Standard/2.png?token=ABWRnodffiYEk918lxTy_eTqVmh6q42Zks5YTn57wA%3D%3D

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6305/
Test PASSed.

**Comment by hatched** [comment]
Thanks @anthonydillon the button to click to add the json file is a little oddly positioned but you can fix that up in a follow-up thanks.

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
