### PR TITLE
Login errors

### PR DESCRIPTION
**Pull request by huwshimi**
Display a message if the login fails.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- remove the auth details from views.py
- open the gui
- enter an incorrect username and password
- you should get a message

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3917/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3918/
Test PASSed.

**Comment by kadams54** [comment]
QA is :ok:, :+1: on the code. Thanks!

**Comment by huwshimi** [comment]
Thanks @kadams54! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
