### PR TITLE
Add expert flow pricing components

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- open `deployment-flow.js`
- add {this._generatePricingSection()} to the `render` method after `{this._generateModelNameSection()}
- load the gui
- add an app and open the deployment flow
- you should see the pricing section and you should be able to highlight a plan

**Comment by huwshimi** [comment]
[Basic pricing UI](https://trello.com/c/KumSl5IC/495-basic-pricing-ui)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8632/

**Comment by hatched** [comment]
:shipit:

**Comment by hatched** [comment]
:shipit:

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
