### PR TITLE
Inputs should validate when there are no validators

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes credentials not able to be created on OpenStack.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load the GUI on OpenStack
- add an app
- open the deployment flow
- open the add credentials form
- input your creds
- click add
- the creds should be created and there should be no errors in your console

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5979/
Test PASSed.

**Comment by huwshimi** [comment]
Thanks @urosj :shipit:!

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
