### PR TITLE
Fix header styling

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #2958. Fixes: #2960.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- in a private browser load /new
- the login button should be the same height as the button next to it
- there should be no scrollbar at the bottom of the screen
- there should be no / hanging over the logo

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7748/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
