### PR TITLE
Fix logout when disconnected

### LINKED ISSUE #1555: Logging out throws error when not connected to a model
In a charm deployed GUI clicking to logout from the GUI when using gisf will throw an error in base.js logout method because it cannot `this.ws.close()` when ws doesn't exist.

### PR DESCRIPTION
**Pull request by huwshimi**
The logout was not working when in a disconnected model state due to the websocket and credentials not existing. Fixes #1555.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4972/
Test PASSed.

**Comment by hatched** [comment]
:+1: Thanks!

**Comment by hatched** [comment]
Shipping this now so that it can be qa'd with other branches. Any issues can be dealt with in a follow-up

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
