### PR TITLE
Fixed sticky icon alignment.

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #2536.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- view a charm
- scroll down until the sticky header appears
- check that the icon is aligned with the title

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6870/

**Comment by hatched** [comment]
QA OK Thanks @huwshimi

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
