### PR TITLE
Add tests for when env should/should not connect.

### PR DESCRIPTION
**Pull request by kadams54**

### CODE REVIEW

**Comment by kadams54** [comment]
## QA

Very little QA to do here since this is just tests, but if you really want to... you can edit `app.js` to re-institute the old logic found here: https://github.com/juju/juju-gui/commit/0961a64ed72e4434a8e87293e893da83c8229832#diff-21dd467cb411bdd922556d1af7461864L661

Run `make test-js-old` and one test ('should connect to model when GISF') should fail.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5082/
Test PASSed.

**Comment by huwshimi** [comment]
Looks good, thanks for that @kadams54. :+1:

**Comment by hatched** [comment]
:+1: Looks good! Thanks for adding coverage here

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
