### PR TITLE
Do not allow model names to be defined with periods.

### LINKED ISSUE #2459: Model name validation lacking
I tried to name a model `insights.ubuntu.com` which the UI was happy with but when I tried to deploy I got an error stating that the model name was invalid. So I changed it to `insights-ubuntu-com` and it worked.

The model name input should check for dots and error. They maybe more characters that are not allowed.

### PR DESCRIPTION
**Pull request by hatched**
Fixes #2459

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Try and create a model in the DF with a period in the name. The input should show an error.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6791/

**Comment by frankban** [comment]
QA ok.

**Comment by hatched** [comment]
Thanks @frankban :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
