### PR TITLE
Combine the two deploy buttons into one

### PR DESCRIPTION
**Pull request by anthonydillon**

### CODE REVIEW

**Comment by anthonydillon** [comment]
## QA
- Load the GUI and see the deployment button is disabled with a label of "Deploy changes (0)"
- Add a service and see that the button is enabled and the title is "Deployed changed (2)"
- Deploy the service
- The button should change to disabled and show "Commit changes (0)"
- Scale up the service and check the button is enabled and says "Commit changes (#)"

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4801/
Test PASSed.

**Comment by makyo** [comment]
:+1: QA :ok:

**Comment by hatched** [comment]
:+1:

**Comment by anthonydillon** [comment]
Thanks :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
