### PR TITLE
Don't include containers in the machine count

### LINKED ISSUE #1285: Canvas/machine view switcher includes containers in the machine count
Add a machine and then add a couple of containers in the machine view. Notice that above the inspector the counts for "0 services | 3 machines" will include the number of containers, not just machines.

### PR DESCRIPTION
**Pull request by huwshimi**
In the machine/canvas switcher the machine count was including the number of containers as well. Fixes #1285.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- open the machine view
- add a machine and then add a couple of containers
- notice that above the inspector the counts for "0 services | 3 machines" will include the number of machines but not containers

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4287/
Test PASSed.

**Comment by hatched** [comment]
:+1: :ok: :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
