### PR TITLE
Lock the xterm versions

### PR DESCRIPTION
**Pull request by huwshimi**
This was causing issues in the CI runs.

### CODE REVIEW

**Comment by huwshimi** [comment]
[Fix Xterm version](https://trello.com/c/SogbOHXw/769-fix-xterm-version)

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8904/

**Pull request merged**
