### PR TITLE
Display favicon

### PR DESCRIPTION
**Pull request by huwshimi**
Correctly display the favicon.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- run `make gui run`
- load the gui and you should see the favicon (you might need to clear your cache or view the gui in a private browser)

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3523/
Test PASSed.

**Comment by hatched** [comment]
Nice :) :+1: QA :ok:

**Comment by fabricematrat** [comment]
:+1:  thanks

**Comment by jaycee** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
