### PR TITLE
Raise a service to the top when it is clicked on

### LINKED ISSUE #1246: Canvas + should always be on top, at the moment if you put a service on the canvas it can be dragged over the top of it.

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #1246.

### CODE REVIEW

**Comment by huwshimi** [comment]
Note: I did not add tests as the whole section where this stuff is tested is currently skipped.

QA:
- add a few services
- drag a service over another service, the dragged services should be at the top
- make two services overlap
- clicking the service at the back should raise it to the top

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4259/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4260/
Test PASSed.

**Comment by anthonydillon** [comment]
Code :+1: and QA :ok:  although if you overlap a few services and click on one then the previous one of top is pushed back below others which is a little unexpected but understand it is being set to its default index.

**Comment by jaycee** [comment]
:+1:

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/1461

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
