### PR TITLE
Fixed escape closing the store

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #2532.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- open the store or search results
- hit escape
- the store should close

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6876/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
