### PR TITLE
Fix pressing enter to submit the login form.

### LINKED ISSUE #1266: Can't submit login form by pressing enter
On the login page if you type a username and password and then press enter it does not submit the form.

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #1266.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- in your browser console enter `app.set('sandbox', false)`
- open the midpoint and close again
- click the logout button
- type a username and password
- hit enter
- the login form should submit

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4262/
Test PASSed.

**Comment by anthonydillon** [comment]
Code :ok: QA :+1:

**Comment by jaycee** [comment]
:+1:

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
