### PR TITLE
Add instructions about setting up a dev env with multipass.

### PR DESCRIPTION
**Pull request by frankban**
You can see the rendered document at https://github.com/frankban/juju-gui/blob/multipass-docs/docs/macos-multipass.md

### CODE REVIEW

**Comment by jujugui** [comment]
Build finished.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8242/

**Comment by jujugui** [comment]
Build finished.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8243/

**Comment by barrymcgee** [comment]
@frankban 

Thank you for this - I'm now up and running locally 💥

Just a few notes I noticed going through:

1. Should this section:

```
ubuntu exec dev -- sudo apt update
ubuntu exec dev -- sudo apt install avahi-daemon avahi-autoipd
```

...also include an upgrade command, like so?

```
ubuntu exec dev -- sudo apt update
ubuntu exec dev -- sudo apt upgrade
ubuntu exec dev -- sudo apt install avahi-daemon avahi-autoipd
``` 

2. I think this code block includes rogue '2's?

```
ssh ubuntu@dev2.local 'touch ~/code/it-works'
ll ~/code/ubuntu2/it-works # This should work.
rm ~/code/ubuntu2/it-works # Clean it up.
```

...this is what worked for me based on previous steps:

```
ssh ubuntu@dev.local 'touch ~/code/it-works'
ll ~/code/ubuntu/it-works # This should work.
rm ~/code/ubuntu/it-works # Clean it up.
```

It would also improve clarity to split this into two sections, separating the commands on the VM and the commands on the host machine?

3. This block;

`sudo sh -c "echo dev.local:/home/ubuntu/code /Users/frankban/code/ubuntu nfs resvport,rw,rsize=8192,wsize=8192,timeo=14,intr >> /etc/fstab"` 

...contains a path to your local machine (`/Users/frankban/code/`) - it would improve clarity to signpost this, explaining that user needs to swap in their own home directory, as you did above with Launchpad id.

4. This code block contains a rogue star?

```
Exports list on dev.local:
/home/ubuntu/code                   *
```

5. macos should be macOS (Apple fanboy alert 😬)

**Comment by frankban** [comment]
Hey @barrymcgee, thanks for the feedback, good stuff.
1. The upgrade step is not strictly required, so I'd not include that.
2. Yes, removed the 2s, good catch. The three commands there must be all run in the host.
3. Done.
4. No the star should actually be present in the output, and it means that the export is available from everywhere.
5. Done.

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Build finished.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8244/

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Comment by cassiocassio** [comment]
@frankban 

The NFS and fstab stuff is neat - would the ubuntu mount command do something similar, but more simply?

**Comment by frankban** [comment]
@cassiocassio no `ubuntu mount` uses sshfs, and, in my experience, it is slower and still have some weird permission issues.

**Pull request merged**
