### PR TITLE
Support MAAS controllers when creating new models.

### PR DESCRIPTION
**Pull request by frankban**
Also improve handling of relation-broken errors.

### CODE REVIEW

**Comment by mhilton** [comment]
LGTM

**Comment by hatched** [comment]
:+1: 
Test failure is spurious (cb not called)

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3357/
Test PASSed.

**Comment by frankban** [comment]
Thanks for the reviews!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
