### PR TITLE
Update bakery-utils to es6

### PR DESCRIPTION
**Pull request by Lukewh**
Fixes /login, doesn't fix login buttons.

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8055/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8061/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8062/

**Comment by Lukewh** [comment]
Replaced by https://github.com/juju/juju-gui/pull/3200

**Pull request closed without merging**
