### PR TITLE
Make delete confirmation render-time decision.

### LINKED ISSUE #2105: Issues destroying apps
- add a few of apps
- deploy
- click destroy on an app
- click on another app and you'll get the message "This application has been marked to be destroyed on next deployment." and there is no destroy button
- click on the canvas
- click on the destroyed app
- clicking on other apps will have the same problem above
- click on the canvas
- click on an app that is not destroyed
- click on the destroyed app
- this time the destroyed app will not show the message and you can destroy it again

### PR DESCRIPTION
**Pull request by kadams54**
Fixes #2105.

### CODE REVIEW

**Comment by kadams54** [comment]
## QA

- add a few of apps
- deploy
- click destroy on an app and you should get the destroyed confirmation
- click on another app and the confirmation should disappear
- click on the canvas
- click on the destroyed app - verify that the destroyed confirmation is still there
- click on other apps and verify that the confirmation disappears
- click on the canvas
- click on an app that is not destroyed
- click on the destroyed app - verify that the destroyed confirmation is still there

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5958/
Test PASSed.

**Comment by anthonydillon** [comment]
Looks and works great on GIJoe :+1:

**Comment by kadams54** [comment]
Thanks all! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
