### PR TITLE
Prototype loading hints

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load /new in a private browser
- see that you get hints of the elements that will load

**Comment by jujugui** [comment]
Build finished.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8236/

**Comment by hatched** [comment]
Smart implementation idea @huwshimi and this works quite well with /new or when going straight into a model. However it's a little odd when you see the 'element hints' and then you're dropped right into the profile or entity details.

**Comment by huwshimi** [comment]
@hatched yeah, I noticed that as well, maybe there's no way to do this properly...

**Comment by cassiocassio** [comment]
screenshot from 2017-11-07 17-19-14

**Comment by cassiocassio** [comment]
Ooo @huwshimi 
Interesting. Nice idea. I fear my connection at home and work is often too fast to feel the need for this, but that's not try for many,

I made a video and took some screengabs to see what Facebook do – their implementation is nice.

I like the way if makes good-enough guesses about what the content will be, that even when it's a bit wrong the illusion if complete.

You can see from the timer it takes perhaps 2 seconds for the four states:

screen shot 2017-11-07 at 17 22 28

screen shot 2017-11-07 at 17 22 36

screen shot 2017-11-07 at 17 22 40

screen shot 2017-11-07 at 17 22 48

**Pull request closed without merging**
