### PR TITLE
Display the terms in the deployment flow

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add a charm without terms
- load the deployment flow
- scroll to deploy button
- there should be no terms agreement checkbox above it
- close the df
- add a charm that has terms
- load the df
- scroll to the list of applications
- the app with terms should have a terms link next to it
- clicking the terms link should open a popup with the terms
- close the popup
- scroll to deploy button
- there should be a terms agreement checkbox above it

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6614/

**Comment by urosj** [comment]
QA failed: deploy works even if a user doesn't agree to terms. It should be blocked until user agrees to the checkbox.

**Comment by kadams54** [comment]
Replaced by #2366.

**Pull request closed without merging**
