### PR TITLE
Require YUI modules

### PR DESCRIPTION
**Pull request by huwshimi**
Require YUI modules instead of combo loading them so that we can require() utils etc. inside the YUI modules.

### CODE REVIEW

**Comment by huwshimi** [comment]
[Require YUI modules](https://trello.com/c/PaVne7ex/667-require-yui-modules)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8706/

**Comment by huwshimi** [comment]
[Fix the go config template](https://trello.com/c/YsGFXDfa/668-fix-the-go-config-template)

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
