### PR TITLE
Avoid using deprecated Client.ModelInfo API.

### PR DESCRIPTION
**Pull request by frankban**
Use the ModeInfo call on the ModelManager facade instead.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5597/
Test PASSed.

**Comment by frankban** [comment]
QA: on gijoe,
- you should be able to successfully login;
- after that, all these commands should return reasonable results:
```
app.env.get('defaultSeries');
app.env.get('providerType');
app.env.get('environmentName');
app.env.get('modelUUID');
app.env.get('modelTag');
```

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5598/
Test PASSed.

**Comment by hatched** [comment]
Thanks @frankban this looks great

**Comment by hatched** [comment]
Thanks @bac  :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
