### PR TITLE
Remove humanize timestamp util

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load the gui with prod
- open the header model switcher
- the models should show the time since connected for the models (as before)
- connect to a model and open the sharing panel
- the users should show the time since accessed (as before)

**Comment by huwshimi** [comment]
[Remove humanize timestamp util](https://trello.com/c/EaueUn94/602-remove-humanize-timestamp-util)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8669/

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
