### PR TITLE
Migrate tests to the new test suite

### PR DESCRIPTION
**Pull request by huwshimi**
Moves tests for the app and hotkeys to the new test runner.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- the tests should pass

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4361/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4362/
Test PASSed.

**Comment by hatched** [comment]
:+1: !!!!

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
