### PR TITLE
Fix cascading plans lookup

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- use `guiproxy -env staging -flags experts,pay`
- visit `/new/?dd=cs:~cmarstech/mattermost`
- open your network tab
- you shouldn't see never ending calls to `https://api.staging.jujucharms.com/omnibus/v3/charm?charm-url=cs:~cmarstech/mattermost-0`

**Comment by huwshimi** [comment]
[Fix cascading plans lookup](https://trello.com/c/JTwbaFk7/618-fix-cascading-plans-lookup)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8676/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
