### PR TITLE
Gracefully fall back if provided with an invalid service id when viewing the inspector

### PR DESCRIPTION
**Pull request by hatched**

### CODE REVIEW

**Comment by huwshimi** [comment]
Thanks @hatched. Code looks good, will QA shortly.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3102/
Test PASSed.

**Comment by huwshimi** [comment]
QA OK!

**Comment by huwshimi** [comment]
:+1:

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
