### PR TITLE
Remove handlebars

### PR DESCRIPTION
**Pull request by huwshimi**
Replace the remaining Handlebars templates with React components. Remove Handlebars building.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load the gui
- check that the onboarding loads correctly
- open the shortcuts (shift + /)
- check that the shortcuts panel opens correclty
- add two services: juju-gui and nrpe
- add a relation
- check that the "Select relation type" panel appears
- once they are related click on the relation and check that the relation details appear

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4255/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4256/
Test PASSed.

**Comment by hatched** [comment]
:+1: :ok:

In the shrinkwrap there is still a top level 'handlebars' object which probably just needs to be re-generated away. You should be able to 'make clean-all deps fast-babel gui' then 'npm uninstall handlebars' then 'npm shrinkwrap' to remove it.

QA Notes:
Checked that the onboarding dispalyed correctly and that the plus button still worked.
Checked that the shortcuts displayed properly and that the selections worked as before.
Checked that the ambiguous relation menu worked as before with ghost and deployed services

**Comment by hatched** [comment]
This update saved us 27KB over the wire after gzip :)

**Comment by jaycee** [comment]
:+1: thanks @huwshimi. Nice to see all that code removed/replaced.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
