### PR TITLE
More automated way for resetting connection attribues.

### PR DESCRIPTION
**Pull request by frankban**
Also fix a regression introduced by last branch (modelUUID not found when picking the model). 
See QA instructions for how to ensure it now works.

### CODE REVIEW

**Comment by frankban** [comment]
QA in gijoe:
- log in with admin credentials, check that you are connected to the "default" model;
- run `console.log(app.env.get('defaultSeries'), app.env.get('environmentName'), app.env.get('controllerAccess'));` and you should get the requested information;
- log out;
- run the same command again and you should get `null null ""`;
- log in again with admin credentials, check that you are still connected to the "default" model.
Done, thank you!

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5848/
Test PASSed.

**Comment by urosj** [comment]
QA 🆗

**Comment by hatched** [comment]
Thanks @frankban 
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
