### PR TITLE
Fix table rows overlapping

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3527.

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8519/

**Comment by huwshimi** [comment]
QA: there are three cases to test.

1.
- connect to a model and open status
- clicking on an app row should open the inspector

2.
- open your profile and hover the person icon on a model, it should not get cut off by the rows above it

3. open the credential list
- click the ...
- the menu should not get cut off by the rows below it

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8520/

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
