### PR TITLE
Replace Y.delegate

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- start a new model
- add a couple of apps
- relate them
- remove the relation
- drag around the canvas
- drag around the apps
- drop a charm zip on the canvas (the inspector should appear but you can't upload the app due to #2546)
- generally do as much with the canvas as you can
- note: #1712 still exists

**Comment by jaycee** [comment]
QA:

Most operations with the canvas worked.

Dragging a zipped charm onto the canvas did not work; the "drop file" command came up but the inspector did not. Dropping triggered chrome's "Leave the page or stay" alert--clicking stay did nothing, clicking leave led to chrome downloading the zip I had just dropped. More than a little peculiar.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7195/

**Comment by jaycee** [comment]
QA:

The inspector showed up on drag and drop as expected.

QA OK.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
