### PR TITLE
Update the username once it is available.

### LINKED ISSUE #1414: Refreshing the GUI when logged in does not set your username
When you have logged into your profile and then refresh the GUI your username in the breadcrumb is "anonymous".

If you click on something like the machine view then your username gets set.

### PR DESCRIPTION
**Pull request by huwshimi**
Rerender the breadcrumb with the username once it has been loaded. Fixes #1414.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load the gui while logged out
- your username should be "anonymous"
- log in
- refresh the gui
- your username should be "..." and then your actual username once it loads

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4578/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4579/
Test PASSed.

**Comment by anthonydillon** [comment]
Code :ok: QA :+1:

**Comment by kadams54** [comment]
Code is :+1: for me as well. Thanks @huwshimi! :shipit:

**Comment by kadams54** [comment]
Code is :+1: for me as well.

**Comment by kadams54** [comment]
Thanks @huwshimi! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
