### PR TITLE
Integrate js macaroon

### PR DESCRIPTION
**Pull request by makyo**

### CODE REVIEW

**Comment by frankban** [comment]
:+1: ty!

**Comment by makyo** [comment]
Thanks :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2835/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2836/
Test PASSed.

**Pull request merged**
