### PR TITLE
Fix notification hover

### LINKED ISSUE #2112: A notification should not disappear if I am hovering over it
A common user behaviour is to attempt to hover over canvas notifications to read and assimilate their content better, expecting that they will remain there if they do so but they don't.

Could we look into this?

### PR DESCRIPTION
**Pull request by kadams54**
Fixes #2112.

### CODE REVIEW

**Comment by kadams54** [comment]
## QA

1. Deploy an app.
2. Hover over the notifications as they appear.
3. The notifications should remain in place as long as you hover over them (try for longer than 10 seconds).
4. As soon as you are no longer hovering, the notifications should disappear in about 3-4 seconds.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6049/
Test PASSed.

**Comment by anthonydillon** [comment]
Code and QA :+1:

**Comment by kadams54** [comment]
Thanks! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
