### PR TITLE
Move section wrappers to the parent deploy flow component

### PR DESCRIPTION
**Pull request by huwshimi**
By moving the wrappers to the parent component we'll have better access to the props require to enable/disable sections.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- use the df flag
- start the deployment flow
- check that the sections enable as required

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5522/
Test PASSed.

**Comment by anthonydillon** [comment]
Thanks @huwshimi Code looks good to me :+1:

**Comment by hatched** [comment]
Thanks @huwshimi 

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
