### PR TITLE
Clean up inputs in the add credentials form

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6017/
Test FAILed.

**Comment by huwshimi** [comment]
QA:
- deploy on GCE or update they gce cloud to have a key of `demonstration` in deployment-flow.js
- add an app
- open the deployment flow
- open the add creds form
- change the auth type to oauth2
- check that all the fields are the same width and that the labels appear correctly when focused and not focused
- check that the 'Private key' field appears just like the others except that you can have multi line strings in it

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6018/
Test PASSed.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
