### PR TITLE
Add credentials component

### PR DESCRIPTION
**Pull request by huwshimi**
Move the credentials section to a component.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
 - use the "df" flag
- open the deployment flow
- choose  a clou
- you should see the credential form
- click add
- you should see select boxes for creds

**Comment by anthonydillon** [comment]
Code and QA :+1:

**Comment by hatched** [comment]
Thanks @huwshimi :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
