### PR TITLE
When adding gce credentials, show that a file has been stored.

### PR DESCRIPTION
**Pull request by hatched**
Fixes: https://github.com/CanonicalLtd/jujucharms.com/issues/407

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

bootstrap a controller to gce
enter the deployment flow and 'add a credential'
select the json file upload dialog and add a file.
it should update to show that something has been added.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6859/

**Comment by hatched** [comment]
Thanks @huwshimi 

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
