### PR TITLE
Remove units

### PR DESCRIPTION
**Pull request by huwshimi**
Added removing of unplaced units and units on containers in the machine view.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- use the flag `/:flags:/mv/`
- add a service
- open the machine view
- using the context menu on the unplaced unit click Destroy
- the unit should be removed
- add a second unit to the service
- click Auto place
- using the context menu on the unit on the root container click Destroy
- the unit should be removed

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3846/
Test PASSed.

**Comment by anthonydillon** [comment]
Once a unit has been placed and I "destroy" it. It moves to unplaced instead of destroying it. Is this expected behaviour? If so, I think the working in the root container should say "Unplace" of something.

**Comment by anthonydillon** [comment]
Cannot drag and drop unit anymore so can only autoplace?

**Comment by anthonydillon** [comment]
Code and QA :+1:

**Comment by kadams54** [comment]
Code is :+1: and QA is :ok:. Nice work @huwshimi!

**Comment by huwshimi** [comment]
@anthonydillon drag and drop is coming!

Thanks for the reviews :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
