### PR TITLE
Clear the add credential form when reopened

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3517.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- open the credential list
- click add credential
- fill in some of the form fields
- click cancel
- open the form again
- the fields should be empty

**Comment by huwshimi** [comment]
[Clear the add cred form when reopened](https://trello.com/c/d7xLG6tf/322-clear-the-add-cred-form-when-reopened)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8512/

**Comment by hatched** [comment]
The QA was successful for me, would you mind trying again @mitechie

**Comment by mitechie** [comment]
wfm, not sure what happened. :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
