### PR TITLE
[#2149] Honor config values set in the bundle.

### PR DESCRIPTION
**Pull request by kadams54**

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6120/
Test FAILed.

**Comment by kadams54** [comment]
## QA

1. Add the `landscape dense-maas` bundle to the canvas (you don't need to deploy).
2. Check the `haproxy` application's config in the inspector.
3. The `services` config setting should be an empty string.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6121/
Test PASSed.

**Comment by anthonydillon** [comment]
Good catch :+1:

**Comment by kadams54** [comment]
Thanks all! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
