### PR TITLE
Don't display unplaced units for subordinates.

### LINKED ISSUE #1265: Subordinates are shown in the MV in a real env
To reproduce, deploy the GUI into a real environment.
From within the GUI add NRPE to the canvas and relate it to the GUI. Deploy this change and wait. NRPE will show up as an unplaced unit in the machine view. This appears to be caused by the lack of check for 'subordinate' when generating the unplaced unit list in machine-view.js

### PR DESCRIPTION
**Pull request by huwshimi**
Subordinates should not appear as units in the unplaced unit list. Fixes #1265.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- deploy the gui charm with this branch
- From within the GUI add NRPE to the canvas and relate it to the GUI.
- Deploy this change and wait.
- NRPE should not show up as an unplaced unit in the machine view.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4223/
Test PASSed.

**Comment by hatched** [comment]
This stops the units from appearing but the "AutoPlace" button is still visible.
screenshot from 2016-01-20 09 56 28

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4239/
Test PASSed.

**Comment by huwshimi** [comment]
@hatched I have updated this to correctly filter out subordinates.

**Comment by hatched** [comment]
Looks good! :+1: :ok: 
Thanks!

**Comment by huwshimi** [comment]
Thanks @hatched :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
