### PR TITLE
Add Juju 2.0 support for add/remove relation API calls.

### PR DESCRIPTION
**Pull request by frankban**
To QA, deploy two services, add a relation, remove the relation.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4468/
Test PASSed.

**Comment by urosj** [comment]
LGTM

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
