### PR TITLE
Fix profile typo

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #2841.

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7265/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7266/

**Comment by frankban** [comment]
This was already fixed at https://github.com/juju/juju-gui/pull/2762
Anyway, the fix seems to have disappeared, probably for mistakenly rewriting the git history.
Thanks Huw for fixing this again.
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
