### PR TITLE
Update node deps inc React 15.3

### PR DESCRIPTION
**Pull request by hatched**
A number of dependencies required updating. This branch updates the node dependencies and fixes any regressions found thereafter.

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

`npm cache clear`
`make clean-all deps fast-babel run`

Then do an exploratory qa to make sure everything works as expected.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5507/
Test FAILed.

**Comment by hatched** [comment]
CI required an `npm cache clear`

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5508/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5509/
Test PASSed.

**Comment by huwshimi** [comment]
QA OK :+1: thanks @hatched

**Comment by hatched** [comment]
Thanks @huwshimi :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
