### PR TITLE
Update expert flow copy updates

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3675. Fixes: #3676.

### CODE REVIEW

**Comment by huwshimi** [comment]
[Expert flow copy changes](https://trello.com/c/6fOOsYJQ/666-expert-flow-copy-changes)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8696/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
