### PR TITLE
Add payments to new profile

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load the gui with `-flags profile,pay`
- open your profile
- you should be able to view a payments section

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8382/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8383/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8384/

**Comment by mitechie** [comment]
I'm getting an error setting up payments here: 

qa-payment-error

So then I can't fill in the CC field? I'm guessing that's the field under the name field. I don't see any heading or such there to be certain. I can't hit submit on this then. 

qa-payment

**Comment by mitechie** [comment]
Hmm, the QA instructions are just seeing a screen which I guess I do see. 

qa-show-payments

**Comment by huwshimi** [comment]
Thanks @mitechie that's correct, you're seeing what I wanted you to see, there's some more config you need to do to actually use the functionality.

:shipit:

**Pull request merged**
