### PR TITLE
scss watching

### PR DESCRIPTION
**Pull request by huwshimi**
Fixed watching and building of SCSS files in subdirs.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- run `make run`
- modify a scss file in a subdir of `/app/assets/css/` e.g. `/app/assets/css/browser`
- check the console ouput `Regenerating SCSS`
- refresh the gui and check that the css updated

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2653/
Test FAILed.

**Comment by jaycee** [comment]
I started the gui and then monkeyed with the scss. I saw it regenerate and saw the color I changed go from dark to white, as I had set it.

I should note that it outputs the "Regenerating SCSS" message twice--that's not qa bad but it's a bit odd.

QA OK. :+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2664/
Test PASSed.

**Comment by mitechie** [comment]
:+1: :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/934

**Comment by mitechie** [comment]
Retrying, seems some sort of sauce labs race

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/935

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
