### PR TITLE
Fix deployed commit summary

### LINKED ISSUE #1637: .split syntax error when using deployment flow on existing models
To reproduce you need to have already deployed a model starting from a disconnected state and deploying a model. Now refresh the GUI and you should be back in a disconnected state. Switch to your model using the model switcher and then add a new service to the canvas. Click to open the deploy summary and you'll notice an error in the browser console about .split()

### PR DESCRIPTION
**Pull request by huwshimi**
Fix the deploy summary when the model has been committed. Fixes #1637.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load a real juju gui
- switch to an existing model
- add a service or machine
- click Commit changes
- you should see the summary screen

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5026/
Test PASSed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5033/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5034/
Test PASSed.

**Comment by kadams54** [comment]
:+1: code looks good to me.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
