### PR TITLE
Login to the charmstore from the profile

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3485.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load the gui pointed to a non-jaas controller
- go to your profile charm or bundle list
- there should be a message about logging in
- log in
- your charms/bundles should appear

**Comment by huwshimi** [comment]
[Add charmstore login to the profile](https://trello.com/c/FoUHMTjO/317-add-charmstore-login-to-the-profile)

**Comment by huwshimi** [comment]
@hatched I didn't manage to QA this with a controller at the end of the day (some rubbish about a tls handshake that I couldn't figure out).

I'll have another look in the morning.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8504/

**Comment by mitechie** [comment]
QA is passable but I love how the login button lines up with the vertical bar above it in the charm case, but then it moves in the bundle case. 

qa-bundles
qa-charm

**Comment by mitechie** [comment]
So works for me and the code looks ok to me. One small issue noted with the spacing/alignment but solid.

**Comment by hatched** [comment]
I've fixed the styling locally but I need @huwshimi to check the box which says 'allow commits from maintainers.'

**Comment by hatched** [comment]
```diff
-- a/jujugui/static/gui/src/app/components/profile/bundle-list/_bundle-list.scss
+++ b/jujugui/static/gui/src/app/components/profile/bundle-list/_bundle-list.scss
@@ -1,5 +1,4 @@
 .profile-bundle-list {
-  width: 766px;

   .icon-list__item {
     margin: 0 4px 0 0;
```

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8510/

**Comment by huwshimi** [comment]
Thanks @mitechie and @hatched :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
