### PR TITLE
Do not disconnect from the model when viewing user profiles.

### LINKED ISSUE #3334: unable to deploy charms from my profile page to my current running model
I created a model and added my prometheus charm by going from the empty model, to my profile, view the charm, add to model, and then I went through the DF and saw the get started text.

I then closed that get started box and went back to my profile, selected to view my grafana charm, and when I hit "add to model" it ends up in a new model titled "untitled-model" and not the one I'd already created/was on.

### PR DESCRIPTION
**Pull request by hatched**
Fixes #3334

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8326/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8327/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8328/

**Comment by frankban** [comment]
I am going to ship this as the little QA issue can be handled in a follow-up branch.
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
