### PR TITLE
Split up resolve and retry actions of units in error

### LINKED ISSUE #1138: Unable to mark a unit as 'resolved'
The new mockups call for a "resolve & retry" and "remove" button in the error unit list. Unfortunately if that unit is in error it cannot be removed (https://bugs.launchpad.net/juju-core/+bug/1528073) and because we can't mark the unit as 'resolved' without automatically 'retrying' the hook which is failing it's impossible to remove the unit without dropping to the CLI.

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #1138.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add a unit
- run `app.db.units.item(0).agent_state = 'error';`
- open the list of error units
- you should see separate Resolve and Retry buttons
- for bonus points try them in a real env

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4005/
Test PASSed.

**Comment by kadams54** [comment]
Code is :+1:. Couldn't get the unit to go into an error state in my sandbox. I suspect this is due to `app.db.units` being a `LazyModelList` (hence no change event or re-render), but even doing `app.db.units.revive(0).set('agent_state', 'error')` didn't seem to trigger a re-render.

Going to re-attempt in a real env.

**Comment by hatched** [comment]
:+1: :ok: 

I also was not able to get it working following the instructions but using the simulator made it work as intended. Thanks for this fix!

**Comment by huwshimi** [comment]
Thanks for the reviews @hatched and @kadams54 :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/1379

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/1380

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/1381

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
