### PR TITLE
UI cleanups

### PR DESCRIPTION
**Pull request by huwshimi**
Hid the zoom controls to match the new UI, removed Actions in the inspector as we won't have them for a while, fixed the click event when dragging the plus circle.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- visit `/:flags:/react/`
- add a service e.g. `app.get('charmstore').getEntity('trusty/apache2', function(entity) { app.deployService(entity[0]); });`
- in the inspector check that there is no "Actions" item next to "Expose"
- on the canvas drag the (+) circle around
- when you stop dragging nothing should happen (the mid-point used to open)
- check that the canvas zoom controls are no longer on the right hand size

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3201/
Test PASSed.

**Comment by anthonydillon** [comment]
LGTM :+1: although not sure you need to check the zoom controls outside of the react flag because all the canvas re-work is not flagged.

**Comment by anthonydillon** [comment]
QA ok good.

**Comment by hatched** [comment]
QA :ok: 

I'm with @anthonydillon on the zoom controls - you might as well just remove it and all its assets, yui modules etc etc

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3202/
Test PASSed.

**Comment by anthonydillon** [comment]
QA :ok:, couple of comments of slider in code but it sets the range of zoom so could rename you feel like it.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3204/
Test PASSed.

**Comment by huwshimi** [comment]
Thanks @anthonydillon and @hatched :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/1094

**Comment by mhilton** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/1095

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
