### PR TITLE
Fix typo causing charmstore to be undefined when deploying from the user profile

### LINKED ISSUE #3359: Cannot deploy private charms from profile
To reproduce:

Add a private charm to your account then in a new model, open your profile and add it to the canvas. When you complete deploy you'll get an error about not being able to call `getDelegatableMacaroon` of undefined.

### PR DESCRIPTION
**Pull request by hatched**
Fixes #3359

### CODE REVIEW

**Comment by hatched** [comment]
There are no tests here because this mixin isn't actually tested at all. We'll need to do a follow-up to add just that.

#### To QA
From your user profile, try and deploy a private charm.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8312/

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
