### PR TITLE
Update breadcrumb when navigating to profile pages.

### PR DESCRIPTION
**Pull request by frankban**
Also fix the mouse hover message on the Juju logo.
Fixes https://github.com/juju/juju-gui/issues/2540

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6868/

**Comment by bac** [comment]
# QA-Better

Cloud logo is still on the page when returning to the profile.

screen shot 2017-03-01 at 13 33 20

**Comment by frankban** [comment]
Thanks for the reviews!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
