### PR TITLE
Improve deployment flow error handling. Fix the breadcrumb content.

### LINKED ISSUE #2380: If there is an error deploying the deploy button gets stuck disabled
To reproduce, try and create a model with the same name as an existing model. You'll get a vague error notification ( which we should properly handle) and the deploy button stays disabled with 'deploying...' So it isn't possible to resolve the error and try again

### LINKED ISSUE #2381: Profile and model switcher use incorrect model paths
The profile page and model switcher use the currently logged in user name for the model path, not the owner from the model info. For example. If you have access to another users model it should be `theirname/modelname` but right now it links to `yourname/modelname`

### LINKED ISSUE #2387: Model switcher: disambiguate models owned by other users.
The model switcher, for models owned by another user, should maybe include the user name as a prefix for the model name in the list. I think that models owned by the currently logged in user could keep hiding the user name.

### PR DESCRIPTION
**Pull request by frankban**
Deployment flow: gracefully handle deployment errors by re-enabling the deploy button (fixes #2380)
Breadcrumb component: show model owner instead of user name (fixes #2381).
Model switcher: disambiguate models owned by other users (fixes #2387).

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6674/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6675/

**Comment by frankban** [comment]
QA: the following must be done in both gijoe and gisf, use guiproxy if required for gisf, or customize development.ini accordingly, point the GUI to the production jimm.

- click on the breadcrumb to go to your profile page;
- click to create a new model;
- deploy something;
- click to deploy changes and enter the deployment flow;
- name your model "test-model", select a cloud and deploy;
- ensure the deployment succeeds, the breadcrumb should show your user name and "test-model";
- do the same as above, create a new model and name it "test-model" again;
- click to deploy and you should see an error notification: "cannot create model: already exists";
- the deploy button should be back to the enabled state;
- rename the model, click deploy again, everything should work;
- now, if you are in gisf connected to production jimm, use the model swithcer to switch to "jujugui-org";
- ensure the model switch succeeds, and that the breadcromb show "uros-jovanovic" / "jujugui-org".

Note that:
1. at this point, clicking "uros-jovanovic" does not do anything, it does not open the profile page for the user. This is bug #2386.
2. the model switcher, for models owned by another user, should maybe include the user name as a prefix for the model name in the list. This is bug #2387.

**Comment by frankban** [comment]
Also note that clicking the profile button in the model switcher no longer works with this branch: this will be fixed later.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6676/

**Comment by jaycee** [comment]
QA notes:

Running 'guiproxy -config gisf:true' with the production jimm controller:

I spun up the gui; it hung at '/' so I went to '/login' where I was able to successfully login. The breadcrumb showed "jcsackett" rather "jcsackett@external"; clicking it updated the url but did not load profile page. The console shows the error "invalid root path. unable to generate state: invalid root path."

Clicking the profile button in the model switcher showed the same issue.

**Comment by frankban** [comment]
Yes these are all the QA problems we currently have on remove-yui-router.

**Comment by Lukewh** [comment]
QA-OK 1/2. GUI - 🆗 
QA-? 2/2. GISF - Some underlying issues with the remove-yui-router base branch mean I can't QA. Will QA again once the issue is resolved.

**Comment by jaycee** [comment]
@frankban Ok, I must misunderstand your QA directions--this seemed to me like I could not complete QA. I'm glad @Lukewh took care of it. :smile:

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6681/

**Comment by Lukewh** [comment]
Refreshing the page hangs on the 'Connecting to the Juju model' spinner, only way back in is to go through /login again. May be part of the known remove-yui-router issues?

**Comment by frankban** [comment]
:shipit:

**Comment by frankban** [comment]
Thanks for the QA efforts JC and Luke! I did QA on gisf with `guiproxy -config 'gisf: true, jujuEnvUUID: ""'`.

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
