### PR TITLE
Ux qa updates

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes for a number of issues found during QA review.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA: it's probably easiest to run through the list of bugs linked to this PR.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3744/
Test PASSed.

**Comment by hatched** [comment]
:+1: QA :ok:

Thanks for tackling so many of these!

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
