### PR TITLE
Don't display the DF if there are no changes

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- visit `http://0.0.0.0:6543/deploy/:flags:/blues/`
- the gui should navigate away from the /deploy/ url
- add a service or machine
- open the deployment flow
- you should see the deployment flow

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5604/
Test PASSed.

**Comment by hatched** [comment]
Thanks @huwshimi

**Comment by anthonydillon** [comment]
LGTM :+1:

**Comment by kadams54** [comment]
QA is :ok: - thanks @huwshimi!

**Comment by hatched** [comment]
Thanks all! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
