### PR TITLE
Hover states and more

### LINKED ISSUE #1179: The inspector and Juju logo need to be 20px from the left edge of the canvas, and 15px from the top

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #1179 #1182 #1198 #1176 #1178 #1177 #1180 #1194.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA: See the attached bugs.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4168/
Test PASSed.

**Comment by hatched** [comment]
:+1: :ok:

Interesting approach using rtl for #1198 I attempted to add `text-overflow: ellipsis` and it oddly added it to the front while truncating the back...

Notes:
I checked to make sure that all of the issues above were handled in qa

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
