### PR TITLE
Add identity API to jujulib

### PR DESCRIPTION
**Pull request by hatched**
To support some of the features in the new profile view we need to be able to query for the logged in users information. This supplies the necessary API instance for that.

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

After loading the GUI, open the devtools and run the following, substituting your username.

```JavaScript
JujuGUI.identity.getUser('usernamegoeshere', (err, data) => console.log(err, data))
```

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8401/

**Comment by huwshimi** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Comment by frankban** [comment]
I think we need to rework part of this branch: I believe assuming an idm URL is not a good idea, and it make the check we do in the bakery/storage handling redundant. See my comment at https://github.com/juju/juju-gui/pull/3414

**Pull request merged**
