### PR TITLE
Converted LESS to SCSS.

### PR DESCRIPTION
**Pull request by huwshimi**
Converted all the LESS to SCSS in the new directory. The SCSS will not build in this branch as the pieces for building are in another PR (https://github.com/juju/juju-gui/pull/754).

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- use a scss tool to compile `app/assets/css/base.scss`
- everything should build without errors

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2592/
Test PASSed.

**Comment by jaycee** [comment]
QA notes:

I merged this into PR #754, in which I disabled less generation so the GUI was only being built with scss. 

I confirmed specifically that the deployer-bar css was in the generated juju-gui css file.

I also confirmed that the GUI loaded up with the appropriate styling.

QA OK.

**Comment by jaycee** [comment]
Thanks @huwshimi :+1:

**Comment by kadams54** [comment]
QA Notes: I also merged into #754 and confirmed that the CSS was in place post-build. Did some general browsing/use of the GUI and didn't see any CSS issues.

QA is OK, :+1: thanks @huwshimi!

**Comment by jaycee** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
