### PR TITLE
Abort XHR

### PR DESCRIPTION
**Pull request by huwshimi**
Abort XHR requests when components are unmounted.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load the inspector change version panel, the entity details or the search results and navigate away before the content has loaded
- there should be no setState errors in your console
- note: the change version fix won't work until the double component updates are fixed

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3424/
Test PASSed.

**Comment by hatched** [comment]
:+1: QA :ok: 

I'm wondering if we shouldn't start working towards a more compose-able component structure to avoid the duplication of this interaction. Lets chat about it.

**Comment by makyo** [comment]
:+1: :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
