### PR TITLE
Status anchor links

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3152.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- open the status view for a deployed model
- check that you can click on the app rows etc. to load the apps in the inspector
- right click on a row and open the link in a new tab
- the link should be correct, but currently redirects to the wrong place due to #3188

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8043/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8048/

**Comment by hatched** [comment]
Thanks @huwshimi 

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
