### PR TITLE
Remove old files

### PR DESCRIPTION
**Pull request by huwshimi**
Clean up old files for building and running the gui.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- check that the GUI can be built and run

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4400/
Test PASSed.

**Comment by hatched** [comment]
Nice! :+1:

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
