### PR TITLE
Style links in deployment flow with correct font-weight

### LINKED ISSUE #3379: Invisible link in cloud provider sign up page
## Actual

screen 20shot 202017-11-07 20at 2010 47 43

## Expected

Links should be differentiated from the text around them

### PR DESCRIPTION
**Pull request by barrymcgee**
Fixes #3379

### CODE REVIEW

**Comment by barrymcgee** [comment]
## Before these changes:

screen 20shot 202017-11-07 20at 2010 47 43

## After these changes:

screen shot 2017-12-07 at 14 11 35

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8350/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8352/

**Comment by huwshimi** [comment]
Hi @barrymcgee should these links be blue like in these mockups, or has the link styling changed since then? https://github.com/CanonicalLtd/juju-design/blob/master/Deployment%20flow/03%20add%20credential:%20Google.png

**Comment by barrymcgee** [comment]
@huwshimi Yes, confirmed with @spencerbygraves - these links should be `$color-link`. Will push that fix now.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8358/

**Comment by huwshimi** [comment]
Thanks @barrymcgee. I think maybe these don't need to be bold anymore. I don't think any of the other links are.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8364/

**Comment by mitechie** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
