### PR TITLE
Use the phantomjs provided with mocha-phantomjs

### PR DESCRIPTION
**Pull request by hatched**
The version of phantom that karma is using is newer than the one mocha-phantom uses which is causing issues about resource timing.

### CODE REVIEW

**Comment by frankban** [comment]
:+1: ship it!

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3769/
Test PASSed.

**Comment by hatched** [comment]
w00t :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
