### PR TITLE
Handle webhandler errors

### LINKED ISSUE #1618: Webhandler doesn't handle request failure
Because of a bug in JEM certain model requests will fail but the request that is created from juju.js to bakery to webhandler only ever handles the successful path because the webhandler.js doesn't attach failure events. This means that if any request fails then the GUI hangs.

### PR DESCRIPTION
**Pull request by huwshimi**
Try to actually handle the webhandler errors. Fixes #1618.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA: We don't really have a way to test this. We'll just have to add this and wait and see what happens.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5014/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5017/
Test PASSed.

**Comment by kadams54** [comment]
Looks good to me. :+1:

**Comment by hatched** [comment]
:shipit: Thanks!

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
