### PR TITLE
Show proper diffs of JSX

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- run `make start-karma`
- open a test file
- find a test that compares jsx
- replace `assert.deepEqual(output, expected);` with  `expect(output).toEqualJSX(expected);`
- modify the expected jsx
- you should get a diff in your terminal showing the exact change

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7042/

**Comment by hatched** [comment]
I am a little suspicious how the shrinkwrap was reduced by 2200 lines after adding a dependency :)

**Comment by huwshimi** [comment]
@hatched that doesn't seem right, I'll try again.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7044/

**Comment by huwshimi** [comment]
Thanks everyone :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
