### PR TITLE
Follow up to allow descriptions in direct deploy for charms too

### PR DESCRIPTION
**Pull request by Lukewh**

### CODE REVIEW

**Comment by Lukewh** [comment]
## QA

Ensure a direct deploy of a charm with a description (e.g. /?dd=nagios) shows the description.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7732/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7737/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7739/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7740/

**Comment by hatched** [comment]
There appears to have been a rebase issue, can you take a look at that plz.

**Comment by Lukewh** [comment]
Fixed in https://github.com/juju/juju-gui/pull/2969

**Pull request closed without merging**
