### PR TITLE
Update the DestroyModels API call for the new Juju API

### PR DESCRIPTION
**Pull request by frankban**
Fixes https://github.com/juju/juju-gui/issues/3541

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8528/

**Comment by mitechie** [comment]
QA ok, works on jaas v3 and on a maas controller that's v4 juju 2.3.3

Thank you for the quick turn around.

**Comment by frankban** [comment]
Thanks for the review and QA!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
