### PR TITLE
When switching models from dc state make sure the model name updates.

### LINKED ISSUE #2146: in GISF switching models does not show correct model name in Safari
When switch from one model to the other, it is common to see 'untitled-model' temporarily before the selected model name shows up. That's what happens in Chrome. In Safari the canvas populates but 'untitled-model' remains.

screen shot 2016-10-19 at 17 18 22

### PR DESCRIPTION
**Pull request by hatched**
Fixes #2146

### CODE REVIEW

**Comment by hatched** [comment]
This is the continuation of: https://github.com/juju/juju-gui/pull/2151 so no QA is necessary, as long as the ci tests pass it's ok to go.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6090/
Test PASSed.

**Comment by hatched** [comment]
Thanks! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
