### PR TITLE
Tweak import/export icon vertical alignment.

### LINKED ISSUE #1984: Import icon off vertical alignment off
Using Juju 2 tip and GUI tip deployed to aws.
screenshot from 2016-09-08 12 51 49

### PR DESCRIPTION
**Pull request by kadams54**
Fixes #1984.

### CODE REVIEW

**Comment by kadams54** [comment]
## QA

1. Deploy in a real env, where the model switcher will be present in the breadcrumb.
2. Verify that the icon (see #1984 for a screenshot) is now top-aligned with the model switcher.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5779/
Test PASSed.

**Comment by anthonydillon** [comment]
Thanks, had that on my list to update :) :+1:

**Comment by kadams54** [comment]
Excellent. :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
