### PR TITLE
Fix service icon bounceback when dragging on canvas

### PR DESCRIPTION
**Pull request by hatched**
This fixes an issue where the service icons would bounce back to their original positions while the user was dragging them around.

### CODE REVIEW

**Comment by hatched** [comment]
Note: Tests already existed for this functionality but did not exist for the timer functionality so no new tests are needed.

#### To QA
Deploy to a real environment - LXC is fine but the slower the env the better.
On the canvas, click and drag the service icon around in short bursts ~1s for 30s. If it doesn't snap back to its original position then you're ok.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2411/
Test PASSed.

**Comment by bac** [comment]
Code is :+1: but I have my machine tied up right now and cannot do QA.

**Comment by makyo** [comment]
Code LGTM, QAing now.

**Comment by makyo** [comment]
QA okay - deployed the GUI and NFS, dragged them around for a while, individually, then alternating.  :+1:

One thing I noticed is that, with the deltas coming back, the service health graph on an unplaced service goes up and down as I'm dragging it about in short bursts.  It's almost as if each time a delta comes back, it decides whether or not to display as unplaced.  Not for this branch and low priority, just something to keep an eye on.

**Comment by hatched** [comment]
Thanks for the reviews and qa! @makyo can you create a low priority bug just so that we can track it? Thanks again!

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by chuckbutler** [comment]
dear @hatched, thank you for this

**Comment by hatched** [comment]
@chuckbutler No Problem! :) A release with this fix (and others) will be coming soon as well.

**Pull request merged**
