### PR TITLE
Only get a new dd entity if the id changes in the deployment flow.

### PR DESCRIPTION
**Pull request by hatched**

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Visit `<host>/new/?dd=cs:bundle/canonical-kubernetes` 
It should not reload every time an entity is downloaded in the background.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8667/

**Comment by frankban** [comment]
Fixes https://github.com/juju/juju-gui/issues/3641

**Comment by frankban** [comment]
QA is ok.
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
