### PR TITLE
Model API: properly send the charm configuration.

### PR DESCRIPTION
**Pull request by frankban**
Fixes https://github.com/juju/juju-gui/issues/2845 by correctly sending the right config fields to the Application.Deploy API call.

### CODE REVIEW

**Comment by frankban** [comment]
QA:
It must be done in gijoe and gisf scenarios (for gisf, given the changes in this branch, guiproxy should be sufficient).
Deploy the openstack-base bundle and, after the charms are deployed, check that the network-manager option of the Nova Cloud Controller charm is set to Neutron.
Also deploy some other charm, change config values in the inspector, and ensure they stick after deployment.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7839/

**Comment by frankban** [comment]
Thank you for the reviews!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
