### PR TITLE
Add a hover state to the logout link

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3003.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load /new
- click the user icon in the top right
- hover the logout link, it should show a background like the other menu items

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7859/

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
