### PR TITLE
Add containers feature to store

### PR DESCRIPTION
**Pull request by anthonydillon**
Fixes: https://github.com/juju/juju-gui/issues/2019

### CODE REVIEW

**Comment by anthonydillon** [comment]
## QA
- Click on search.
- Check that the middle feature box now matches the one on storefronts staging.
- It differs in that it links to a search result instead of the topics page. But this is to maintain state and matches the OpenStack feature to the right.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5852/
Test PASSed.

**Comment by hatched** [comment]
Thanks @anthonydillon 

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
