### PR TITLE
Pyju cleanup

### PR DESCRIPTION
**Pull request by makyo**
Remove PyJuju remnants

### CODE REVIEW

**Comment by makyo** [comment]
# QA

Mechanical change; QA entire app to ensure that nothing is broken in devel mode/sandbox.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2581/
Test FAILed.

**Comment by makyo** [comment]
Additional build failed, but it looks unrelated to this.  IE 10 is having a bit of a problem with notifications.  Digging a bit.

**Comment by frankban** [comment]
Code looks good.
:+1:

**Comment by hatched** [comment]
:+1: QA OK! THanks!

**Comment by makyo** [comment]
:shipit: thanks!

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
