### PR TITLE
Update unit list in subordinate app after removing ghost relation.

### LINKED ISSUE #1975: Removing subordinate relations doesn't trigger db update
I related nrpe to python-django. The python-django application was in error so the nrpe subordinate showed the errors for python-django (as it should). However once I removed this relation (it wasn't yet committed) the errors remained until the next delta triggered the db update. When we remove this subordinate relation we should be sure that the db update is triggered so that the inspector and added-applications-list updates accordingly.

### PR DESCRIPTION
**Pull request by frankban**
Fixes #1975

### CODE REVIEW

**Comment by frankban** [comment]
QA: in gijoe, follow instructions in the related bug.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5884/
Test PASSed.

**Comment by hatched** [comment]
Thanks @frankban this works as expected!

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/1927

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by frankban** [comment]
This was a spurious failure.
:shipit:

**Pull request merged**
