### PR TITLE
Hook up the model name field to the deploy command

### PR DESCRIPTION
**Pull request by huwshimi**
Allow the model name to be set on the deployment summary screen.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- work through the deployment flow
- on the summary you should be able set the model name

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4817/
Test PASSed.

**Comment by jaycee** [comment]
Code looks :+1:

**Comment by makyo** [comment]
Code :+1:, still having issues QAing due to stuff 401ing after login.  If someone else can check, that'd be good, or count @urosj's demo as QA :ok:

**Comment by huwshimi** [comment]
Thanks @jaycee and @makyo :shipit:.

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
