### PR TITLE
Require existing modules

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load /nova-compute/271
- the markdown should be rendered and code should be highlighted
- clicking the clipboard icon should copy the command
- add the app to the canvas
- open the machine view
- create a machine
- drop the unit on the machine

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8175/

**Comment by Lukewh** [comment]
## QA OK 👍

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8178/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
