### PR TITLE
Handle unspecified cloud tags for models.

### LINKED ISSUE #2507: Sandbox mode no longer loads

### PR DESCRIPTION
**Pull request by kadams54**
Fixes #2507.

### CODE REVIEW

**Comment by kadams54** [comment]
## QA

1. `make run`.
2. Visit `http://localhost:6543`. Verify that the canvas loads without any errors in the console.
3. Play around, try to deploy, hit machine view and inspector, etc. Make sure all works as expected in sandbox mode.

**Comment by hatched** [comment]
Added DNL tag so we can get the hotfix out first.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6840/

**Comment by bac** [comment]
QA looks good but I did get these svg viewBbox errors:

screen shot 2017-02-22 at 16 43 55

**Comment by hatched** [comment]
Thanks @kadams54 :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
