### PR TITLE
Fix unit scaling input in Firefox

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3482.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- open the gui in Firefox on OSX
- add an app
- open the machine view and click the [+] to scale the number of units
- the "units" text in the input  should be readable

**Comment by huwshimi** [comment]
[Fix scaling input in Firefox on OSX](https://trello.com/c/yjoyu75O/307-fix-scaling-input-in-firefox-on-osx)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8496/

**Comment by mitechie** [comment]
QA ok looks good. :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
