### PR TITLE
Align models table according to the spec

### PR DESCRIPTION
**Pull request by barrymcgee**

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8416/

**Comment by barrymcgee** [comment]
## QA

- Run jujugui with 'profile' flag - `guiproxy -env prod --flags profile`
- Navigate to models table on your profile - `http://192.168.64.3:8042/u/$USERNAME/#models`
- Cross-ref with the design spec - https://github.com/CanonicalLtd/juju-design/blob/master/Profile/11-Models-table-specs.png

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8417/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8418/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8419/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8420/

**Comment by hatched** [comment]
The gap between the card and the horizontal rule with the expanded row seems to be larger than the mockups. It's 24px, but with the extra row padding of 12px it's much larger.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8426/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8427/

**Comment by barrymcgee** [comment]
@hatched Extra margin should now be addressed

**Comment by hatched** [comment]
- It appears that the permissions icons shift to the left very slightly, like 1-2px
- The trashcan moves left quite a bit...

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8430/

**Comment by hatched** [comment]
Thanks @barrymcgee :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
