### PR TITLE
Clear the ECS when logging out

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #2068.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add an app
- in your browser console run `app.logout()`
- refresh your window
- you shouldn't get a reload confirmation popup

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5931/
Test PASSed.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
