### PR TITLE
Add the ability to close the profile

### PR DESCRIPTION
**Pull request by huwshimi**
Add a temporary option for closing the profile/account pages until there is proper design. Fixes: #3387.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- with the old and new profiles and the account page check there are close x buttons and that they close the pages

**Comment by huwshimi** [comment]
[Add a temporary way to close the profile](https://trello.com/c/ewKBTpGG/143-add-a-temporary-way-to-close-the-profile)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8370/

**Comment by huwshimi** [comment]
Thanks @mitechie, I think the functionality will remain, but the UI might change slightly, so might not be worth a comment. Happy to add one as a followup if you think it's important.

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
