### PR TITLE
Fix machine view flex issue.

### PR DESCRIPTION
**Pull request by huwshimi**
Fix the machines column header when there are a lot of machines.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add a service
- open the machine view
- add 100 new units
- click 'Auto place'
- check that the machines column header ("Sandbox (100)") does not collapse

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2629/
Test PASSed.

**Comment by hatched** [comment]
This is now two areas which gets rid of the `flex-basis` mixin, should the other one be removed as well?

**Comment by jaycee** [comment]
Looks good to me, Huw, thanks. :+1: 

I loaded up 100 auto placed units of mysql and nothing seems to be collapsed. QA OK.

**Comment by hatched** [comment]
:+1: as well

**Comment by huwshimi** [comment]
@hatched I've removed the flex-basis mixin so we don't run into issues in the future. The other place wasn't having issues, but this way we should be OK if something changes.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2630/
Test PASSed.

**Comment by huwshimi** [comment]
Thanks @hatched and @jaycee :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
