### PR TITLE
Fixed duplicate tag ids

### LINKED ISSUE #1611: Store console errors
I spotted there are quiet a few console errors when displaying the store. For example:
`flattenChildren(...): Encountered two children with the same key, .$bigdata. Child keys must be unique; when two children share a key, only the first child will be used.`

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #1611.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- search for "big data"
- you should not have any duplicate id errors in the browser console

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5011/
Test PASSed.

**Comment by anthonydillon** [comment]
Fixes this bug I believe: https://github.com/juju/juju-gui/issues/1611

**Comment by anthonydillon** [comment]
Code looks good :+1: No QA yet.

**Comment by anthonydillon** [comment]
QA ok

**Comment by kadams54** [comment]
Code looks :+1: to me as well. Thanks!

**Comment by kadams54** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
