### PR TITLE
Don't show the inspector scaling screen when read only

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3528.

### CODE REVIEW

**Comment by huwshimi** [comment]
[Don't show the inspector scaling screen when read only](https://trello.com/c/jeKrrwBs/348-dont-show-the-inspector-scaling-screen-when-read-only)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8535/

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
