### PR TITLE
Remove old deployer bar

### PR DESCRIPTION
**Pull request by huwshimi**
Remove old deployer bar, enable new deployment components.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- with no flags load the gui
- the new deployment button should appear and the old one should be gone
- add some services and check that the updates appear
- do the same with `/:flags:/react/`

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3379/
Test PASSed.

**Comment by jaycee** [comment]
QA notes:

Both with and without the react flag I added mysql and wordpress, deployed them with autoplacement and related them.

The UI and experience was as expected.

QA OK, :+1:

Thanks @huwshimi!

**Comment by hatched** [comment]
Thanks for the review and qa @jaycee :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/1158

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/1160

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3394/
Test PASSed.

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/1161

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
