### PR TITLE
[#2193] Vertically center cloud logo in Firefox.

### PR DESCRIPTION
**Pull request by kadams54**
Fixes https://github.com/juju/juju-gui/issues/2193

### CODE REVIEW

**Comment by kadams54** [comment]
## QA

Bootstrap juju in the cloud of your choice and then `make dist && juju upgrade-gui dist/jujugui-2.2.2.tar.bz`. Verify that the cloud provider logo in the breadcrumb is vertically centered in both Firefox and Chrome.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6174/
Test PASSed.

**Comment by hatched** [comment]
screenshot from 2016-11-14 14 36 19

**Comment by hatched** [comment]
To fix that spacing issue here are the modifications I've found to work well:

```css
.header-banner__provider {
    float: left;
    height: 68px;
    /* padding: 15px 0 0 20px; */
    padding-left: 20px;
    position: relative;
    /* top: 50%; */
    /* transform: translateY(-50%); */
}

#provider-logo-container .svg-icon {
  top: 50%;
  transform: translateY(-50%);
  position: relative;
}
```

**Comment by hatched** [comment]
screenshot from 2016-11-14 18 19 51

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6175/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6176/
Test PASSed.

**Comment by frankban** [comment]
👍 thank you!

**Comment by hatched** [comment]
Thanks @kadams54 QA OK

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
