### PR TITLE
Don't allow duplicate credential names

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #2658.

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7111/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7112/

**Comment by huwshimi** [comment]
QA:
- the only one that can easily be QAed is getting the payment methods, run this in your browser console: `app.payment.getPaymentMethods('YOUR USERNAME HERE', (error, data) => {console.log(error, data)});`

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
