### PR TITLE
Fixed elk-stack link in the store

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3578.

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8578/

**Comment by huwshimi** [comment]
[Fix elk-stack link](https://trello.com/c/4ot4KN7A/414-fix-elk-stack-link)

**Comment by huwshimi** [comment]
QA:
- open the store
- scroll down and click on the elk-stack link
- it should display the bundle details

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
