### PR TITLE
Upgrading node packages

### PR DESCRIPTION
**Pull request by hatched**
Upgrading some node packages that have had new releases come out in the past couple weeks.

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA
`make clean-all deps fast-babel gui`
Use the GUI, it should work as expected

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3648/
Test FAILed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3649/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3650/
Test PASSed.

**Comment by huwshimi** [comment]
QA OK :+1: thanks for this @hatched.

**Comment by jaycee** [comment]
:+1: looks good, @hatched.

**Comment by hatched** [comment]
Thanks for the reviews and qa! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
