### PR TITLE
Remove deployer code from go env and sandbox

### PR DESCRIPTION
**Pull request by makyo**

### CODE REVIEW

**Comment by makyo** [comment]
# QA

App should function as expected.  QA should focus on sandbox and bundle deployment in a live env

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2529/
Test FAILed.

**Comment by hatched** [comment]
:+1: QA OK!

**Comment by makyo** [comment]
Thanks! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
