### PR TITLE
Do not set state when closing the deployment flow.

### LINKED ISSUE #3228: new-init: deploying a model has a setState error
When you click deploy there's a console error: `Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the DeploymentFlow component.`

### PR DESCRIPTION
**Pull request by hatched**
Fixes #3228

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

In a new model, deploy an application. There should not be a setstate error in the console.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8200/

**Comment by hatched** [comment]
Thanks @Lukewh 
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
