### PR TITLE
Update entity action links

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #1704.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- connect to prod
- open the store and click on a bunch of bundles and charms
- check that the Contribute section on the side links to Launchpad, GitHub etc.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6854/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6855/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6856/

**Comment by hatched** [comment]
Thanks @huwshimi QA OK

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
