### PR TITLE
sandbox.js: close the WebSocket without reconnecting.

### PR DESCRIPTION
**Pull request by frankban**
Fix a repeating error when deploying bundles in sandbox mode: attempts to reconnect the WebSocket failed because the connection status was closed previously.

QA: try to deploy a bundle in sandbox mode.
In chrome, "WebSocket connection to 'wss://demo.jujucharms.com/ws' failed: Invalid frame header" will still happen, but that seems to be a Chrome issue, the errors don't repeat for ever, and the deployment should succeed. Further investigation on the Chrome issue can be done later, if we decide it's required.
The problem can be easily duped in the JS console:
`ws = new WebSocket('wss://demo.jujucharms.com/ws'); setTimeout(ws.close.bind(ws), 2000);`

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3471/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3472/
Test PASSed.

**Comment by jaycee** [comment]
QA:

In sandbox mode on FF I deployed mongo cluster. It deployed without issues in uncommitted state, though it did show up way off the initial screen (e.g. I had to zoom out to see it). Committing the changes with machines also worked appropriately. QA :ok:

**Comment by jaycee** [comment]
Code looks good :+1:. Thanks @frankban.

**Comment by hatched** [comment]
:+1: Thanks for tracking this down!

**Comment by frankban** [comment]
Thank you both for the reviews!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
