### PR TITLE
Add gallery-markdown to force download. Bump to 0.0.5.

### PR DESCRIPTION
**Pull request by bac**

### CODE REVIEW

**Comment by hatched** [comment]
:+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3266/
Test PASSed.

**Comment by jaycee** [comment]
:+1: thanks @bac.

**Comment by bac** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
