### PR TITLE
Ensure that the charmstore url has a trailing slash

### LINKED ISSUE #2144: charmstore_url too sensitive to trailing slash
If jujugui.charmstore_url does not end in a trailing slash, the GUI builds URLS like:

https://api.staging.jujucharms.com/charmstorev5/kibana/icon.svg

It should be more defensive.

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #2144.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- open `development.ini`
- change `jujugui.charmstore_url` to not have a trailing slash
- load the gui
- open the store
- the charm icons should load

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6083/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6084/
Test PASSed.

**Comment by bac** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
