### PR TITLE
Fix deployment props update

### PR DESCRIPTION
**Pull request by huwshimi**
Fixed passing of new props to the deployment components.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add a service
- place the unit on a machine
- commit
- remove the unit
- commit
- check that the deploy button is not active and there are no pending changes

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3269/
Test PASSed.

**Comment by hatched** [comment]
:+1: QA OK! Thanks for fixing this bug!

**Comment by huwshimi** [comment]
Thanks @hatched :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
