### PR TITLE
Fix equation for checking point inside service

### PR DESCRIPTION
**Pull request by makyo**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3718/
Test PASSed.

**Comment by makyo** [comment]
# QA

* deploy a few services
* click on each and make sure the inspector opens
* pan and zoom and repeat
* Ensure relation dragline snapping still works.

**Comment by hatched** [comment]
Thanks this works a lot better. I've created a few canvas related cards for issues I found qa'ing this branch but they are pre-existing.

:+1: QA :ok:

**Comment by makyo** [comment]
TY :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
