### PR TITLE
Post Deployment component now correctly updates and handles no-get-started gracefully

### PR DESCRIPTION
**Pull request by hatched**
- The post-deployment component now correctly updates when the state changes with a new bundle url to display. 
- It also gracefully handles the case where a bundle author has not provided a `getstarted.md` file.

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

- Deploy a bundle that has a `getstarted.md` file (CDK) and one that doesn't (any) and one more charm.
- You can remove all of the machines pre-deploy if you'd like.
- Once the charms have been added to the controller you can click the links and it should work as expected.

**Comment by huwshimi** [comment]
When I deployed this, the post deployment panel loaded and displayed "The bundle author has not provided a getstarted.md file." but I was expecting to see the getstarted for k8s

**Comment by huwshimi** [comment]
As discussed in IRC, this works as expected for now.

**Comment by hatched** [comment]
Thanks @huwshimi

**Pull request merged**
