### PR TITLE
Disable add keys button after adding GitHub keys

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3451.

### CODE REVIEW

**Comment by huwshimi** [comment]
[Disable add keys button after adding GitHub keys](https://trello.com/c/oe4lfyV4/353-disable-add-keys-button-after-adding-github-keys)

**Comment by huwshimi** [comment]
QA:
- start a new model and add an app
- open the deployment flow
- in the keys section choose GitHub and add a username
- click "Add keys"
- the keys should get added and the button should become disabled

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8538/

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge/2720

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
