### PR TITLE
Remove old test files

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
[Remove old test files](https://trello.com/c/w2Y9P8Qy/687-remove-old-test-files)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8742/

**Comment by frankban** [comment]
It would be nice if you provide some context about why those files can be safely removed, why they are no longer used in tests, what's used instead.  Otherwise this looks great thanks.

**Comment by huwshimi** [comment]
@frankban ah yep sorry, these are all files from the old test suite that were not being used any more. Old test assets, test setup and test data. Most of probably hasn't been used in a long long time.

**Pull request merged**
