### PR TITLE
Inspector scrolling

### PR DESCRIPTION
**Pull request by huwshimi**
Fixed bug where couldn't click in the area below the inspector. Update the inspector scrolling to allow us to choose which bits are scrollable.

Includes drive-by fix for a unique key warning.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3145/
Test PASSed.

**Comment by huwshimi** [comment]
QA:
- view `http://0.0.0.0:6543/:flags:/react/?deploy-target=bundle%2Fdjango-2`
- wait for the services to load
- in the space between the bottom of the inspector and the deployer bar check that you can click and drag the canvas around
- make your window smaller and check that the list of added services scrolls when there is not enough room to display them all
- click on a service
- check that the list of actions scrolls when the window is small our displays the full list if there is enough room
- click on the units and then added 5 more units
- check that it either displays all the units or it scrolls the list of units, but doesn't scroll the Scale service or Remove buttons

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3146/
Test PASSed.

**Comment by hatched** [comment]
:+1: 

QA Notes (Ubuntu 14.04 Chrome (Latest Stable)) :
Everything worked as outlined except the Scale Up component also had a horizontal scroll bar .
I was not able to click and drag the scroll bars but they were visible and it did scroll using the mouse wheel.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3147/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3148/
Test PASSed.

**Comment by anthonydillon** [comment]
Great stuff code and QA looks good in Chrome/FF. IE10 as a few issues but not related to this branch. Thanks @huwshimi :+1:

**Comment by hatched** [comment]
Thanks for the fix! :+1: :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/1077

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
