### PR TITLE
Don't reposition the crosshatch background as it no longer exists.

### PR DESCRIPTION
**Pull request by huwshimi**
Don't reposition the crosshatch background as it no longer exists.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- inspect the canvas and find the element `.topology-canvas`
- drag the canvas around
- check that the `style="..."` for `.topology-canvas` does not get `background-position` changes

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2974/
Test PASSed.

**Comment by anthonydillon** [comment]
Code and QA good :+1:

**Comment by hatched** [comment]
:+1: Thanks for this! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
