### PR TITLE
Do not pipe find to itself

### PR DESCRIPTION
**Pull request by hatched**

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Build the GUI dist and upload to Juju, it should work instead of failing on `zip`

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7312/

**Comment by jaycee** [comment]
QA OK, but it looks like you've got failures in CI. :frowning_face:

**Comment by hatched** [comment]
Thanks @jaycee 

Chrome just didn't start (again)

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7313/

**Pull request merged**
