### PR TITLE
Update React components to use es6 classes

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3026.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load the GUI as you normally would
- click on as many things as you can, watch out for binding issues.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7829/

**Comment by huwshimi** [comment]
These modules were updated one by one as can be seen if you step through the commits. For an idea of why the changes were done as they were you can see this guide on updating React components: https://www.newmediacampaigns.com/blog/refactoring-react-components-to-es6-classes.

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
