### PR TITLE
Fixed health bar width.

### PR DESCRIPTION
**Pull request by huwshimi**
Make the health bar width the same as the icon.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- drag a service to the canvas
- deploy
- check that the health bar width is the same width as the icon (96px)

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2602/
Test FAILed.

**Comment by jaycee** [comment]
QA notes:
The bar is the same width as the icon on several services. QA OK.

Code looks :+1: 

Thanks @huwshimi

**Comment by mitechie** [comment]
:+1: :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2610/
Test PASSed.

**Pull request merged**
