### PR TITLE
Modify state so that the search portion isn't greedy

### LINKED ISSUE #2873: Cannot navigate back to search results from deployed model
While connected to a model perform a search and then view one of the search results. Now hit the back button. You'll instead get an error about the search results not existing because it's trying to perform a search on the full url.

### PR DESCRIPTION
**Pull request by hatched**
Fixes #2873

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7745/

**Comment by hatched** [comment]
#### To QA

- Open the store and perform a search.
- View the entity and click 'back' you should be able to navigate back to the canvas.
- See #2963 which is exposed by this and will be resolved in a follow-up.

**Comment by jaycee** [comment]
QA OK.

**Comment by hatched** [comment]
Thanks!

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
