### PR TITLE
Adds retry count to auto login

### PR DESCRIPTION
**Pull request by jaycee**
When auto login happens, it must wait on the controller to connect. This
limits the number of times it tries to connect to the controller w/
timeout to 5

### CODE REVIEW

**Comment by jaycee** [comment]
QA:

Run with guiproxy passing `-config 'gisf:true, jujuEnvUUID:""'`.

Go to '/login' and open the console. You should get the api login popup. You should see a console message about retrying auto login. You should not see more than 5 such messages (they will be numbered).

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6686/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6687/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6688/

**Comment by jaycee** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6691/

**Pull request merged**
