### PR TITLE
Handle bzr-revisions missing in extra-info.

### PR DESCRIPTION
**Pull request by frankban**
Do not freeze when showing charm details in the case bzr-revisions is not there.

### CODE REVIEW

**Comment by fabricematrat** [comment]
:+1:  nice and simple !

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3964/
Test PASSed.

**Comment by urosj** [comment]
:+1:

**Comment by frankban** [comment]
Thanks for the reviews!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
