### PR TITLE
WIP Bakery: properly resend the original request.

### PR DESCRIPTION
**Pull request by frankban**
Work in progress, test-js-old fails, the branch has not been tested.
This is intended to fix https://github.com/juju/juju-gui/issues/2407

### CODE REVIEW

**Comment by frankban** [comment]
There is a lot of repeated code in the bakery. Also, I wonder if a recursive approach would be more beneficial in the retry strategy.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6720/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6721/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6722/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6762/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6763/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6764/

**Pull request closed without merging**
