### PR TITLE
Remove openstack from gisf store

### PR DESCRIPTION
**Pull request by makyo**
Addresses #2587 in the GUI

### CODE REVIEW

**Comment by makyo** [comment]
# QA

Run the gui with `guiproxy -config 'gisf:true'` and ensure there are only two promoted options; run again with `guiproxy -config 'gisf:false'` and ensure all three show up.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7865/

**Comment by makyo** [comment]
Passing CI http://ci-cge.jujugui.org:8080/job/juju-gui/7867/

**Comment by jaycee** [comment]
QA notes:

Using guiproxy pointed at prod (`-env production`) I opened the store, where I still saw Openstack.

**Comment by jaycee** [comment]
Ignore previous QA notes--I had a bad checkout of this branch. Trying again.

**Comment by jaycee** [comment]
QA notes:

Using guiproxy against prod (`-env production`) I do not see openstack in the store, as expected. The rest of the store looks fine.

Using guiproxy against a local controller, I do see openstack in the store.

QA OK.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
