### PR TITLE
Fix pressing enter for the deploy summary

### LINKED ISSUE #1724: Pressing enter in the deploy summary reloads the GUI
If you type a model name in the deploy summary and then press enter the GUI reloads, losing all your changes.

### PR DESCRIPTION
**Pull request by huwshimi**
Submit the form instead of reloading the page when pressing enter in the deployment summary form. Fixes #1724.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5172/
Test PASSed.

**Comment by anthonydillon** [comment]
Code looks good :+1:

**Comment by kadams54** [comment]
QA is :ok: 

*QA Notes:*

Deployed GUI as GISF. Created a controller per the instructions provided by @huwshimi, then proceed to create a new model. Added Wordpress, MySQL, and a relation between them. Clicked on the "Commit changes" button and stepped through the deployment process to setup a new AWS model. Typed the model name in and hit "Enter". The panel closed and my services deployed successfully.

**Comment by kadams54** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
