### PR TITLE
Make the model name in the header editable

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #2085.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- start a new model
- click in the model name in the header and change the name
- click out of the field
- the model name should update in the page title
- connect to an existing model
- the model name should now not be editable

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7894/

**Comment by hatched** [comment]
QA Notes:

When the model is committed: 
- I click on the model name it doesn't open the switcher.
- It selects the model name text and I can't click anywhere to unselect. It could probably use a no-select style.

When the model is uncommitted:
- I can input invalid characters and invalid name. It should validate on keypress.
- I can input multi-line data into it.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7909/

**Comment by hatched** [comment]
@huwshimi is this one ready for another qa? I just see that the [QA bad] and [needs-followup] labels are still sticking around

**Comment by huwshimi** [comment]
@hatched I'm still working on this one.

**Comment by huwshimi** [comment]
@hatched what do you think about leaving the model name validation to the deployment flow? The user has to pass through that and will get told if the name is not valid. Otherwise we could figure out a bit of UI to show the errors on the canvas.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7947/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7951/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7952/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7953/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7969/

**Comment by huwshimi** [comment]
@hatched I've updated this to do the validation on the canvas. Let me know what you think.

**Comment by hatched** [comment]
QA OK
Thanks @huwshimi 

After using it though maybe the name should error on blur if it contains invalid characters. If I type `purple-` it shows an error message before I finish the string `purple-batman`.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7974/

**Comment by huwshimi** [comment]
Thanks @hatched and @makyo, I've updated it to work on blur. :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
