### PR TITLE
Remove editorial.js and charmresults.js

### PR DESCRIPTION
**Pull request by hatched**
These two files are unused, left over from the restructuring of the charm list.

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Play around with the charmbrowser, it should work as usual.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2402/
Test FAILed.

**Comment by kadams54** [comment]
:+1: QA is :ok:, great to see all this code go!

**Comment by hatched** [comment]
Thanks! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
