### PR TITLE
Do not use untitled-model as the default name for new models.

### LINKED ISSUE #2299: The default model name is untitled-model, which is suboptimal
It is suboptimal for a couple of reason:
1) it's not descriptive at all, at least we could switch to something like {cloud-name}-{incremental-number} or similar;
2) it generates confusion as untitled-model is the model displayed in disconnected mode.

### PR DESCRIPTION
**Pull request by frankban**
This is trivial and fixes #2299

### CODE REVIEW

**Comment by frankban** [comment]
QA: 
- use this branch against a real controller;
- try to deploy from an existing model and check that the model name in the deployment flow is the name of the model;
- try to deploy on a new model and check that the default model name in the deployment flow input is "mymodel";
- in both cases, ensure deploying works.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6626/

**Comment by Lukewh** [comment]
QA works and code 👍

**Comment by frankban** [comment]
Thanks @Lukewh for the review!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
