### PR TITLE
Search results not displaying all returned results from api

### PR DESCRIPTION
**Pull request by Lukewh**
*fixes* https://github.com/juju/juju-gui/issues/2435

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6771/

**Comment by Lukewh** [comment]
The way the code was suggests the search results were consciously done to *only* return promulgated or community results. I've created a hybrid with an optional flag.

**QA**
- On guimaas search for 'term' you should see two results.
- In https://github.com/Lukewh/juju-gui/blob/f9183e992290e10e7457bdc50bac033a59504dab/jujugui/static/gui/src/app/components/charmbrowser/charmbrowser.js#L155 change 'true' to 'false'
- Repeat the search for 'term' you should see three results.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6772/

**Comment by Lukewh** [comment]
This has been made obsolete by https://github.com/juju/juju-gui/pull/2829

**Pull request closed without merging**
