### PR TITLE
Handle changes in ModelInfo and CreateModel responses.

### PR DESCRIPTION
**Pull request by frankban**
These calls used to return cloud names, now they return cloud tags.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5803/
Test PASSed.

**Comment by urosj** [comment]
👍 shipit

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
