### PR TITLE
Upgrade React to 16.0.0.

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #1709.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- clean-all and rebuild
- poke around in the GUI, there should be no errors or warnings

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8173/

**Comment by Lukewh** [comment]
## QA BAD

Errors when click around in the inspector regarding 'two children with the same key'. Things still work, but I believe it's a new error.

**Comment by huwshimi** [comment]
@Lukewh I wasn't able to get those errors. Do you happen to remember exactly what you did to get them?

**Comment by Lukewh** [comment]
@huwshimi false alarm, cleaning building and refreshing again seemed to work.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
