### PR TITLE
Use metrics endpoint

### PR DESCRIPTION
**Pull request by huwshimi**
Use the metrics endpoint instead of checking for a metrics.yaml file.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- connect to guimaas
- search for landscape mock
- check that you get plans

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5335/
Test PASSed.

**Comment by hatched** [comment]
Thanks for this cleanup! :+1:

**Comment by bac** [comment]
Followed QA instructions, pointed to guimaas, found the charm referenced, and saw no plans.  @hatched was going to follow up.

**Comment by bac** [comment]
:+1:

**Comment by hatched** [comment]
It appears that there may be a bug in the query response, lets hold off on landing this until we get that confirmed/resolved.

**Comment by kadams54** [comment]
QA'd and OK'd by @urosj. :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
