### PR TITLE
Use the pre-bound switchModel method for rendering the user profile.

### LINKED ISSUE #3146: Unable to switch to models from profile
Using the `develop` branch when  you view your profile, select "Manage" a model, you'll be navigated to /gui instead of to the model.

### PR DESCRIPTION
**Pull request by hatched**
Fixes #3146

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Switch to models from the user profile "Manage" button. It should actually switch to them instead of `/gui`

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7994/

**Comment by hatched** [comment]
Thanks @makyo :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
