### PR TITLE
Display cookie notification using a component

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- start the GUI using guiproxy and set `GTM_enabled: true`
- load the gui in a private browser and log in
- the cookie notice should appear
- close the cookie via the x
- reload the page, the cookie notice should not reappear

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7759/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7760/

**Comment by Lukewh** [comment]
Should this not use the notification component that includes the new vanilla styles and colours?

**Comment by huwshimi** [comment]
@Lukewh that's a good question. @spencerbygraves do you happen to know?

**Comment by spencerbygraves** [comment]
@huwshimi we recently did a cookie notification for ubuntu.com using the new style, so we should use that if possible. Here's how it looks:

image

**Comment by huwshimi** [comment]
I've updated this branch to use the new notification style.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7767/

**Comment by huwshimi** [comment]
@Lukewh All good, this is better.

**Comment by Lukewh** [comment]
## QA-OK

I think maybe the link should be `target="_blank"` just incase someone has started modelling. Otherwise looks great!

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7773/

**Comment by huwshimi** [comment]
Thanks @Lukewh and @hatched :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
