### PR TITLE
Updated the applications/machines switcher

### PR DESCRIPTION
**Pull request by anthonydillon**

### CODE REVIEW

**Comment by anthonydillon** [comment]
## QA
- Check the application/machines switcher matches the new design [1]
- Check it works the same as before
- Check small screen still looks good

[1] https://github.com/CanonicalLtd/juju-design/issues/106

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5517/
Test PASSed.

**Comment by hatched** [comment]
Looks good thanks @anthonydillon 

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
