### PR TITLE
Remove agreements and budgets component form profile.

### PR DESCRIPTION
**Pull request by hatched**

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

In incognito, load the GUI, it shouldn't try and open two windows when you enter the user profile for the first time.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6747/

**Comment by jaycee** [comment]
QA:

I logged in with gui running with guiproxy and gisf true.

I went to /login; I got one tab, no extra reload of the tab as I had seen before.

QA OK.

**Comment by frankban** [comment]
Looks good, thanks for this last minute improvement.
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
