### PR TITLE
Allow deploy target on anon disconnected models

### LINKED ISSUE #2416: gisf: storefront's "add to new model" does not work
As a totally anonymous user (incognito mode), navigate the storefront to a charm detail, for instance kibana. At this point, the "Add to new model" button points to `/new/?deploy-target=cs:trusty/kibana-15`. That path does not work, the GUI redirects to /login and then hangs.

To dupe this you must set up the current `gui-handles-auth` branch of the storefront with the most recent GUI from `develop` branch, then `make run`, then log in and activate the GUI switch for everyone at `/_switchboard`. Then, in another browser, use incognito mode to start from scratch.

### PR DESCRIPTION
**Pull request by hatched**
Fixes #2416

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

see referenced issues for repro steps.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6739/

**Comment by jaycee** [comment]
QA OK.

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
