### PR TITLE
Add addCharm to ECS

### PR DESCRIPTION
**Pull request by hatched**

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5358/
Test PASSed.

**Comment by urosj** [comment]
QA in GIJoe was 🆗 👍 for both LXD and AWS.

**Comment by frankban** [comment]
Thanks for implementing this functionality so quickly Jeff! Code looks good and ready to go.
👍  and :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
