### PR TITLE
Fix the spinner when loading entity details

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3513.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- open the store and click on a charm or bundle
- the details should load and while they do you should see a spinner (you may need to use the dev tools to simulate an Australian connection)

**Comment by huwshimi** [comment]
[Fix the spinner when loading entity details](https://trello.com/c/dJtrWrzZ/342-fix-the-spinner-when-loading-entity-details)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8529/

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
