### PR TITLE
Increase the default size of the AWS logo

### PR DESCRIPTION
**Pull request by anthonydillon**
Fixes: https://github.com/juju/juju-gui/issues/2225

### CODE REVIEW

**Comment by anthonydillon** [comment]
## QA
- Deploy application 
- Enter DF and see that the AWS logo is bigger then it is on prod

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6281/
Test PASSed.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
