### PR TITLE
Remove pendingResources from the ECS when charm parent record is removed.

### LINKED ISSUE #3304: addPendingResources not cleared when charm parent record is cleared.
To reproduce add the 'jujushell' charm to a new canvas. Before deploying, hit the "destroy" button in the inspector. You'll now get an error in the console where the application in the `application.get('icon')` is null.

```js
        case '_addPendingResources':
          const applicationName = change.command.args[0].applicationName;
          const application = services.getServiceByName(applicationName);
          changeItem.icon = application.get('icon');
```

### PR DESCRIPTION
**Pull request by hatched**
Fixes #3304

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA
Add the "jujushell" charm to the canvas.
Click the "Destroy" button in the inspector.
The Deployment Flow should no longer be able to be opened and the ecs should be empty `JujuGUI.ecs.changeSet`

**Comment by jujugui** [comment]
Build finished.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8246/

**Comment by hatched** [comment]
Thanks @huwshimi 

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
