### PR TITLE
New service blocks

### PR DESCRIPTION
**Pull request by anthonydillon**
Updated the design of the new service blocks to use svg circle.

### CODE REVIEW

**Comment by jujugui** [comment]
please test this

**Comment by anthonydillon** [comment]
QA:
- Add a few services and deploy them
- Toggle the show and hide
- Create some relations
- Highlight a service and see the others still hide as expected

**Comment by anthonydillon** [comment]
Says test pass successfully when run manually.
http://ci.jujugui.org:8080/job/juju-gui/2827/console#spinner

**Comment by hatched** [comment]
:+1: But I would like to see a test for the generated svg's now that we are actually generating them instead of just showing an asset.

NO QA

**Comment by huwshimi** [comment]
QA only. As discussed in person there are three followups:

- relation lines don't quite touch the edges of the circle
- the unit statuses are not reflected by the circle border
- the relation line snapping needs to be removed

**Comment by makyo** [comment]
:+1: QA okay with @huwshimi's follow-ups

**Comment by anthonydillon** [comment]
Thanks all, I have follow cards for @huwshimi comments.

**Comment by anthonydillon** [comment]
:shipit:

**Comment by anthonydillon** [comment]
:shipit:

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
