### PR TITLE
Handle stopping mega-watcher more gracefully.

### PR DESCRIPTION
**Pull request by frankban**
Avoid displaying a console error each time the user switches to another model.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5381/
Test PASSed.

**Comment by hatched** [comment]
Thanks for this cleanup @frankban :+1: :ok:

**Comment by frankban** [comment]
Thanks for the review and QA Jeff.
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
