### PR TITLE
Remove the crosshatched background of the canvas

### PR DESCRIPTION
**Pull request by anthonydillon**
Replaced with the new #f5f5f5 flat background color.

### CODE REVIEW

**Comment by jujugui** [comment]
please test this

**Comment by hatched** [comment]
:+1: QA OK 
Thanks for doing this on pyramid-fork!

**Comment by hatched** [comment]
:shipit: 

Other reviews were done on the previous branch targeting develop

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/981

**Comment by hatched** [comment]
spurious landing failure...

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/982

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/983

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/989

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/991

**Comment by hatched** [comment]
Now that CI is fixed the unit tests are now failing with this branch, can you please update from pyramid-fork and then take a look at those failing tests. Thanks!

**Comment by hatched** [comment]
Unit tests are now passing. Thanks @anthonydillon 

http://ci.jujugui.org:8080/job/juju-gui/2812

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
