### PR TITLE
Enable the new flow when using the blues flag

### PR DESCRIPTION
**Pull request by huwshimi**
In preparation for the removal of the old blues flow this sets the new flow as default under the blues flag.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- use the blues flag
- add a machine or service
- click deploy
- you should see the new flow

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5523/
Test PASSed.

**Comment by hatched** [comment]
Thanks @huwshimi :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
