### PR TITLE
Bump version.

### PR DESCRIPTION
**Pull request by jaycee**

### CODE REVIEW

**Comment by bac** [comment]
:+1: :+1:

**Comment by urosj** [comment]
Not sure, needs thorough QA!

**Comment by urosj** [comment]
:+1: :)

**Comment by jaycee** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/1149

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3368/
Test PASSed.

**Pull request merged**
