### PR TITLE
Remove all references to jem and jimm

### PR DESCRIPTION
**Pull request by hatched**
Because jem and jimm are no longer necessary all code which references them as been removed.

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Deploy using Juju 2 and the GUI should work as expected.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5879/
Test PASSed.

**Comment by hatched** [comment]
Thanks @frankban 

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
