### PR TITLE
Do not provide num_units for subordinates

### PR DESCRIPTION
**Pull request by makyo**

### CODE REVIEW

**Comment by makyo** [comment]
# QA

* Deploy a service and a subordinate (I used django and gunicorn) and commit, auto-placing units
* Export the environment
* Open the bundle and ensure the subordinate service doesn't have a num_units field

**Comment by hatched** [comment]
:+1: Will QA

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2569/
Test PASSed.

**Comment by hatched** [comment]
QA OK! Tested in a real environment and exported with no num units as expected.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/900

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
