### PR TITLE
Disable env switcher on environments where the EnvironmentManager is not supported

### LINKED ISSUE #1168: Model switcher error for non JES enabled models
If you load the new GUI into a non JES enabled model you will see that the model switcher is still shown and there is an error in the console that it's not supported. We should not show the switcher if it's not supported to prevent this error.

### PR DESCRIPTION
**Pull request by hatched**
Fixes #1168

### CODE REVIEW

**Comment by hatched** [comment]
We dont' have any tests for the component rendering methods yet so that's why one wasn't added here.

#### To QA

You will need to package this up into a charm and deploy it into a JES enabled env and a non-JES env and it should show/hide appropriately.

**Comment by bac** [comment]
code :+1:
Can QA later unless someone beats me to it.

**Comment by frankban** [comment]
:+1: no QA

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4096/
Test PASSed.

**Comment by bac** [comment]
QA-super

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4107/
Test PASSed.

**Comment by hatched** [comment]
Thanks all! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
