### PR TITLE
Show a notification when importing a bundle from the charmbrowser

### PR DESCRIPTION
**Pull request by hatched**

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA
```
juju bootstrap
juju deploy cs:~juju-gui/trusty/juju-gui-51
juju set juju-gui juju-gui-source="https://github.com/hatched/juju-gui.git show-notification-from-cb"
```

Drag a bundle from the charmbrowser to the canvas. A notification should be shown.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2575/
Test PASSed.

**Comment by makyo** [comment]
:+1: QAing now (using ec2 because lxcs aren't cutting it for me, sorry for the delay)

**Comment by makyo** [comment]
QA okay

**Comment by hatched** [comment]
Thanks! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
