### PR TITLE
Align charm tables names and layout as per spec

### PR DESCRIPTION
**Pull request by barrymcgee**

### CODE REVIEW

**Comment by barrymcgee** [comment]
The design spec can be found here: https://raw.githubusercontent.com/CanonicalLtd/juju-design/master/Profile/12-Charms-table-specs.png?token=AAe24iOBovFa83D5oeDwipQ-Q3cey7Agks5aX3WqwA%3D%3D

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8403/

**Comment by hatched** [comment]
QA Notes:

- The charm icons do not line up as in the spec.
- The release #'s do not line up, but only by a pixel or so.

screen shot 2018-01-10 at 12 18 12 pm

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8404/

**Comment by hatched** [comment]
According to the design, the description is supposed to line up with the name.
screen shot 2018-01-11 at 10 19 15 am

**Comment by barrymcgee** [comment]
@hatched Fix pushed, QA again please?

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8409/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
