### PR TITLE
Entity links

### PR DESCRIPTION
**Pull request by huwshimi**
Fixed charm owner link error. Added contribute and submit a bug links.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- view details for a charm
- click on the owner
- in the GUI open the console
- there should be no error
- scroll down to "More information"
- you should see "Submit a bug" and "Contribute" links

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3914/
Test PASSed.

**Comment by hatched** [comment]
:+1: :ok: :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
