### PR TITLE
Fix upgrade by local charm

### LINKED ISSUE #3243: Upgrading a local charm with another local charm has syntax error

### PR DESCRIPTION
**Pull request by hatched**
Fixes #3243

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Deploy a local charm with a name with a dash in it ie) `gui-plugin`.
Then try and upgrade that charm by dropping the same charm on the canvas.
Upgrade the charm, give it a moment, the charm Id should increment in the inspector.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8188/

**Comment by hatched** [comment]
I was not able to reproduce this, would you mind trying again from a freshly checked out branch?

**Comment by hatched** [comment]
Issues:
- When uploading invalid zip's the error is 'undefined' but one was returned from Juju.
- When upgrading charms with a local charm there is no indication that you must select one of the applications to continue.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8190/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
