### PR TITLE
Remove old env header

### PR DESCRIPTION
**Pull request by huwshimi**
Remove the old environment header. Enable the new component.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- view the gui with no flags
- check that there is a new env header that reads "0 services | 0 machines"
- check that you can open the machine view and that adding services updates the header
- check the same with `/:flags:/react/`

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3380/
Test FAILed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3381/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3382/
Test PASSed.

**Comment by jaycee** [comment]
QA notes:

I had the header in both views and it updated in both cases as I added a machine with hadoop.

QA OK.

:+1:

**Comment by hatched** [comment]
Thanks for the review and qa! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/1157

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
