### PR TITLE
Load fonts locally

### PR DESCRIPTION
**Pull request by anthonydillon**

### CODE REVIEW

**Comment by anthonydillon** [comment]
Check that the fonts load locally from CSS instead of the Google font. This fixes the bold font from taking over on 15.10.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3704/
Test PASSed.

**Comment by huwshimi** [comment]
QA OK :+1: thanks heaps for this @anthonydillon!

**Comment by hatched** [comment]
:+1: Looks good! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
