### PR TITLE
Remove app ready and fix state init in tests.

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6254/
Test FAILed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6258/
Test FAILed.

**Comment by huwshimi** [comment]
Apologies for adding to this PR, but I've pushed some more changes as this PR didn't have any reviews.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6262/
Test FAILed.

**Comment by hatched** [comment]
Thanks @huwshimi looks good, if you could just fix up the lint error then this can land.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6266/
Test FAILed.

**Pull request merged**
