### PR TITLE
Even more ux qa updates

### PR DESCRIPTION
**Pull request by huwshimi**

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- Row hovers in the inspector should be #f7f7f7 not #f5f5f5
- Update of type sizes in unit view in the inspector
- All 14px text in the inspector should have a line height of 21px
- Inspector expose page type sizes are not consistent with the rest of the inspector
- When you expose a service there is no hover over for the units shown below
- You should be able to click the uncommitted notification counter to open up the deployment summary
- When viewing charm details, the store icon and word should be orange
- When search is activated, the word “Store” next to the icon should disappear (only the trolley icon should remain)

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3788/
Test PASSed.

**Comment by anthonydillon** [comment]
Looks awesome @huwshimi code and QA are good :+1:

**Comment by hatched** [comment]
:+1: QA :ok:
Nice improvements, I see that you also were able to get rid of a component, good to see! Generic components ftw!

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
