### PR TITLE
Tighten alignment within relation popup.

### PR DESCRIPTION
**Pull request by kadams54**

### CODE REVIEW

**Comment by kadams54** [comment]
## QA

1. Add both Wordpress and Apache2 to the canvas.
2. Create multiple relations between them.
3. Deploy.
4. Click on the center icon in the relation and confirm that everything (text and icons) is all nicely aligned within the popup.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3842/
Test PASSed.

**Comment by hatched** [comment]
:+1: QA :ok: :shipit: 
Thanks!

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
