### PR TITLE
Fix env calls

### PR DESCRIPTION
**Pull request by huwshimi**
Add env calls to the sandbox provider.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- view `http://0.0.0.0:6543/:flags:/react/`
- check that there are no errors in the console
- in the header click List
- you should see a sandbox env listed
- type a new env name
- click Create
- you should get a warning but not an error in the console

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3097/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3098/
Test PASSed.

**Comment by hatched** [comment]
:+1: QA :ok: :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
