### PR TITLE
Fix add units button position

### LINKED ISSUE #1525: Add units + is out of center in machine view
screenshot from 2016-04-07 13 46 29

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #1525.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- open the machine view
- check that the button is aligned to the right hand side (matching the dotted border below)

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5067/
Test PASSed.

**Comment by hatched** [comment]
Sorry the bug report wasn't very clear. The + and x are not centered in the green square, they are a pixel or two down.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5083/
Test PASSed.

**Comment by kadams54** [comment]
QA is :ok: and :+1: on the code. You know what would be sweet? If we had an animation that rotated the plus into the x and vice versa when clicked.

**Comment by kadams54** [comment]
:shipit: - Thanks @huwshimi!

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
