### PR TITLE
Fix state test

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes: #3681.

### CODE REVIEW

**Comment by huwshimi** [comment]
[Fix state test](https://trello.com/c/2hEgddM5/669-fix-state-test)

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8708/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8709/

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
