### PR TITLE
Don't try and display the env name when logging in.

### LINKED ISSUE #1518: Remove env name from the login screen
At the moment we do not not know what the name of the model the user is trying to log in as so we need to just remove the env name display from the login screen. Currently the fallback is the uuid which is pretty unsightly.

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #1518.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load the gui
- logout (in the console run `app.logout()`)
- check that above the form in now reads "Login" instead of the model name

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4779/
Test PASSed.

**Comment by hatched** [comment]
:+1: :ok: Thanks for this fix!

:shipit: as trivial

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
