### PR TITLE
Set up python packaging for the juju gui.

### PR DESCRIPTION
**Pull request by jaycee**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2719/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2720/
Test PASSed.

**Comment by jaycee** [comment]
QA:

Run `make clean-all dist`. Confirm that dist/jujugui-0.0.1.tar.gz is created.

Unpack the tarball in a new directory. Confirm that jujugui/static/gui/build/app exist.

Run the gui package. Create a new directory and copy the development.ini file into it. From the new directory, assuming the path to the tarball is $package_path:

```
virtualenv .
bin/pip install $package_path
bin/pserve development.ini
```

The gui should run; confirm it's running appropriately.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2721/
Test PASSed.

**Comment by frankban** [comment]
Code :+1: will QA asap.

**Comment by frankban** [comment]
I encountered a QA error:
```
 % make clean-all dist                                                                                                                                                                                                                    (package-gui) gui
rm -rf bin include lib local man share build node_modules
find . -name '*.pyc' -exec rm -f {} +
find . -name '*.pyo' -exec rm -f {} +
find . -name '*~' -exec rm -f {} +
rm -rf dist
rm -rf *.egg-info
virtualenv .
New python executable in ./bin/python
Installing Setuptools..............................................................................................................................................................................................................................done.
Installing Pip.....................................................................................................................................................................................................................................................................................................................................done.
git clone --depth=1 "git@github.com:juju/juju-gui-downloadcache.git" /home/frankban/devel/juju-gui/juju-gui/downloadcache
Cloning into '/home/frankban/devel/juju-gui/juju-gui/downloadcache'...
remote: Counting objects: 66, done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 66 (delta 34), reused 66 (delta 34), pack-reused 0
Receiving objects: 100% (66/66), 21.68 MiB | 3.41 MiB/s, done.
Resolving deltas: 100% (34/34), done.
Checking connectivity... done
bin/pip install --no-index --no-dependencies --find-links file:////home/frankban/devel/juju-gui/juju-gui/downloadcache/saucy -r requirements.txt
Ignoring indexes: https://pypi.python.org/simple/
Downloading/unpacking Mako==1.0.1 (from -r requirements.txt (line 1))
  Could not find any downloads that satisfy the requirement Mako==1.0.1 (from -r requirements.txt (line 1))
Cleaning up...
No distributions at all found for Mako==1.0.1 (from -r requirements.txt (line 1))
Storing complete log in /home/frankban/.pip/pip.log
make: *** [lib/python2.7/site-packages/pyramid] Error 1
```

**Comment by frankban** [comment]
Ok I updated my GUI lxc to vivid and now QA is ok after installing `python-virtualenv` and `python-setuptools` manually, so I guess these packages should be included in the sysdeps.
Great to see the GUI installed via pip!

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2722/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2723/
Test PASSed.

**Comment by bac** [comment]
:+1:

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2724/
Test FAILed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2725/
Test FAILed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2727/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2729/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2730/
Test PASSed.

**Comment by jaycee** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-merge/971

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
