### PR TITLE
Always translate a workload in maintenance to a pending state.

### PR DESCRIPTION
**Pull request by frankban**
Fixes https://github.com/juju/juju-gui/issues/2190

### CODE REVIEW

**Comment by frankban** [comment]
TO QA, this command could be handy, for instance for an etcd unit:
`juju run --unit etcd/0 status-set maintenance`

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7130/

**Comment by frankban** [comment]
Thanks for the reviews!

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
