### PR TITLE
Add in relations from v4; driveby fix for subordinates

### PR DESCRIPTION
**Pull request by makyo**
Fixes release blocker of not being able to add relations between services due to misplaced provides/requires.  Drive by fix for 1369576.

### CODE REVIEW

**Comment by makyo** [comment]
# QA

1. Ensure that you can deploy two services and add a relation between them (ensure in real env as well)
2. Ensure that, after adding a subordinate such as puppet, that it does not show up in unplaced units.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/2342/
Test PASSed.

**Comment by kadams54** [comment]
:+1: QA'd locally and was OK. Was never able to get the env up and running in EC2. I think the problems in the real env were due to release complications - i.e., config needing to be updated in both the app and the charm, so I'd be fine with merging this.

QA Notes:

Locally, related wordpress and mysql just fine, as well as confirmed that puppet was not added to unplaced units. When I tried to QA in EC2, I kept getting EOF errors from server.go. @makyo had me manually update charmstore config, but that didn't resolve the problem.

**Comment by mitechie** [comment]
:+1: ty for the updates

**Comment by makyo** [comment]
Unable to repro the EC2 EOF errors in two test deploys, agree that it was due to release complications.  Thanks for the reviews :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
