### PR TITLE
Enable support for using Juju to get bundle changes.

### PR DESCRIPTION
**Pull request by frankban**
Also fall back to GUI server endpoints if Juju bundle
deployment is not available.

### CODE REVIEW

**Comment by frankban** [comment]
This will be QAed later when creating a new release and uploading to bastion.

**Comment by makyo** [comment]
Awesome, thanks! :+1:

**Comment by urosj** [comment]
:+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/3293/
Test PASSed.

**Comment by frankban** [comment]
Thank you both for the reviews!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
