### PR TITLE
Tidy up profile credential tables alignment

### PR DESCRIPTION
**Pull request by barrymcgee**

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8446/

**Comment by barrymcgee** [comment]
## QA

- Power up credentials tab in the Profile view
- Check that columns align

Note: there is no specific spec doc for this table so alignments are based off the other tables.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
