### PR TITLE
Allow SLA and budget to be selected on deploy

### PR DESCRIPTION
**Pull request by hatched**

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8743/

**Comment by huwshimi** [comment]
During QA I hit deploy and got `Unable to authorize SLA` and the console had:
```
POST https://api.staging.jujucharms.com/omnibus/v3/sla/authorize 401 (Unauthorized)
not member of a reseller group
```
Is there something I need to set up?

**Comment by hatched** [comment]
Looks like some stuff was reset, that's now been resolved, plz try again :)

**Comment by huwshimi** [comment]
QA OK, I got SLA standard which was the one I chose in the expert flow.

**Comment by hatched** [comment]
Thanks! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Pull request merged**
